// koffee 1.16.0
a.dot(b);
a.times(Math.cos(3));
a.times(2);
a.dot(a);
b.times(b.dot(b));
b.times(b.dot(b));
b.dot(b.times(b.dot(b)));
b.dot(b.times(b.dot(b)));
b.dot(b.times(b.dot(b)));
b.dot(b.times(b.dot(b)));
(b.dot(b)) * (b.dot(b));
a.dot(a.times(f));
b.dot(b.times(f).times(f));
b.dot(a.times((b.times(f)).times(1.1).times(2.2).dot(a.times(2))));
b.dot(a.times((b.times(f)).times(1.1 * 2.2).dot(a.times(2))));
b.times(b.dot(a) * ((b.times(f)).times(1.1 * 2.2).dot(a.times(2))));
a.times(b.dot(a.times((b.times(f)).times(1.1 * 2.2).dot(a.times(2)))));
b.times(b.dot(a) * ((b.times(f)).times(1.1).times(2.2).dot(a.times(2))));
a.plus(b).plus(c);
a.minus(b);
a.minus(b).minus(c);
(a.plus(b)).minus(a).plus(b).minus(a);
a.minus(b.minus(a)).minus(b).minus(a);
a.dot(a.plus(b));
c.dot(a.minus(b));
a.minus(b.dot(c));
a.dot(b).minus(c);
a.plus(b).minus(c.minus(b).minus(a));
a.cross(b);;
