// koffee 1.16.0
2 * a;
a * 2;
a * a;
b * b * b;
(b * b) * b;
b * b * b * b;
(b * b) * b * b;
(b * b * b) * b;
b * b * b * b;
(b * b) * (b * b);
a * f * a;
b * f * f * b;
a * ((b * f) * 1.1 * 2.2 * (2 * a)) * b;
a * ((b * f) * (1.1 * 2.2) * (2 * a)) * b;
b * a * ((b * f) * (1.1 * 2.2) * (2 * a)) * b;
a * ((b * f) * (1.1 * 2.2) * (2 * a)) * b * a;
b * a * ((b * f) * 1.1 * 2.2 * (2 * a)) * b;
a + b + c;
a - b;
a - b - c;
a + b - a + b - a;
a - b - a - b - a;
a + b - c - b - a;;
