

injectFeature = (options) -> # make sure that options has a feature set
    
    options ?= {}
    
    defaultFeatures = 
        header:                 false
        rewrite:                true
        'negative-index':       true
        'config-parameters':    true
        'constructor-shortcut': true
    
    { extend } = require './helpers'
    
    feature = extend defaultFeatures, options.feature ? {}
    
    options = extend { feature: feature }, options
    options

FEATURES = [
    [ 'header',                    'prefix with "Generated by" header', false ]
    [ 'rewrite',                   'rewrite tokens',                    true  ]
    [ 'config-parameters',         'enable config parameters',          true  ]
    [ 'constructor-shortcut',      'replace @: with constructor:',      true  ]
    [ 'negative-index',            'replace a[-1] with a[-1..-1]',      true  ]
]

module.exports = { FEATURES, injectFeature }
