###
00000000  00000000   0000000   000000000  000   000  00000000   00000000   0000000  
000       000       000   000     000     000   000  000   000  000       000       
000000    0000000   000000000     000     000   000  0000000    0000000   0000000   
000       000       000   000     000     000   000  000   000  000            000  
000       00000000  000   000     000      0000000   000   000  00000000  0000000   
###

FEATURES = [
    [ 'header',                    'prefix with "generated by" header',        false ]
    [ 'config-parameters',         'enable config parameters',                 true  ]
    [ 'console-shortcut',          'replace log with console.log',             true  ]
    [ 'constructor-shortcut',      'replace @: with constructor:',             true  ]
    [ 'negative-index',            'replace a[-1] with a[-1..-1]',             true  ]
    [ 'rewrite',                   'rewrite tokens',                           true  ]
]

injectFeature = (options) -> # make sure that options has a feature set
    
    options ?= {}
    
    defaultFeatures = {}
    FEATURES.map (f) -> defaultFeatures[f[0]] = f[2]
    
    { extend } = require './helpers'
    
    feature = extend defaultFeatures, options.feature ? {}
    
    options = extend { feature: feature }, options
    options

module.exports = { FEATURES, injectFeature }
