
/*
 0000000   0000000   00     00  00     00   0000000   000   000  0000000    
000       000   000  000   000  000   000  000   000  0000  000  000   000  
000       000   000  000000000  000000000  000000000  000 0 000  000   000  
000       000   000  000 0 000  000 0 000  000   000  000  0000  000   000  
 0000000   0000000   000   000  000   000  000   000  000   000  0000000
 */
var BANNER, EventEmitter, FEATURES, Koffee, SWITCHES, compileOptions, compilePath, compileScript, compileStdio, error, exec, features, findDirectoryIndex, fs, helpers, hidden, log, makePrelude, mkdirp, nopt, opts, outputPath, parseOptions, path, print, printLine, printTokens, printWarn, ref, run, spawn, startRepl, timeLog, usage, useWinPathSep, version, wait, watchDir, watchFile, watchPath, writeJs;

fs = require('fs');

path = require('path');

nopt = require('nopt');

helpers = require('./helpers');

Koffee = require('./koffee');

ref = require('child_process'), spawn = ref.spawn, exec = ref.exec;

EventEmitter = require('events').EventEmitter;

useWinPathSep = path.sep === '\\';

helpers.extend(Koffee, new EventEmitter);

log = console.log;

error = console.error;

print = function(line) {
    return process.stdout.write(line);
};

printLine = function(line) {
    return process.stdout.write(line + '\n');
};

printWarn = function(line) {
    return process.stderr.write(line + '\n');
};

hidden = function(file) {
    return /^\.|~$/.test(file);
};

BANNER = "Usage: koffee [options] path/to/script -- [args]";

FEATURES = [['header', 'prefix with "Generated by" header'], ['rewrite', 'rewrite tokens'], ['config-parameters', 'enable config parameters'], ['constructor-shortcut', 'replace @: with constructor:'], ['negative-index', 'replace a[-1] with a[-1..-1]']];

SWITCHES = [['-b', '--bare', 'compile without a top-level function wrapper', Boolean], ['-c', '--compile', 'compile to JavaScript and save as .js files', Boolean], ['-e', '--eval [STRING]', 'pass a string from the command line as input', [String, Array]], ['-f', '--features', 'list available features', Boolean], ['', '--no-[feature]', 'disable a feature, e.g. --no-negative-index', null], ['-h', '--help', 'display this help message', Boolean], ['-j', '--js', 'print out the compiled JavaScript', Boolean], ['-m', '--map', 'generate source map and save as .js.map files', Boolean], ['-M', '--inline-map', 'generate source map and include it directly in output', Boolean], ['-n', '--noop', 'does nothing, for debugging purposes', Boolean], ['-o', '--output [DIR]', 'set the output directory for compiled JavaScript', String], ['-p', '--parse', 'print out the parse tree that the parser produces', Boolean], ['-r', '--require [MODULE]', 'require the given module before eval or REPL', [String, Array]], ['-s', '--stdio', 'listen for and compile scripts over stdio', Boolean], ['-t', '--tokens', 'print out the tokens that the lexer/rewriter produce', Boolean], ['-v', '--version', 'display the version number', Boolean], ['-w', '--watch', 'watch scripts for changes and rerun commands', Boolean]];

opts = {};

parseOptions = function() {
    var known, o, short, toggles;
    toggles = ['bare', 'compile', 'features', 'help', 'inline-map', 'js', 'map', 'parse', 'stdio', 'tokens', 'version', 'watch', 'Debug'];
    known = {
        Debug: Boolean
    };
    short = {
        D: '--Debug'
    };
    SWITCHES.map(function(s) {
        var l;
        l = s[1].split(' ')[0].slice(2);
        if (s[3]) {
            known[l] = s[3];
        }
        if (s[0] !== '') {
            return short[s[0][1]] = "--" + l;
        }
    });
    FEATURES.map(function(f) {
        return known[f[0]] = Boolean;
    });
    o = opts = nopt(known, short);
    o.compile || (o.compile = !!o.output);
    o["arguments"] = o.argv.remain;
    o.run = !(o.compile || o.js || o.map || o.tokens || o.parse);
    o.js = !!(o.js || o["eval"] || o.stdio && o.compile);
    o.feature = {};
    FEATURES.map(function(f) {
        var ref1;
        o.feature[f[0]] = (ref1 = o[f[0]]) != null ? ref1 : true;
        return delete o[f[0]];
    });
    if (o.Debug) {
        delete o.argv;
        return log(helpers.stringify(o));
    }
};

run = function() {
    var eval, i, j, len, len1, literals, ref1, ref2, results, source;
    parseOptions();
    if (opts.features) {
        return features();
    }
    if (opts.help) {
        return usage();
    }
    if (opts.version) {
        return version();
    }
    if (opts.interactive) {
        return startRepl();
    }
    if (opts.stdio) {
        return compileStdio();
    }
    if (opts["eval"]) {
        ref1 = opts["eval"];
        for (i = 0, len = ref1.length; i < len; i++) {
            eval = ref1[i];
            compileScript(eval);
        }
        return;
    }
    if (!opts["arguments"].length) {
        return startRepl();
    }
    literals = opts.run ? opts["arguments"].splice(1) : [];
    process.argv = process.argv.slice(0, 2).concat(literals);
    process.argv[0] = 'koffee';
    if (opts.output) {
        opts.output = path.resolve(opts.output);
    }
    ref2 = opts["arguments"];
    results = [];
    for (j = 0, len1 = ref2.length; j < len1; j++) {
        source = ref2[j];
        source = path.resolve(source);
        if (opts.watch) {
            results.push(watchPath(source));
        } else {
            results.push(compilePath(source, true));
        }
    }
    return results;
};

exports.run = run;

startRepl = function() {
    var replCliOpts;
    replCliOpts = {
        useGlobal: true
    };
    if (opts.require) {
        opts.prelude = makePrelude(opts.require);
    }
    replCliOpts.prelude = opts.prelude;
    return require('./repl').start(replCliOpts);
};

makePrelude = function(requires) {
    return requires.map(function(module) {
        var _, match, name;
        if (match = module.match(/^(.*)=(.*)$/)) {
            _ = match[0], name = match[1], module = match[2];
        }
        name || (name = helpers.baseFileName(module, true, useWinPathSep));
        return name + " = require('" + module + "')";
    }).join(';');
};

compilePath = function(source, topLevel) {
    var code, err, file, files, i, len, ref1, results, stats;
    if (topLevel == null) {
        topLevel = false;
    }
    if (!topLevel && hidden(source)) {
        return;
    }
    try {
        stats = fs.statSync(source);
    } catch (error1) {
        err = error1;
        if (err.code === 'ENOENT') {
            error("Command.compilePath can't stat '" + source + "'");
            process.exit(1);
        }
        throw err;
    }
    if (stats.isDirectory()) {
        if ((ref1 = path.basename(source)) === 'node_modules' || ref1 === '.git') {
            return;
        }
        if (opts.run) {
            compilePath(findDirectoryIndex(source), topLevel);
            return;
        }
        if (opts.Debug) {
            log('Command.compilePath dir:', source);
        }
        try {
            files = fs.readdirSync(source);
        } catch (error1) {
            err = error1;
            if (err.code === 'ENOENT') {
                return;
            }
            throw err;
        }
        results = [];
        for (i = 0, len = files.length; i < len; i++) {
            file = files[i];
            results.push(compilePath(path.join(source, file)));
        }
        return results;
    } else if (topLevel || helpers.isCoffee(source)) {
        try {
            code = fs.readFileSync(source);
        } catch (error1) {
            err = error1;
            if (err.code === 'ENOENT') {
                return;
            }
            throw err;
        }
        if (opts.Debug) {
            log('Command.compilePath file:', source);
        }
        return compileScript(code.toString(), source);
    }
};

findDirectoryIndex = function(source) {
    var err, ext, i, index, len, ref1;
    ref1 = Koffee.FILE_EXTENSIONS;
    for (i = 0, len = ref1.length; i < len; i++) {
        ext = ref1[i];
        index = path.join(source, "index" + ext);
        try {
            if ((fs.statSync(index)).isFile()) {
                return index;
            }
        } catch (error1) {
            err = error1;
            if (err.code !== 'ENOENT') {
                throw err;
            }
        }
    }
    error("Missing index.coffee in " + source);
    return process.exit(1);
};

compileScript = function(input, file) {
    var base, compiled, err, message, o, options, t, task;
    if (file == null) {
        file = null;
    }
    o = opts;
    options = compileOptions(file);
    try {
        t = task = {
            file: file,
            input: input,
            options: options
        };
        Koffee.emit('compile', task);
        if (o.tokens) {
            return printTokens(Koffee.tokens(t.input, t.options));
        } else if (o.nodes) {
            return printLine(Koffee.nodes(t.input, t.options).toString().trim());
        } else if (o.run) {
            Koffee.register();
            if (opts.prelude) {
                Koffee["eval"](opts.prelude, t.options);
            }
            if ((base = t.options).filename == null) {
                base.filename = options.source;
            }
            if (opts.noop) {
                return log("noop run " + file);
            } else {
                return Koffee.run(t.input, t.options);
            }
        } else {
            compiled = Koffee.compile(t.input, t.options);
            t.output = compiled;
            if (o.map) {
                t.output = compiled.js;
                t.sourceMap = compiled.v3SourceMap;
            }
            Koffee.emit('success', task);
            if (o.js) {
                if (opts.noop) {
                    return log("noop js " + file);
                } else {
                    return printLine(t.output.trim());
                }
            } else if (o.compile || o.map) {
                if (opts.noop) {
                    return log("noop write " + options.jsPath);
                } else {
                    return writeJs(t.file, t.output, options.jsPath, t.sourceMap);
                }
            }
        }
    } catch (error1) {
        err = error1;
        Koffee.emit('failure', err, task);
        if (Koffee.listeners('failure').length) {
            return;
        }
        message = (err != null ? err.stack : void 0) || ("" + err);
        if (o.watch) {
            return printLine(message + '\x07');
        } else {
            printWarn(message);
            return process.exit(1);
        }
    }
};

compileOptions = function(source) {
    var copts, cwd, jsDir, jsPath;
    copts = {
        source: source,
        sourceMap: opts.map,
        inlineMap: opts['inline-map'],
        feature: opts.feature,
        bare: opts.bare,
        Debug: opts.Debug
    };
    if (source) {
        cwd = process.cwd();
        jsPath = outputPath(source, '.js');
        jsDir = path.dirname(jsPath);
        copts = helpers.merge(copts, {
            jsPath: jsPath,
            sourceRoot: path.relative(jsDir, cwd),
            sourceFiles: [path.relative(cwd, source)],
            generatedFile: helpers.baseFileName(jsPath, false, useWinPathSep)
        });
    }
    return copts;
};

compileStdio = function() {
    var buffers, stdin;
    buffers = [];
    stdin = process.openStdin();
    stdin.on('data', function(buffer) {
        if (buffer) {
            return buffers.push(buffer);
        }
    });
    return stdin.on('end', function() {
        return compileScript(Buffer.concat(buffers).toString());
    });
};

watchPath = function(source) {
    var err, stats;
    try {
        stats = fs.statSync(source);
    } catch (error1) {
        err = error1;
        if (err.code === 'ENOENT') {
            return;
        }
        return error("Command.watchPath can't stat '" + source + "'", err);
    }
    if (stats.isDirectory()) {
        return watchDir(source);
    } else {
        return watchFile(source);
    }
};

watchFile = function(source) {
    var compileTimeout, err, prevStats, startWatcher, watcher;
    if (!helpers.isCoffee(source)) {
        return;
    }
    if (opts.Debug) {
        log('Command.watchFile', source);
    }
    watcher = null;
    prevStats = null;
    compileTimeout = null;
    startWatcher = function() {
        return watcher = fs.watch(source).on('change', function(change) {
            if (change !== 'change') {
                return;
            }
            if (opts.Debug) {
                log('Command.watchFile', change, source);
            }
            clearTimeout(compileTimeout);
            return compileTimeout = wait(25, function() {
                return fs.stat(source, function(err, stats) {
                    if ((err != null ? err.code : void 0) === 'ENOENT') {
                        return watcher.close();
                    }
                    if (err) {
                        return error(err);
                    }
                    if (prevStats && stats.mtime.getTime() === prevStats.mtime.getTime() && stats.size === prevStats.size) {
                        return;
                    }
                    prevStats = stats;
                    return fs.readFile(source, function(err, code) {
                        if (err) {
                            return error(err);
                        }
                        if (opts.Debug) {
                            log('Command.watchFile compile', source);
                        }
                        return compileScript(code.toString(), source);
                    });
                });
            });
        }).on('error', function(err) {
            if (err.code !== 'EPERM') {
                throw err;
            }
        });
    };
    try {
        return startWatcher();
    } catch (error1) {
        err = error1;
        return error(err);
    }
};

watchDir = function(source) {
    var err, startWatcher, watcher;
    if (opts.Debug) {
        log('Command.watchDir', source);
    }
    watcher = null;
    startWatcher = function() {
        var err, file, files, i, len;
        try {
            files = fs.readdirSync(source);
        } catch (error1) {
            err = error1;
            if ((err != null ? err.code : void 0) === 'ENOENT') {
                return;
            }
            throw err;
        }
        for (i = 0, len = files.length; i < len; i++) {
            file = files[i];
            if (file[0] === '.') {
                continue;
            }
            if (file === 'node_modules') {
                continue;
            }
            watchPath(path.join(source, file));
        }
        return watcher = fs.watch(source).on('error', function(err) {
            if (err.code !== 'EPERM') {
                throw err;
            }
            return watcher.close();
        }).on('change', function(change, p) {
            if (change === 'rename') {
                if (opts.Debug) {
                    log('Command.watchDir', change, path.join(source, p));
                }
                return watchPath(path.join(source, p));
            }
        });
    };
    try {
        return startWatcher();
    } catch (error1) {
        err = error1;
        if (err.code === 'ENOENT') {
            return;
        }
        throw err;
    }
};

outputPath = function(source, extension) {
    var basename, dir;
    basename = helpers.baseFileName(source, true, useWinPathSep);
    if (opts.output) {
        dir = opts.output;
    } else {
        dir = path.dirname(source);
    }
    return path.join(dir, basename + extension);
};

mkdirp = function(dir, fn) {
    var mkdirs, mode;
    mode = 0x1ff & ~process.umask();
    return (mkdirs = function(p, fn) {
        return fs.exists(p, function(exists) {
            if (exists) {
                return fn();
            } else {
                return mkdirs(path.dirname(p), function() {
                    return fs.mkdir(p, mode, function(err) {
                        if (err) {
                            return fn(err);
                        }
                        return fn();
                    });
                });
            }
        });
    })(dir, fn);
};

writeJs = function(source, js, jsPath, generatedSourceMap) {
    var compile, jsDir, sourceMapPath;
    if (generatedSourceMap == null) {
        generatedSourceMap = null;
    }
    sourceMapPath = outputPath(source, '.js.map');
    jsDir = path.dirname(jsPath);
    compile = function() {
        if (opts.compile) {
            if (js.length <= 0) {
                js = ' ';
            }
            if (generatedSourceMap) {
                js = js + "\n//# sourceMappingURL=" + (helpers.baseFileName(sourceMapPath, false, useWinPathSep)) + "\n";
            }
            fs.writeFile(jsPath, js, function(err) {
                if (err) {
                    printLine(err.message);
                    return process.exit(1);
                } else if (opts.compile && opts.watch) {
                    return timeLog("compiled " + source);
                }
            });
        }
        if (generatedSourceMap) {
            return fs.writeFile(sourceMapPath, generatedSourceMap, function(err) {
                if (err) {
                    printLine("Could not write source map: " + err.message);
                    return process.exit(1);
                }
            });
        }
    };
    return fs.exists(jsDir, function(itExists) {
        if (itExists) {
            return compile();
        } else {
            return mkdirp(jsDir, compile);
        }
    });
};

wait = function(milliseconds, func) {
    return setTimeout(func, milliseconds);
};

timeLog = function(message) {
    return log(((new Date).toLocaleTimeString()) + " - " + message);
};

printTokens = function(tokens) {
    var i, index, ref1, results, tag, token, value;
    results = [];
    for (index = i = 0, ref1 = tokens.length; 0 <= ref1 ? i < ref1 : i > ref1; index = 0 <= ref1 ? ++i : --i) {
        token = tokens[index];
        tag = token[0];
        value = token[1].toString().replace(/\n/, '\\n');
        if (tag === 'TERMINATOR') {
            results.push(print('\n\n'));
        } else if (tag === 'INDENT') {
            results.push(print('IND '));
        } else if (tag === 'OUTDENT') {
            results.push(print('OUT '));
        } else if (tag === 'CLASS' || tag === 'PARAM_START' || tag === 'PARAM_END' || tag === 'NULL') {
            results.push(print(index + " " + tag + " "));
        } else if (tag === value) {
            results.push(print(index + " " + tag + " "));
        } else {
            results.push(print(index + " " + tag + "=" + value + " "));
        }
    }
    return results;
};

version = function() {
    return printLine("" + Koffee.VERSION);
};

usage = function() {
    var lines, rules;
    lines = [BANNER + "\n"];
    rules = SWITCHES.map(function(rule) {
        var description, letter, long, longFlag, match, option, short;
        if (rule.length < 3) {
            rule.unshift(null);
        }
        short = rule[0], long = rule[1], description = rule[2];
        match = long.match(/\[(\w+(\*?))\]/);
        longFlag = long.match(/^(--\w[\w\-]*)/)[1];
        letter = short ? short + ', ' : '    ';
        option = helpers.pad(letter + long);
        return lines.push('    ' + option + description);
    });
    return log("\n" + (lines.join('\n')) + "\n");
};

features = function() {
    var f;
    f = function(f) {
        return "    " + (helpers.pad(f[0])) + f[1];
    };
    return log("\nFeatures:\n\n" + (FEATURES.map(f).join('\n')) + "\n");
};

//# sourceMappingURL=data:application/json;base64,eyJ2ZXJzaW9uIjozLCJmaWxlIjoiY29tbWFuZC5qcyIsInNvdXJjZVJvb3QiOiIuIiwic291cmNlcyI6WyIiXSwibmFtZXMiOltdLCJtYXBwaW5ncyI6IjtBQUFBOzs7Ozs7O0FBQUEsSUFBQTs7QUFpQkEsRUFBQSxHQUFpQixPQUFBLENBQVEsSUFBUjs7QUFDakIsSUFBQSxHQUFpQixPQUFBLENBQVEsTUFBUjs7QUFDakIsSUFBQSxHQUFpQixPQUFBLENBQVEsTUFBUjs7QUFDakIsT0FBQSxHQUFpQixPQUFBLENBQVEsV0FBUjs7QUFDakIsTUFBQSxHQUFpQixPQUFBLENBQVEsVUFBUjs7QUFDakIsTUFBaUIsT0FBQSxDQUFRLGVBQVIsQ0FBakIsRUFBQyxpQkFBRCxFQUFROztBQUNQLGVBQWdCLE9BQUEsQ0FBUSxRQUFSOztBQUVqQixhQUFBLEdBQWlCLElBQUksQ0FBQyxHQUFMLEtBQVk7O0FBRTdCLE9BQU8sQ0FBQyxNQUFSLENBQWUsTUFBZixFQUF1QixJQUFJLFlBQTNCOztBQUVBLEdBQUEsR0FBWSxPQUFPLENBQUM7O0FBQ3BCLEtBQUEsR0FBWSxPQUFPLENBQUM7O0FBQ3BCLEtBQUEsR0FBWSxTQUFDLElBQUQ7V0FBVSxPQUFPLENBQUMsTUFBTSxDQUFDLEtBQWYsQ0FBcUIsSUFBckI7QUFBVjs7QUFDWixTQUFBLEdBQVksU0FBQyxJQUFEO1dBQVUsT0FBTyxDQUFDLE1BQU0sQ0FBQyxLQUFmLENBQXFCLElBQUEsR0FBTyxJQUE1QjtBQUFWOztBQUNaLFNBQUEsR0FBWSxTQUFDLElBQUQ7V0FBVSxPQUFPLENBQUMsTUFBTSxDQUFDLEtBQWYsQ0FBcUIsSUFBQSxHQUFPLElBQTVCO0FBQVY7O0FBQ1osTUFBQSxHQUFZLFNBQUMsSUFBRDtXQUFVLFFBQVEsQ0FBQyxJQUFULENBQWMsSUFBZDtBQUFWOztBQUVaLE1BQUEsR0FBUzs7QUFFVCxRQUFBLEdBQVcsQ0FDUCxDQUFDLFFBQUQsRUFBOEIsbUNBQTlCLENBRE8sRUFFUCxDQUFDLFNBQUQsRUFBOEIsZ0JBQTlCLENBRk8sRUFHUCxDQUFDLG1CQUFELEVBQThCLDBCQUE5QixDQUhPLEVBSVAsQ0FBQyxzQkFBRCxFQUE4Qiw4QkFBOUIsQ0FKTyxFQUtQLENBQUMsZ0JBQUQsRUFBOEIsOEJBQTlCLENBTE87O0FBUVgsUUFBQSxHQUFXLENBQ1AsQ0FBQyxJQUFELEVBQU8sUUFBUCxFQUE4Qiw4Q0FBOUIsRUFBdUYsT0FBdkYsQ0FETyxFQUVQLENBQUMsSUFBRCxFQUFPLFdBQVAsRUFBOEIsNkNBQTlCLEVBQXVGLE9BQXZGLENBRk8sRUFHUCxDQUFDLElBQUQsRUFBTyxpQkFBUCxFQUE4Qiw4Q0FBOUIsRUFBc0YsQ0FBQyxNQUFELEVBQVMsS0FBVCxDQUF0RixDQUhPLEVBSVAsQ0FBQyxJQUFELEVBQU8sWUFBUCxFQUE4Qix5QkFBOUIsRUFBdUYsT0FBdkYsQ0FKTyxFQUtQLENBQUMsRUFBRCxFQUFPLGdCQUFQLEVBQThCLDZDQUE5QixFQUF1RixJQUF2RixDQUxPLEVBTVAsQ0FBQyxJQUFELEVBQU8sUUFBUCxFQUE4QiwyQkFBOUIsRUFBdUYsT0FBdkYsQ0FOTyxFQU9QLENBQUMsSUFBRCxFQUFPLE1BQVAsRUFBOEIsbUNBQTlCLEVBQXVGLE9BQXZGLENBUE8sRUFRUCxDQUFDLElBQUQsRUFBTyxPQUFQLEVBQThCLCtDQUE5QixFQUF1RixPQUF2RixDQVJPLEVBU1AsQ0FBQyxJQUFELEVBQU8sY0FBUCxFQUE4Qix1REFBOUIsRUFBdUYsT0FBdkYsQ0FUTyxFQVVQLENBQUMsSUFBRCxFQUFPLFFBQVAsRUFBOEIsc0NBQTlCLEVBQXVGLE9BQXZGLENBVk8sRUFXUCxDQUFDLElBQUQsRUFBTyxnQkFBUCxFQUE4QixrREFBOUIsRUFBdUYsTUFBdkYsQ0FYTyxFQVlQLENBQUMsSUFBRCxFQUFPLFNBQVAsRUFBOEIsbURBQTlCLEVBQXVGLE9BQXZGLENBWk8sRUFhUCxDQUFDLElBQUQsRUFBTyxvQkFBUCxFQUE4Qiw4Q0FBOUIsRUFBc0YsQ0FBQyxNQUFELEVBQVMsS0FBVCxDQUF0RixDQWJPLEVBY1AsQ0FBQyxJQUFELEVBQU8sU0FBUCxFQUE4QiwyQ0FBOUIsRUFBdUYsT0FBdkYsQ0FkTyxFQWVQLENBQUMsSUFBRCxFQUFPLFVBQVAsRUFBOEIsc0RBQTlCLEVBQXVGLE9BQXZGLENBZk8sRUFnQlAsQ0FBQyxJQUFELEVBQU8sV0FBUCxFQUE4Qiw0QkFBOUIsRUFBdUYsT0FBdkYsQ0FoQk8sRUFpQlAsQ0FBQyxJQUFELEVBQU8sU0FBUCxFQUE4Qiw4Q0FBOUIsRUFBdUYsT0FBdkYsQ0FqQk87O0FBb0JYLElBQUEsR0FBTzs7QUFRUCxZQUFBLEdBQWUsU0FBQTtBQUVYLFFBQUE7SUFBQSxPQUFBLEdBQVUsQ0FBRSxNQUFGLEVBQVUsU0FBVixFQUFxQixVQUFyQixFQUFpQyxNQUFqQyxFQUF5QyxZQUF6QyxFQUF1RCxJQUF2RCxFQUE2RCxLQUE3RCxFQUNFLE9BREYsRUFDVyxPQURYLEVBQ29CLFFBRHBCLEVBQzZCLFNBRDdCLEVBQ3dDLE9BRHhDLEVBQ2lELE9BRGpEO0lBR1YsS0FBQSxHQUFRO1FBQUMsS0FBQSxFQUFNLE9BQVA7O0lBQ1IsS0FBQSxHQUFRO1FBQUMsQ0FBQSxFQUFFLFNBQUg7O0lBQ1IsUUFBUSxDQUFDLEdBQVQsQ0FBYSxTQUFDLENBQUQ7QUFBTyxZQUFBO1FBQUEsQ0FBQSxHQUFJLENBQUUsQ0FBQSxDQUFBLENBQUUsQ0FBQyxLQUFMLENBQVcsR0FBWCxDQUFnQixDQUFBLENBQUEsQ0FBRztRQUFNLElBQW1CLENBQUUsQ0FBQSxDQUFBLENBQXJCO1lBQUEsS0FBTSxDQUFBLENBQUEsQ0FBTixHQUFXLENBQUUsQ0FBQSxDQUFBLEVBQWI7O1FBQXlCLElBQTZCLENBQUUsQ0FBQSxDQUFBLENBQUYsS0FBTSxFQUFuQzttQkFBQSxLQUFNLENBQUEsQ0FBRSxDQUFBLENBQUEsQ0FBRyxDQUFBLENBQUEsQ0FBTCxDQUFOLEdBQWlCLElBQUEsR0FBSyxFQUF0Qjs7SUFBN0QsQ0FBYjtJQUNBLFFBQVEsQ0FBQyxHQUFULENBQWEsU0FBQyxDQUFEO2VBQU8sS0FBTSxDQUFBLENBQUUsQ0FBQSxDQUFBLENBQUYsQ0FBTixHQUFjO0lBQXJCLENBQWI7SUFFQSxDQUFBLEdBQUksSUFBQSxHQUFPLElBQUEsQ0FBSyxLQUFMLEVBQVksS0FBWjtJQUlYLENBQUMsQ0FBQyxZQUFGLENBQUMsQ0FBQyxVQUFhLENBQUMsQ0FBQyxDQUFDLENBQUM7SUFDbkIsQ0FBQyxFQUFDLFNBQUQsRUFBRCxHQUFlLENBQUMsQ0FBQyxJQUFJLENBQUM7SUFDdEIsQ0FBQyxDQUFDLEdBQUYsR0FBZSxDQUFJLENBQUMsQ0FBQyxDQUFDLE9BQUYsSUFBYSxDQUFDLENBQUMsRUFBZixJQUFxQixDQUFDLENBQUMsR0FBdkIsSUFBOEIsQ0FBQyxDQUFDLE1BQWhDLElBQTBDLENBQUMsQ0FBQyxLQUE3QztJQUNuQixDQUFDLENBQUMsRUFBRixHQUFlLENBQUMsQ0FBQyxDQUFDLENBQUMsQ0FBQyxFQUFGLElBQVEsQ0FBQyxFQUFDLElBQUQsRUFBVCxJQUFrQixDQUFDLENBQUMsS0FBRixJQUFZLENBQUMsQ0FBQyxPQUFqQztJQUVqQixDQUFDLENBQUMsT0FBRixHQUFZO0lBQ1osUUFBUSxDQUFDLEdBQVQsQ0FBYSxTQUFDLENBQUQ7QUFBTyxZQUFBO1FBQUEsQ0FBQyxDQUFDLE9BQVEsQ0FBQSxDQUFFLENBQUEsQ0FBQSxDQUFGLENBQVYscUNBQTRCO2VBQU0sT0FBTyxDQUFFLENBQUEsQ0FBRSxDQUFBLENBQUEsQ0FBRjtJQUFsRCxDQUFiO0lBRUEsSUFBRyxDQUFDLENBQUMsS0FBTDtRQUNJLE9BQU8sQ0FBQyxDQUFDO2VBQ1QsR0FBQSxDQUFJLE9BQU8sQ0FBQyxTQUFSLENBQWtCLENBQWxCLENBQUosRUFGSjs7QUF0Qlc7O0FBb0NmLEdBQUEsR0FBTSxTQUFBO0FBRUYsUUFBQTtJQUFBLFlBQUEsQ0FBQTtJQUVBLElBQXlCLElBQUksQ0FBQyxRQUE5QjtBQUFBLGVBQU8sUUFBQSxDQUFBLEVBQVA7O0lBQ0EsSUFBeUIsSUFBSSxDQUFDLElBQTlCO0FBQUEsZUFBTyxLQUFBLENBQUEsRUFBUDs7SUFDQSxJQUF5QixJQUFJLENBQUMsT0FBOUI7QUFBQSxlQUFPLE9BQUEsQ0FBQSxFQUFQOztJQUNBLElBQXlCLElBQUksQ0FBQyxXQUE5QjtBQUFBLGVBQU8sU0FBQSxDQUFBLEVBQVA7O0lBQ0EsSUFBeUIsSUFBSSxDQUFDLEtBQTlCO0FBQUEsZUFBTyxZQUFBLENBQUEsRUFBUDs7SUFDQSxJQUFHLElBQUksRUFBQyxJQUFELEVBQVA7QUFDSTtBQUFBLGFBQUEsc0NBQUE7O1lBQ0ksYUFBQSxDQUFjLElBQWQ7QUFESjtBQUVBLGVBSEo7O0lBSUEsSUFBeUIsQ0FBSSxJQUFJLEVBQUMsU0FBRCxFQUFVLENBQUMsTUFBNUM7QUFBQSxlQUFPLFNBQUEsQ0FBQSxFQUFQOztJQUVBLFFBQUEsR0FBYyxJQUFJLENBQUMsR0FBUixHQUFpQixJQUFJLEVBQUMsU0FBRCxFQUFVLENBQUMsTUFBZixDQUFzQixDQUF0QixDQUFqQixHQUE4QztJQUV6RCxPQUFPLENBQUMsSUFBUixHQUFlLE9BQU8sQ0FBQyxJQUFLLFlBQUssQ0FBQyxNQUFuQixDQUEwQixRQUExQjtJQUNmLE9BQU8sQ0FBQyxJQUFLLENBQUEsQ0FBQSxDQUFiLEdBQWtCO0lBRWxCLElBQTBDLElBQUksQ0FBQyxNQUEvQztRQUFBLElBQUksQ0FBQyxNQUFMLEdBQWMsSUFBSSxDQUFDLE9BQUwsQ0FBYSxJQUFJLENBQUMsTUFBbEIsRUFBZDs7QUFDQTtBQUFBO1NBQUEsd0NBQUE7O1FBQ0ksTUFBQSxHQUFTLElBQUksQ0FBQyxPQUFMLENBQWEsTUFBYjtRQUVULElBQUcsSUFBSSxDQUFDLEtBQVI7eUJBQ0ksU0FBQSxDQUFVLE1BQVYsR0FESjtTQUFBLE1BQUE7eUJBR0ksV0FBQSxDQUFZLE1BQVosRUFBb0IsSUFBcEIsR0FISjs7QUFISjs7QUFyQkU7O0FBNkJOLE9BQU8sQ0FBQyxHQUFSLEdBQWM7O0FBRWQsU0FBQSxHQUFZLFNBQUE7QUFNUixRQUFBO0lBQUEsV0FBQSxHQUFjO1FBQUEsU0FBQSxFQUFXLElBQVg7O0lBQ2QsSUFBMkMsSUFBSSxDQUFDLE9BQWhEO1FBQUEsSUFBSSxDQUFDLE9BQUwsR0FBZSxXQUFBLENBQVksSUFBSSxDQUFDLE9BQWpCLEVBQWY7O0lBQ0EsV0FBVyxDQUFDLE9BQVosR0FBc0IsSUFBSSxDQUFDO1dBQzNCLE9BQUEsQ0FBUSxRQUFSLENBQWlCLENBQUMsS0FBbEIsQ0FBd0IsV0FBeEI7QUFUUTs7QUFXWixXQUFBLEdBQWMsU0FBQyxRQUFEO1dBRVYsUUFBUSxDQUFDLEdBQVQsQ0FBYSxTQUFDLE1BQUQ7QUFDVCxZQUFBO1FBQUEsSUFBNkIsS0FBQSxHQUFRLE1BQU0sQ0FBQyxLQUFQLENBQWEsYUFBYixDQUFyQztZQUFDLFlBQUQsRUFBSSxlQUFKLEVBQVUsa0JBQVY7O1FBQ0EsU0FBQSxPQUFTLE9BQU8sQ0FBQyxZQUFSLENBQXFCLE1BQXJCLEVBQTZCLElBQTdCLEVBQWtDLGFBQWxDO2VBQ04sSUFBRCxHQUFNLGNBQU4sR0FBb0IsTUFBcEIsR0FBMkI7SUFIcEIsQ0FBYixDQUlBLENBQUMsSUFKRCxDQUlNLEdBSk47QUFGVTs7QUFnQmQsV0FBQSxHQUFjLFNBQUMsTUFBRCxFQUFTLFFBQVQ7QUFFVixRQUFBOztRQUZtQixXQUFXOztJQUU5QixJQUFVLENBQUksUUFBSixJQUFpQixNQUFBLENBQU8sTUFBUCxDQUEzQjtBQUFBLGVBQUE7O0FBRUE7UUFDSSxLQUFBLEdBQVEsRUFBRSxDQUFDLFFBQUgsQ0FBWSxNQUFaLEVBRFo7S0FBQSxjQUFBO1FBRU07UUFDRixJQUFHLEdBQUcsQ0FBQyxJQUFKLEtBQVksUUFBZjtZQUNJLEtBQUEsQ0FBTSxrQ0FBQSxHQUFtQyxNQUFuQyxHQUEwQyxHQUFoRDtZQUNBLE9BQU8sQ0FBQyxJQUFSLENBQWEsQ0FBYixFQUZKOztBQUdBLGNBQU0sSUFOVjs7SUFRQSxJQUFHLEtBQUssQ0FBQyxXQUFOLENBQUEsQ0FBSDtRQUVJLFlBQUcsSUFBSSxDQUFDLFFBQUwsQ0FBYyxNQUFkLEVBQUEsS0FBMEIsY0FBMUIsSUFBQSxJQUFBLEtBQTBDLE1BQTdDO0FBQ0ksbUJBREo7O1FBR0EsSUFBRyxJQUFJLENBQUMsR0FBUjtZQUNJLFdBQUEsQ0FBWSxrQkFBQSxDQUFtQixNQUFuQixDQUFaLEVBQXdDLFFBQXhDO0FBQ0EsbUJBRko7O1FBSUEsSUFBMEMsSUFBSSxDQUFDLEtBQS9DO1lBQUEsR0FBQSxDQUFJLDBCQUFKLEVBQWdDLE1BQWhDLEVBQUE7O0FBRUE7WUFDSSxLQUFBLEdBQVEsRUFBRSxDQUFDLFdBQUgsQ0FBZSxNQUFmLEVBRFo7U0FBQSxjQUFBO1lBRU07WUFDRixJQUFHLEdBQUcsQ0FBQyxJQUFKLEtBQVksUUFBZjtBQUE2Qix1QkFBN0I7O0FBQ0Esa0JBQU0sSUFKVjs7QUFNQTthQUFBLHVDQUFBOzt5QkFDSSxXQUFBLENBQVksSUFBSSxDQUFDLElBQUwsQ0FBVSxNQUFWLEVBQWtCLElBQWxCLENBQVo7QUFESjt1QkFqQko7S0FBQSxNQW9CSyxJQUFHLFFBQUEsSUFBWSxPQUFPLENBQUMsUUFBUixDQUFpQixNQUFqQixDQUFmO0FBRUQ7WUFDSSxJQUFBLEdBQU8sRUFBRSxDQUFDLFlBQUgsQ0FBZ0IsTUFBaEIsRUFEWDtTQUFBLGNBQUE7WUFFTTtZQUNGLElBQUcsR0FBRyxDQUFDLElBQUosS0FBWSxRQUFmO0FBQTZCLHVCQUE3Qjs7QUFDQSxrQkFBTSxJQUpWOztRQU1BLElBQTJDLElBQUksQ0FBQyxLQUFoRDtZQUFBLEdBQUEsQ0FBSSwyQkFBSixFQUFpQyxNQUFqQyxFQUFBOztlQUVBLGFBQUEsQ0FBYyxJQUFJLENBQUMsUUFBTCxDQUFBLENBQWQsRUFBK0IsTUFBL0IsRUFWQzs7QUFoQ0s7O0FBNENkLGtCQUFBLEdBQXFCLFNBQUMsTUFBRDtBQUVqQixRQUFBO0FBQUE7QUFBQSxTQUFBLHNDQUFBOztRQUNJLEtBQUEsR0FBUSxJQUFJLENBQUMsSUFBTCxDQUFVLE1BQVYsRUFBa0IsT0FBQSxHQUFRLEdBQTFCO0FBQ1I7WUFDSSxJQUFnQixDQUFDLEVBQUUsQ0FBQyxRQUFILENBQVksS0FBWixDQUFELENBQW1CLENBQUMsTUFBcEIsQ0FBQSxDQUFoQjtBQUFBLHVCQUFPLE1BQVA7YUFESjtTQUFBLGNBQUE7WUFFTTtZQUNGLElBQWlCLEdBQUcsQ0FBQyxJQUFKLEtBQVksUUFBN0I7QUFBQSxzQkFBTSxJQUFOO2FBSEo7O0FBRko7SUFNQSxLQUFBLENBQU0sMEJBQUEsR0FBMkIsTUFBakM7V0FDQSxPQUFPLENBQUMsSUFBUixDQUFhLENBQWI7QUFUaUI7O0FBb0JyQixhQUFBLEdBQWdCLFNBQUMsS0FBRCxFQUFRLElBQVI7QUFFWixRQUFBOztRQUZvQixPQUFPOztJQUUzQixDQUFBLEdBQUk7SUFDSixPQUFBLEdBQVUsY0FBQSxDQUFlLElBQWY7QUFFVjtRQUNJLENBQUEsR0FBSSxJQUFBLEdBQU87WUFBQyxNQUFBLElBQUQ7WUFBTyxPQUFBLEtBQVA7WUFBYyxTQUFBLE9BQWQ7O1FBQ1gsTUFBTSxDQUFDLElBQVAsQ0FBWSxTQUFaLEVBQXVCLElBQXZCO1FBQ0EsSUFBRyxDQUFDLENBQUMsTUFBTDttQkFDSSxXQUFBLENBQVksTUFBTSxDQUFDLE1BQVAsQ0FBYyxDQUFDLENBQUMsS0FBaEIsRUFBdUIsQ0FBQyxDQUFDLE9BQXpCLENBQVosRUFESjtTQUFBLE1BRUssSUFBRyxDQUFDLENBQUMsS0FBTDttQkFDRCxTQUFBLENBQVUsTUFBTSxDQUFDLEtBQVAsQ0FBYSxDQUFDLENBQUMsS0FBZixFQUFzQixDQUFDLENBQUMsT0FBeEIsQ0FBZ0MsQ0FBQyxRQUFqQyxDQUFBLENBQTJDLENBQUMsSUFBNUMsQ0FBQSxDQUFWLEVBREM7U0FBQSxNQUVBLElBQUcsQ0FBQyxDQUFDLEdBQUw7WUFDRCxNQUFNLENBQUMsUUFBUCxDQUFBO1lBQ0EsSUFBdUMsSUFBSSxDQUFDLE9BQTVDO2dCQUFBLE1BQU0sRUFBQyxJQUFELEVBQU4sQ0FBWSxJQUFJLENBQUMsT0FBakIsRUFBMEIsQ0FBQyxDQUFDLE9BQTVCLEVBQUE7OztvQkFFUyxDQUFDLFdBQVksT0FBTyxDQUFDOztZQUc5QixJQUFHLElBQUksQ0FBQyxJQUFSO3VCQUFrQixHQUFBLENBQUksV0FBQSxHQUFZLElBQWhCLEVBQWxCO2FBQUEsTUFBQTt1QkFFSSxNQUFNLENBQUMsR0FBUCxDQUFXLENBQUMsQ0FBQyxLQUFiLEVBQW9CLENBQUMsQ0FBQyxPQUF0QixFQUZKO2FBUEM7U0FBQSxNQUFBO1lBV0QsUUFBQSxHQUFXLE1BQU0sQ0FBQyxPQUFQLENBQWUsQ0FBQyxDQUFDLEtBQWpCLEVBQXdCLENBQUMsQ0FBQyxPQUExQjtZQUNYLENBQUMsQ0FBQyxNQUFGLEdBQVc7WUFDWCxJQUFHLENBQUMsQ0FBQyxHQUFMO2dCQUNJLENBQUMsQ0FBQyxNQUFGLEdBQVcsUUFBUSxDQUFDO2dCQUNwQixDQUFDLENBQUMsU0FBRixHQUFjLFFBQVEsQ0FBQyxZQUYzQjs7WUFJQSxNQUFNLENBQUMsSUFBUCxDQUFZLFNBQVosRUFBdUIsSUFBdkI7WUFFQSxJQUFHLENBQUMsQ0FBQyxFQUFMO2dCQUNJLElBQUcsSUFBSSxDQUFDLElBQVI7MkJBQWtCLEdBQUEsQ0FBSSxVQUFBLEdBQVcsSUFBZixFQUFsQjtpQkFBQSxNQUFBOzJCQUVJLFNBQUEsQ0FBVSxDQUFDLENBQUMsTUFBTSxDQUFDLElBQVQsQ0FBQSxDQUFWLEVBRko7aUJBREo7YUFBQSxNQUlLLElBQUcsQ0FBQyxDQUFDLE9BQUYsSUFBYSxDQUFDLENBQUMsR0FBbEI7Z0JBQ0QsSUFBRyxJQUFJLENBQUMsSUFBUjsyQkFBa0IsR0FBQSxDQUFJLGFBQUEsR0FBYyxPQUFPLENBQUMsTUFBMUIsRUFBbEI7aUJBQUEsTUFBQTsyQkFFSSxPQUFBLENBQVEsQ0FBQyxDQUFDLElBQVYsRUFBZ0IsQ0FBQyxDQUFDLE1BQWxCLEVBQTBCLE9BQU8sQ0FBQyxNQUFsQyxFQUEwQyxDQUFDLENBQUMsU0FBNUMsRUFGSjtpQkFEQzthQXZCSjtTQVBUO0tBQUEsY0FBQTtRQWtDTTtRQUVGLE1BQU0sQ0FBQyxJQUFQLENBQVksU0FBWixFQUF1QixHQUF2QixFQUE0QixJQUE1QjtRQUNBLElBQVUsTUFBTSxDQUFDLFNBQVAsQ0FBaUIsU0FBakIsQ0FBMkIsQ0FBQyxNQUF0QztBQUFBLG1CQUFBOztRQUNBLE9BQUEsa0JBQVUsR0FBRyxDQUFFLGVBQUwsSUFBYyxDQUFBLEVBQUEsR0FBRyxHQUFIO1FBQ3hCLElBQUcsQ0FBQyxDQUFDLEtBQUw7bUJBQ0ksU0FBQSxDQUFVLE9BQUEsR0FBVSxNQUFwQixFQURKO1NBQUEsTUFBQTtZQUdJLFNBQUEsQ0FBVSxPQUFWO21CQUNBLE9BQU8sQ0FBQyxJQUFSLENBQWEsQ0FBYixFQUpKO1NBdkNKOztBQUxZOztBQWtEaEIsY0FBQSxHQUFpQixTQUFDLE1BQUQ7QUFFYixRQUFBO0lBQUEsS0FBQSxHQUNJO1FBQUEsTUFBQSxFQUFXLE1BQVg7UUFDQSxTQUFBLEVBQVcsSUFBSSxDQUFDLEdBRGhCO1FBRUEsU0FBQSxFQUFXLElBQUssQ0FBQSxZQUFBLENBRmhCO1FBR0EsT0FBQSxFQUFXLElBQUksQ0FBQyxPQUhoQjtRQUlBLElBQUEsRUFBVyxJQUFJLENBQUMsSUFKaEI7UUFLQSxLQUFBLEVBQVcsSUFBSSxDQUFDLEtBTGhCOztJQU9KLElBQUcsTUFBSDtRQUVJLEdBQUEsR0FBTSxPQUFPLENBQUMsR0FBUixDQUFBO1FBQ04sTUFBQSxHQUFTLFVBQUEsQ0FBVyxNQUFYLEVBQW1CLEtBQW5CO1FBQ1QsS0FBQSxHQUFRLElBQUksQ0FBQyxPQUFMLENBQWEsTUFBYjtRQUNSLEtBQUEsR0FBUSxPQUFPLENBQUMsS0FBUixDQUFjLEtBQWQsRUFBcUI7WUFDekIsUUFBQSxNQUR5QjtZQUV6QixVQUFBLEVBQVksSUFBSSxDQUFDLFFBQUwsQ0FBYyxLQUFkLEVBQXFCLEdBQXJCLENBRmE7WUFHekIsV0FBQSxFQUFhLENBQUMsSUFBSSxDQUFDLFFBQUwsQ0FBYyxHQUFkLEVBQW1CLE1BQW5CLENBQUQsQ0FIWTtZQUl6QixhQUFBLEVBQWUsT0FBTyxDQUFDLFlBQVIsQ0FBcUIsTUFBckIsRUFBNkIsS0FBN0IsRUFBaUMsYUFBakMsQ0FKVTtTQUFyQixFQUxaOztXQWdCQTtBQTFCYTs7QUE4QmpCLFlBQUEsR0FBZSxTQUFBO0FBRVgsUUFBQTtJQUFBLE9BQUEsR0FBVTtJQUNWLEtBQUEsR0FBUSxPQUFPLENBQUMsU0FBUixDQUFBO0lBQ1IsS0FBSyxDQUFDLEVBQU4sQ0FBUyxNQUFULEVBQWlCLFNBQUMsTUFBRDtRQUNiLElBQXVCLE1BQXZCO21CQUFBLE9BQU8sQ0FBQyxJQUFSLENBQWEsTUFBYixFQUFBOztJQURhLENBQWpCO1dBRUEsS0FBSyxDQUFDLEVBQU4sQ0FBUyxLQUFULEVBQWdCLFNBQUE7ZUFDWixhQUFBLENBQWMsTUFBTSxDQUFDLE1BQVAsQ0FBYyxPQUFkLENBQXNCLENBQUMsUUFBdkIsQ0FBQSxDQUFkO0lBRFksQ0FBaEI7QUFOVzs7QUFlZixTQUFBLEdBQVksU0FBQyxNQUFEO0FBRVIsUUFBQTtBQUFBO1FBQ0ksS0FBQSxHQUFRLEVBQUUsQ0FBQyxRQUFILENBQVksTUFBWixFQURaO0tBQUEsY0FBQTtRQUVNO1FBQ0YsSUFBVSxHQUFHLENBQUMsSUFBSixLQUFZLFFBQXRCO0FBQUEsbUJBQUE7O0FBQ0EsZUFBTyxLQUFBLENBQU0sZ0NBQUEsR0FBaUMsTUFBakMsR0FBd0MsR0FBOUMsRUFBa0QsR0FBbEQsRUFKWDs7SUFNQSxJQUFHLEtBQUssQ0FBQyxXQUFOLENBQUEsQ0FBSDtlQUNJLFFBQUEsQ0FBUyxNQUFULEVBREo7S0FBQSxNQUFBO2VBR0ksU0FBQSxDQUFVLE1BQVYsRUFISjs7QUFSUTs7QUFnQlosU0FBQSxHQUFZLFNBQUMsTUFBRDtBQUVSLFFBQUE7SUFBQSxJQUFVLENBQUksT0FBTyxDQUFDLFFBQVIsQ0FBaUIsTUFBakIsQ0FBZDtBQUFBLGVBQUE7O0lBRUEsSUFBbUMsSUFBSSxDQUFDLEtBQXhDO1FBQUEsR0FBQSxDQUFJLG1CQUFKLEVBQXlCLE1BQXpCLEVBQUE7O0lBRUEsT0FBQSxHQUFpQjtJQUNqQixTQUFBLEdBQWlCO0lBQ2pCLGNBQUEsR0FBaUI7SUFFakIsWUFBQSxHQUFlLFNBQUE7ZUFFWCxPQUFBLEdBQVUsRUFBRSxDQUFDLEtBQUgsQ0FBUyxNQUFULENBQ1YsQ0FBQyxFQURTLENBQ04sUUFETSxFQUNJLFNBQUMsTUFBRDtZQUVWLElBQVUsTUFBQSxLQUFVLFFBQXBCO0FBQUEsdUJBQUE7O1lBRUEsSUFBMkMsSUFBSSxDQUFDLEtBQWhEO2dCQUFBLEdBQUEsQ0FBSSxtQkFBSixFQUF5QixNQUF6QixFQUFpQyxNQUFqQyxFQUFBOztZQUVBLFlBQUEsQ0FBYSxjQUFiO21CQUNBLGNBQUEsR0FBaUIsSUFBQSxDQUFLLEVBQUwsRUFBUyxTQUFBO3VCQUV0QixFQUFFLENBQUMsSUFBSCxDQUFRLE1BQVIsRUFBZ0IsU0FBQyxHQUFELEVBQU0sS0FBTjtvQkFDWixtQkFBMEIsR0FBRyxDQUFFLGNBQUwsS0FBYSxRQUF2QztBQUFBLCtCQUFPLE9BQU8sQ0FBQyxLQUFSLENBQUEsRUFBUDs7b0JBQ0EsSUFBb0IsR0FBcEI7QUFBQSwrQkFBTyxLQUFBLENBQU0sR0FBTixFQUFQOztvQkFDQSxJQUFVLFNBQUEsSUFBYyxLQUFLLENBQUMsS0FBSyxDQUFDLE9BQVosQ0FBQSxDQUFBLEtBQXlCLFNBQVMsQ0FBQyxLQUFLLENBQUMsT0FBaEIsQ0FBQSxDQUF2QyxJQUFxRSxLQUFLLENBQUMsSUFBTixLQUFjLFNBQVMsQ0FBQyxJQUF2RztBQUFBLCtCQUFBOztvQkFDQSxTQUFBLEdBQVk7MkJBQ1osRUFBRSxDQUFDLFFBQUgsQ0FBWSxNQUFaLEVBQW9CLFNBQUMsR0FBRCxFQUFNLElBQU47d0JBQ2hCLElBQW9CLEdBQXBCO0FBQUEsbUNBQU8sS0FBQSxDQUFNLEdBQU4sRUFBUDs7d0JBQ0EsSUFBMkMsSUFBSSxDQUFDLEtBQWhEOzRCQUFBLEdBQUEsQ0FBSSwyQkFBSixFQUFpQyxNQUFqQyxFQUFBOzsrQkFDQSxhQUFBLENBQWMsSUFBSSxDQUFDLFFBQUwsQ0FBQSxDQUFkLEVBQStCLE1BQS9CO29CQUhnQixDQUFwQjtnQkFMWSxDQUFoQjtZQUZzQixDQUFUO1FBUFAsQ0FESixDQW9CVixDQUFDLEVBcEJTLENBb0JOLE9BcEJNLEVBb0JHLFNBQUMsR0FBRDtZQUNULElBQWlCLEdBQUcsQ0FBQyxJQUFKLEtBQVksT0FBN0I7QUFBQSxzQkFBTSxJQUFOOztRQURTLENBcEJIO0lBRkM7QUF5QmY7ZUFDSSxZQUFBLENBQUEsRUFESjtLQUFBLGNBQUE7UUFFTTtlQUNGLEtBQUEsQ0FBTSxHQUFOLEVBSEo7O0FBbkNROztBQXdDWixRQUFBLEdBQVcsU0FBQyxNQUFEO0FBRVAsUUFBQTtJQUFBLElBQWtDLElBQUksQ0FBQyxLQUF2QztRQUFBLEdBQUEsQ0FBSSxrQkFBSixFQUF3QixNQUF4QixFQUFBOztJQUVBLE9BQUEsR0FBVTtJQUVWLFlBQUEsR0FBZSxTQUFBO0FBRVgsWUFBQTtBQUFBO1lBQ0ksS0FBQSxHQUFRLEVBQUUsQ0FBQyxXQUFILENBQWUsTUFBZixFQURaO1NBQUEsY0FBQTtZQUVNO1lBQ0YsbUJBQVUsR0FBRyxDQUFFLGNBQUwsS0FBYSxRQUF2QjtBQUFBLHVCQUFBOztBQUNBLGtCQUFNLElBSlY7O0FBTUEsYUFBQSx1Q0FBQTs7WUFDSSxJQUFZLElBQUssQ0FBQSxDQUFBLENBQUwsS0FBVyxHQUF2QjtBQUFBLHlCQUFBOztZQUNBLElBQVksSUFBQSxLQUFTLGNBQXJCO0FBQUEseUJBQUE7O1lBQ0EsU0FBQSxDQUFVLElBQUksQ0FBQyxJQUFMLENBQVUsTUFBVixFQUFrQixJQUFsQixDQUFWO0FBSEo7ZUFLQSxPQUFBLEdBQVUsRUFBRSxDQUFDLEtBQUgsQ0FBUyxNQUFULENBQ1YsQ0FBQyxFQURTLENBQ04sT0FETSxFQUNHLFNBQUMsR0FBRDtZQUNULElBQWlCLEdBQUcsQ0FBQyxJQUFKLEtBQVksT0FBN0I7QUFBQSxzQkFBTSxJQUFOOzttQkFDQSxPQUFPLENBQUMsS0FBUixDQUFBO1FBRlMsQ0FESCxDQUlWLENBQUMsRUFKUyxDQUlOLFFBSk0sRUFJSSxTQUFDLE1BQUQsRUFBUyxDQUFUO1lBQ1YsSUFBRyxNQUFBLEtBQVUsUUFBYjtnQkFDSSxJQUF1RCxJQUFJLENBQUMsS0FBNUQ7b0JBQUEsR0FBQSxDQUFJLGtCQUFKLEVBQXdCLE1BQXhCLEVBQWdDLElBQUksQ0FBQyxJQUFMLENBQVUsTUFBVixFQUFrQixDQUFsQixDQUFoQyxFQUFBOzt1QkFDQSxTQUFBLENBQVUsSUFBSSxDQUFDLElBQUwsQ0FBVSxNQUFWLEVBQWtCLENBQWxCLENBQVYsRUFGSjs7UUFEVSxDQUpKO0lBYkM7QUFzQmY7ZUFDSSxZQUFBLENBQUEsRUFESjtLQUFBLGNBQUE7UUFFTTtRQUNGLElBQVUsR0FBRyxDQUFDLElBQUosS0FBWSxRQUF0QjtBQUFBLG1CQUFBOztBQUNBLGNBQU0sSUFKVjs7QUE1Qk87O0FBb0NYLFVBQUEsR0FBYSxTQUFDLE1BQUQsRUFBUyxTQUFUO0FBRVQsUUFBQTtJQUFBLFFBQUEsR0FBVyxPQUFPLENBQUMsWUFBUixDQUFxQixNQUFyQixFQUE2QixJQUE3QixFQUFrQyxhQUFsQztJQUNYLElBQUcsSUFBSSxDQUFDLE1BQVI7UUFDSSxHQUFBLEdBQU0sSUFBSSxDQUFDLE9BRGY7S0FBQSxNQUFBO1FBR0ksR0FBQSxHQUFNLElBQUksQ0FBQyxPQUFMLENBQWEsTUFBYixFQUhWOztXQUlBLElBQUksQ0FBQyxJQUFMLENBQVUsR0FBVixFQUFlLFFBQUEsR0FBVyxTQUExQjtBQVBTOztBQVdiLE1BQUEsR0FBUyxTQUFDLEdBQUQsRUFBTSxFQUFOO0FBQ0wsUUFBQTtJQUFBLElBQUEsR0FBTyxLQUFBLEdBQVEsQ0FBQyxPQUFPLENBQUMsS0FBUixDQUFBO1dBRWIsQ0FBQSxNQUFBLEdBQVMsU0FBQyxDQUFELEVBQVUsRUFBVjtlQUNSLEVBQUUsQ0FBQyxNQUFILENBQVUsQ0FBVixFQUFhLFNBQUMsTUFBRDtZQUNULElBQUcsTUFBSDt1QkFDSSxFQUFBLENBQUEsRUFESjthQUFBLE1BQUE7dUJBR0ksTUFBQSxDQUFPLElBQUksQ0FBQyxPQUFMLENBQWEsQ0FBYixDQUFQLEVBQXdCLFNBQUE7MkJBQ3BCLEVBQUUsQ0FBQyxLQUFILENBQVMsQ0FBVCxFQUFZLElBQVosRUFBa0IsU0FBQyxHQUFEO3dCQUNkLElBQWlCLEdBQWpCO0FBQUEsbUNBQU8sRUFBQSxDQUFHLEdBQUgsRUFBUDs7K0JBQ0EsRUFBQSxDQUFBO29CQUZjLENBQWxCO2dCQURvQixDQUF4QixFQUhKOztRQURTLENBQWI7SUFEUSxDQUFULENBQUgsQ0FBaUIsR0FBakIsRUFBc0IsRUFBdEI7QUFISzs7QUF1QlQsT0FBQSxHQUFVLFNBQUMsTUFBRCxFQUFTLEVBQVQsRUFBYSxNQUFiLEVBQXFCLGtCQUFyQjtBQUVOLFFBQUE7O1FBRjJCLHFCQUFxQjs7SUFFaEQsYUFBQSxHQUFnQixVQUFBLENBQVcsTUFBWCxFQUFtQixTQUFuQjtJQUNoQixLQUFBLEdBQVEsSUFBSSxDQUFDLE9BQUwsQ0FBYSxNQUFiO0lBQ1IsT0FBQSxHQUFVLFNBQUE7UUFDTixJQUFHLElBQUksQ0FBQyxPQUFSO1lBQ0ksSUFBWSxFQUFFLENBQUMsTUFBSCxJQUFhLENBQXpCO2dCQUFBLEVBQUEsR0FBSyxJQUFMOztZQUNBLElBQUcsa0JBQUg7Z0JBQTJCLEVBQUEsR0FBUSxFQUFELEdBQUkseUJBQUosR0FBNEIsQ0FBQyxPQUFPLENBQUMsWUFBUixDQUFxQixhQUFyQixFQUFvQyxLQUFwQyxFQUF3QyxhQUF4QyxDQUFELENBQTVCLEdBQW1GLEtBQXJIOztZQUNBLEVBQUUsQ0FBQyxTQUFILENBQWEsTUFBYixFQUFxQixFQUFyQixFQUF5QixTQUFDLEdBQUQ7Z0JBQ3JCLElBQUcsR0FBSDtvQkFDSSxTQUFBLENBQVUsR0FBRyxDQUFDLE9BQWQ7MkJBQ0EsT0FBTyxDQUFDLElBQVIsQ0FBYSxDQUFiLEVBRko7aUJBQUEsTUFHSyxJQUFHLElBQUksQ0FBQyxPQUFMLElBQWlCLElBQUksQ0FBQyxLQUF6QjsyQkFDRCxPQUFBLENBQVEsV0FBQSxHQUFZLE1BQXBCLEVBREM7O1lBSmdCLENBQXpCLEVBSEo7O1FBU0EsSUFBRyxrQkFBSDttQkFDSSxFQUFFLENBQUMsU0FBSCxDQUFhLGFBQWIsRUFBNEIsa0JBQTVCLEVBQWdELFNBQUMsR0FBRDtnQkFDNUMsSUFBRyxHQUFIO29CQUNJLFNBQUEsQ0FBVSw4QkFBQSxHQUErQixHQUFHLENBQUMsT0FBN0M7MkJBQ0EsT0FBTyxDQUFDLElBQVIsQ0FBYSxDQUFiLEVBRko7O1lBRDRDLENBQWhELEVBREo7O0lBVk07V0FlVixFQUFFLENBQUMsTUFBSCxDQUFVLEtBQVYsRUFBaUIsU0FBQyxRQUFEO1FBQ2IsSUFBRyxRQUFIO21CQUFpQixPQUFBLENBQUEsRUFBakI7U0FBQSxNQUFBO21CQUFnQyxNQUFBLENBQU8sS0FBUCxFQUFjLE9BQWQsRUFBaEM7O0lBRGEsQ0FBakI7QUFuQk07O0FBc0JWLElBQUEsR0FBTyxTQUFDLFlBQUQsRUFBZSxJQUFmO1dBQXdCLFVBQUEsQ0FBVyxJQUFYLEVBQWlCLFlBQWpCO0FBQXhCOztBQUVQLE9BQUEsR0FBVSxTQUFDLE9BQUQ7V0FBYSxHQUFBLENBQU0sQ0FBQyxDQUFDLElBQUksSUFBTCxDQUFVLENBQUMsa0JBQVgsQ0FBQSxDQUFELENBQUEsR0FBaUMsS0FBakMsR0FBc0MsT0FBNUM7QUFBYjs7QUFRVixXQUFBLEdBQWMsU0FBQyxNQUFEO0FBTVYsUUFBQTtBQUFBO1NBQWEsbUdBQWI7UUFDSSxLQUFBLEdBQVEsTUFBTyxDQUFBLEtBQUE7UUFDZixHQUFBLEdBQVEsS0FBTSxDQUFBLENBQUE7UUFDZCxLQUFBLEdBQVEsS0FBTSxDQUFBLENBQUEsQ0FBRSxDQUFDLFFBQVQsQ0FBQSxDQUFtQixDQUFDLE9BQXBCLENBQTRCLElBQTVCLEVBQWtDLEtBQWxDO1FBQ1IsSUFBRyxHQUFBLEtBQU8sWUFBVjt5QkFDSSxLQUFBLENBQU0sTUFBTixHQURKO1NBQUEsTUFFSyxJQUFHLEdBQUEsS0FBTyxRQUFWO3lCQUNELEtBQUEsQ0FBTSxNQUFOLEdBREM7U0FBQSxNQUVBLElBQUcsR0FBQSxLQUFPLFNBQVY7eUJBQ0QsS0FBQSxDQUFNLE1BQU4sR0FEQztTQUFBLE1BRUEsSUFBRyxHQUFBLEtBQVEsT0FBUixJQUFBLEdBQUEsS0FBaUIsYUFBakIsSUFBQSxHQUFBLEtBQWdDLFdBQWhDLElBQUEsR0FBQSxLQUE2QyxNQUFoRDt5QkFDRCxLQUFBLENBQVMsS0FBRCxHQUFPLEdBQVAsR0FBVSxHQUFWLEdBQWMsR0FBdEIsR0FEQztTQUFBLE1BRUEsSUFBRyxHQUFBLEtBQU8sS0FBVjt5QkFDRCxLQUFBLENBQVMsS0FBRCxHQUFPLEdBQVAsR0FBVSxHQUFWLEdBQWMsR0FBdEIsR0FEQztTQUFBLE1BQUE7eUJBR0QsS0FBQSxDQUFTLEtBQUQsR0FBTyxHQUFQLEdBQVUsR0FBVixHQUFjLEdBQWQsR0FBaUIsS0FBakIsR0FBdUIsR0FBL0IsR0FIQzs7QUFaVDs7QUFOVTs7QUF1QmQsT0FBQSxHQUFVLFNBQUE7V0FBRyxTQUFBLENBQVUsRUFBQSxHQUFHLE1BQU0sQ0FBQyxPQUFwQjtBQUFIOztBQUNWLEtBQUEsR0FBVSxTQUFBO0FBRU4sUUFBQTtJQUFBLEtBQUEsR0FBUSxDQUFJLE1BQUQsR0FBUSxJQUFYO0lBRVIsS0FBQSxHQUFRLFFBQVEsQ0FBQyxHQUFULENBQWEsU0FBQyxJQUFEO0FBQ2pCLFlBQUE7UUFBQSxJQUFxQixJQUFJLENBQUMsTUFBTCxHQUFjLENBQW5DO1lBQUEsSUFBSSxDQUFDLE9BQUwsQ0FBYSxJQUFiLEVBQUE7O1FBQ0MsZUFBRCxFQUFRLGNBQVIsRUFBYztRQUNkLEtBQUEsR0FBVyxJQUFJLENBQUMsS0FBTCxDQUFXLGdCQUFYO1FBQ1gsUUFBQSxHQUFXLElBQUksQ0FBQyxLQUFMLENBQVcsZ0JBQVgsQ0FBNkIsQ0FBQSxDQUFBO1FBQ3hDLE1BQUEsR0FBYyxLQUFILEdBQWMsS0FBQSxHQUFRLElBQXRCLEdBQWdDO1FBQzNDLE1BQUEsR0FBVyxPQUFPLENBQUMsR0FBUixDQUFZLE1BQUEsR0FBUyxJQUFyQjtlQUNYLEtBQUssQ0FBQyxJQUFOLENBQVcsTUFBQSxHQUFTLE1BQVQsR0FBa0IsV0FBN0I7SUFQaUIsQ0FBYjtXQVNSLEdBQUEsQ0FBSSxJQUFBLEdBQUksQ0FBRSxLQUFLLENBQUMsSUFBTixDQUFXLElBQVgsQ0FBRixDQUFKLEdBQXdCLElBQTVCO0FBYk07O0FBZVYsUUFBQSxHQUFXLFNBQUE7QUFFUCxRQUFBO0lBQUEsQ0FBQSxHQUFJLFNBQUMsQ0FBRDtlQUFPLE1BQUEsR0FBTSxDQUFDLE9BQU8sQ0FBQyxHQUFSLENBQVksQ0FBRSxDQUFBLENBQUEsQ0FBZCxDQUFELENBQU4sR0FBMEIsQ0FBRSxDQUFBLENBQUE7SUFBbkM7V0FFSixHQUFBLENBQUksaUJBQUEsR0FBaUIsQ0FBRSxRQUFRLENBQUMsR0FBVCxDQUFhLENBQWIsQ0FBZSxDQUFDLElBQWhCLENBQXFCLElBQXJCLENBQUYsQ0FBakIsR0FBK0MsSUFBbkQ7QUFKTyIsInNvdXJjZXNDb250ZW50IjpbIiMjI1xuIDAwMDAwMDAgICAwMDAwMDAwICAgMDAgICAgIDAwICAwMCAgICAgMDAgICAwMDAwMDAwICAgMDAwICAgMDAwICAwMDAwMDAwICAgIFxuMDAwICAgICAgIDAwMCAgIDAwMCAgMDAwICAgMDAwICAwMDAgICAwMDAgIDAwMCAgIDAwMCAgMDAwMCAgMDAwICAwMDAgICAwMDAgIFxuMDAwICAgICAgIDAwMCAgIDAwMCAgMDAwMDAwMDAwICAwMDAwMDAwMDAgIDAwMDAwMDAwMCAgMDAwIDAgMDAwICAwMDAgICAwMDAgIFxuMDAwICAgICAgIDAwMCAgIDAwMCAgMDAwIDAgMDAwICAwMDAgMCAwMDAgIDAwMCAgIDAwMCAgMDAwICAwMDAwICAwMDAgICAwMDAgIFxuIDAwMDAwMDAgICAwMDAwMDAwICAgMDAwICAgMDAwICAwMDAgICAwMDAgIDAwMCAgIDAwMCAgMDAwICAgMDAwICAwMDAwMDAwICAgIFxuIyMjXG5cbiMgaGFuZGxlIHZhcmlvdXMgdGFza3M6IFxuI1xuIyAgIC0gY29tcGlsZSBhbmQgc2F2ZSBpbnRvIGAuanNgIGZpbGVzIFxuIyAgIC0gY29tcGlsZSBhbmQgcHJpbnQgdG8gc3Rkb3V0IFxuIyAgIC0gcmVjb21waWxlIGlmIHRoZSBzb3VyY2UgY2hhbmdlc1xuIyAgIC0gcHJpbnQgbGV4ZXIgdG9rZW5zXG4jICAgLSBwcmludCBhIHN5bnRheCB0cmVlXG4jICAgLSBsYXVuY2ggYSBSRVBMXG5cbmZzICAgICAgICAgICAgID0gcmVxdWlyZSAnZnMnXG5wYXRoICAgICAgICAgICA9IHJlcXVpcmUgJ3BhdGgnXG5ub3B0ICAgICAgICAgICA9IHJlcXVpcmUgJ25vcHQnXG5oZWxwZXJzICAgICAgICA9IHJlcXVpcmUgJy4vaGVscGVycydcbktvZmZlZSAgICAgICAgID0gcmVxdWlyZSAnLi9rb2ZmZWUnXG57c3Bhd24sIGV4ZWN9ICA9IHJlcXVpcmUgJ2NoaWxkX3Byb2Nlc3MnXG57RXZlbnRFbWl0dGVyfSA9IHJlcXVpcmUgJ2V2ZW50cydcblxudXNlV2luUGF0aFNlcCAgPSBwYXRoLnNlcCBpcyAnXFxcXCdcblxuaGVscGVycy5leHRlbmQgS29mZmVlLCBuZXcgRXZlbnRFbWl0dGVyICMgQWxsb3cgZW1pdHRpbmcgTm9kZSBldmVudHNcblxubG9nICAgICAgID0gY29uc29sZS5sb2dcbmVycm9yICAgICA9IGNvbnNvbGUuZXJyb3JcbnByaW50ICAgICA9IChsaW5lKSAtPiBwcm9jZXNzLnN0ZG91dC53cml0ZSBsaW5lXG5wcmludExpbmUgPSAobGluZSkgLT4gcHJvY2Vzcy5zdGRvdXQud3JpdGUgbGluZSArICdcXG4nICMgPz8/XG5wcmludFdhcm4gPSAobGluZSkgLT4gcHJvY2Vzcy5zdGRlcnIud3JpdGUgbGluZSArICdcXG4nICMgPz8/XG5oaWRkZW4gICAgPSAoZmlsZSkgLT4gL15cXC58fiQvLnRlc3QgZmlsZVxuXG5CQU5ORVIgPSBcIlVzYWdlOiBrb2ZmZWUgW29wdGlvbnNdIHBhdGgvdG8vc2NyaXB0IC0tIFthcmdzXVwiXG5cbkZFQVRVUkVTID0gW1xuICAgIFsnaGVhZGVyJywgICAgICAgICAgICAgICAgICAgICdwcmVmaXggd2l0aCBcIkdlbmVyYXRlZCBieVwiIGhlYWRlciddXG4gICAgWydyZXdyaXRlJywgICAgICAgICAgICAgICAgICAgJ3Jld3JpdGUgdG9rZW5zJ11cbiAgICBbJ2NvbmZpZy1wYXJhbWV0ZXJzJywgICAgICAgICAnZW5hYmxlIGNvbmZpZyBwYXJhbWV0ZXJzJ11cbiAgICBbJ2NvbnN0cnVjdG9yLXNob3J0Y3V0JywgICAgICAncmVwbGFjZSBAOiB3aXRoIGNvbnN0cnVjdG9yOiddXG4gICAgWyduZWdhdGl2ZS1pbmRleCcsICAgICAgICAgICAgJ3JlcGxhY2UgYVstMV0gd2l0aCBhWy0xLi4tMV0nXVxuXVxuXG5TV0lUQ0hFUyA9IFtcbiAgICBbJy1iJywgJy0tYmFyZScsICAgICAgICAgICAgICAnY29tcGlsZSB3aXRob3V0IGEgdG9wLWxldmVsIGZ1bmN0aW9uIHdyYXBwZXInLCAgICAgICAgICBCb29sZWFuICAgICAgICBdXG4gICAgWyctYycsICctLWNvbXBpbGUnLCAgICAgICAgICAgJ2NvbXBpbGUgdG8gSmF2YVNjcmlwdCBhbmQgc2F2ZSBhcyAuanMgZmlsZXMnLCAgICAgICAgICAgQm9vbGVhbiAgICAgICAgXVxuICAgIFsnLWUnLCAnLS1ldmFsIFtTVFJJTkddJywgICAgICdwYXNzIGEgc3RyaW5nIGZyb20gdGhlIGNvbW1hbmQgbGluZSBhcyBpbnB1dCcsICAgICAgICAgW1N0cmluZywgQXJyYXldIF1cbiAgICBbJy1mJywgJy0tZmVhdHVyZXMnLCAgICAgICAgICAnbGlzdCBhdmFpbGFibGUgZmVhdHVyZXMnLCAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICBCb29sZWFuICAgICAgICBdXG4gICAgWycnLCAgICctLW5vLVtmZWF0dXJlXScsICAgICAgJ2Rpc2FibGUgYSBmZWF0dXJlLCBlLmcuIC0tbm8tbmVnYXRpdmUtaW5kZXgnLCAgICAgICAgICAgbnVsbCAgICAgICAgICAgXVxuICAgIFsnLWgnLCAnLS1oZWxwJywgICAgICAgICAgICAgICdkaXNwbGF5IHRoaXMgaGVscCBtZXNzYWdlJywgICAgICAgICAgICAgICAgICAgICAgICAgICAgIEJvb2xlYW4gICAgICAgIF1cbiAgICBbJy1qJywgJy0tanMnLCAgICAgICAgICAgICAgICAncHJpbnQgb3V0IHRoZSBjb21waWxlZCBKYXZhU2NyaXB0JywgICAgICAgICAgICAgICAgICAgICBCb29sZWFuICAgICAgICBdXG4gICAgWyctbScsICctLW1hcCcsICAgICAgICAgICAgICAgJ2dlbmVyYXRlIHNvdXJjZSBtYXAgYW5kIHNhdmUgYXMgLmpzLm1hcCBmaWxlcycsICAgICAgICAgQm9vbGVhbiAgICAgICAgXVxuICAgIFsnLU0nLCAnLS1pbmxpbmUtbWFwJywgICAgICAgICdnZW5lcmF0ZSBzb3VyY2UgbWFwIGFuZCBpbmNsdWRlIGl0IGRpcmVjdGx5IGluIG91dHB1dCcsIEJvb2xlYW4gICAgICAgIF1cbiAgICBbJy1uJywgJy0tbm9vcCcsICAgICAgICAgICAgICAnZG9lcyBub3RoaW5nLCBmb3IgZGVidWdnaW5nIHB1cnBvc2VzJywgICAgICAgICAgICAgICAgICBCb29sZWFuICAgICAgICBdXG4gICAgWyctbycsICctLW91dHB1dCBbRElSXScsICAgICAgJ3NldCB0aGUgb3V0cHV0IGRpcmVjdG9yeSBmb3IgY29tcGlsZWQgSmF2YVNjcmlwdCcsICAgICAgU3RyaW5nICAgICAgICAgXVxuICAgIFsnLXAnLCAnLS1wYXJzZScsICAgICAgICAgICAgICdwcmludCBvdXQgdGhlIHBhcnNlIHRyZWUgdGhhdCB0aGUgcGFyc2VyIHByb2R1Y2VzJywgICAgIEJvb2xlYW4gICAgICAgIF1cbiAgICBbJy1yJywgJy0tcmVxdWlyZSBbTU9EVUxFXScsICAncmVxdWlyZSB0aGUgZ2l2ZW4gbW9kdWxlIGJlZm9yZSBldmFsIG9yIFJFUEwnLCAgICAgICAgIFtTdHJpbmcsIEFycmF5XSBdXG4gICAgWyctcycsICctLXN0ZGlvJywgICAgICAgICAgICAgJ2xpc3RlbiBmb3IgYW5kIGNvbXBpbGUgc2NyaXB0cyBvdmVyIHN0ZGlvJywgICAgICAgICAgICAgQm9vbGVhbiAgICAgICAgXVxuICAgIFsnLXQnLCAnLS10b2tlbnMnLCAgICAgICAgICAgICdwcmludCBvdXQgdGhlIHRva2VucyB0aGF0IHRoZSBsZXhlci9yZXdyaXRlciBwcm9kdWNlJywgIEJvb2xlYW4gICAgICAgIF1cbiAgICBbJy12JywgJy0tdmVyc2lvbicsICAgICAgICAgICAnZGlzcGxheSB0aGUgdmVyc2lvbiBudW1iZXInLCAgICAgICAgICAgICAgICAgICAgICAgICAgICBCb29sZWFuICAgICAgICBdXG4gICAgWyctdycsICctLXdhdGNoJywgICAgICAgICAgICAgJ3dhdGNoIHNjcmlwdHMgZm9yIGNoYW5nZXMgYW5kIHJlcnVuIGNvbW1hbmRzJywgICAgICAgICAgQm9vbGVhbiAgICAgICAgXVxuXVxuXG5vcHRzID0ge31cblxuIyAgMDAwMDAwMCAgIDAwMDAwMDAwICAgMDAwMDAwMDAwICAwMDAgICAwMDAwMDAwICAgMDAwICAgMDAwICAgMDAwMDAwMCAgXG4jIDAwMCAgIDAwMCAgMDAwICAgMDAwICAgICAwMDAgICAgIDAwMCAgMDAwICAgMDAwICAwMDAwICAwMDAgIDAwMCAgICAgICBcbiMgMDAwICAgMDAwICAwMDAwMDAwMCAgICAgIDAwMCAgICAgMDAwICAwMDAgICAwMDAgIDAwMCAwIDAwMCAgMDAwMDAwMCAgIFxuIyAwMDAgICAwMDAgIDAwMCAgICAgICAgICAgMDAwICAgICAwMDAgIDAwMCAgIDAwMCAgMDAwICAwMDAwICAgICAgIDAwMCAgXG4jICAwMDAwMDAwICAgMDAwICAgICAgICAgICAwMDAgICAgIDAwMCAgIDAwMDAwMDAgICAwMDAgICAwMDAgIDAwMDAwMDAgICBcblxucGFyc2VPcHRpb25zID0gLT5cblxuICAgIHRvZ2dsZXMgPSBbICdiYXJlJywgJ2NvbXBpbGUnLCAnZmVhdHVyZXMnLCAnaGVscCcsICdpbmxpbmUtbWFwJywgJ2pzJywgJ21hcCcsIFxuICAgICAgICAgICAgICAgICdwYXJzZScsICdzdGRpbycsICd0b2tlbnMnLCd2ZXJzaW9uJywgJ3dhdGNoJywgJ0RlYnVnJyBdIFxuICAgIFxuICAgIGtub3duID0ge0RlYnVnOkJvb2xlYW59XG4gICAgc2hvcnQgPSB7RDonLS1EZWJ1Zyd9XG4gICAgU1dJVENIRVMubWFwIChzKSAtPiBsID0gc1sxXS5zcGxpdCgnICcpWzBdWzIuLl07IGtub3duW2xdID0gc1szXSBpZiBzWzNdOyBzaG9ydFtzWzBdWzFdXSA9IFwiLS0je2x9XCIgaWYgc1swXSE9JydcbiAgICBGRUFUVVJFUy5tYXAgKGYpIC0+IGtub3duW2ZbMF1dID0gQm9vbGVhblxuICAgIFxuICAgIG8gPSBvcHRzID0gbm9wdCBrbm93biwgc2hvcnRcbiAgICAgICAgXG4gICAgIyBsb2cgb1xuICAgIFxuICAgIG8uY29tcGlsZSAgb3I9ICEhby5vdXRwdXRcbiAgICBvLmFyZ3VtZW50cyAgPSBvLmFyZ3YucmVtYWluXG4gICAgby5ydW4gICAgICAgID0gbm90IChvLmNvbXBpbGUgb3Igby5qcyBvciBvLm1hcCBvciBvLnRva2VucyBvciBvLnBhcnNlKVxuICAgIG8uanMgICAgICAgICA9ICEhKG8uanMgb3Igby5ldmFsIG9yIG8uc3RkaW8gYW5kIG8uY29tcGlsZSkgIyBqcyBvdXRwdXQgaXMgcGFzc2VkIHRvIGV2YWwgYW5kIHN0ZGlvIGNvbXBpbGVcbiAgICBcbiAgICBvLmZlYXR1cmUgPSB7fVxuICAgIEZFQVRVUkVTLm1hcCAoZikgLT4gby5mZWF0dXJlW2ZbMF1dID0gb1tmWzBdXSA/IHRydWU7IGRlbGV0ZSBvW2ZbMF1dXG4gICAgXG4gICAgaWYgby5EZWJ1Z1xuICAgICAgICBkZWxldGUgby5hcmd2XG4gICAgICAgIGxvZyBoZWxwZXJzLnN0cmluZ2lmeSBvXG5cbiMgMDAwMDAwMDAgICAwMDAgICAwMDAgIDAwMCAgIDAwMCAgXG4jIDAwMCAgIDAwMCAgMDAwICAgMDAwICAwMDAwICAwMDAgIFxuIyAwMDAwMDAwICAgIDAwMCAgIDAwMCAgMDAwIDAgMDAwICBcbiMgMDAwICAgMDAwICAwMDAgICAwMDAgIDAwMCAgMDAwMCAgXG4jIDAwMCAgIDAwMCAgIDAwMDAwMDAgICAwMDAgICAwMDAgIFxuXG4jIFJ1biBgY29mZmVlYCBieSBwYXJzaW5nIHBhc3NlZCBvcHRpb25zIGFuZCBkZXRlcm1pbmluZyB3aGF0IGFjdGlvbiB0byB0YWtlLlxuIyBNYW55IGZsYWdzIGNhdXNlIHVzIHRvIGRpdmVydCBiZWZvcmUgY29tcGlsaW5nIGFueXRoaW5nLiBcbiMgRmxhZ3MgcGFzc2VkIGFmdGVyIGAtLWAgd2lsbCBiZSBwYXNzZWQgdmVyYmF0aW0gaW4gYHByb2Nlc3MuYXJndmBcblxucnVuID0gLT5cbiAgICBcbiAgICBwYXJzZU9wdGlvbnMoKVxuICAgICAgICBcbiAgICByZXR1cm4gZmVhdHVyZXMoKSAgICAgaWYgb3B0cy5mZWF0dXJlc1xuICAgIHJldHVybiB1c2FnZSgpICAgICAgICBpZiBvcHRzLmhlbHBcbiAgICByZXR1cm4gdmVyc2lvbigpICAgICAgaWYgb3B0cy52ZXJzaW9uXG4gICAgcmV0dXJuIHN0YXJ0UmVwbCgpICAgIGlmIG9wdHMuaW50ZXJhY3RpdmVcbiAgICByZXR1cm4gY29tcGlsZVN0ZGlvKCkgaWYgb3B0cy5zdGRpb1xuICAgIGlmIG9wdHMuZXZhbFxuICAgICAgICBmb3IgZXZhbCBpbiBvcHRzLmV2YWxcbiAgICAgICAgICAgIGNvbXBpbGVTY3JpcHQgZXZhbFxuICAgICAgICByZXR1cm5cbiAgICByZXR1cm4gc3RhcnRSZXBsKCkgICAgaWYgbm90IG9wdHMuYXJndW1lbnRzLmxlbmd0aFxuICAgIFxuICAgIGxpdGVyYWxzID0gaWYgb3B0cy5ydW4gdGhlbiBvcHRzLmFyZ3VtZW50cy5zcGxpY2UgMSBlbHNlIFtdXG4gICAgXG4gICAgcHJvY2Vzcy5hcmd2ID0gcHJvY2Vzcy5hcmd2WzAuLjFdLmNvbmNhdCBsaXRlcmFsc1xuICAgIHByb2Nlc3MuYXJndlswXSA9ICdrb2ZmZWUnXG5cbiAgICBvcHRzLm91dHB1dCA9IHBhdGgucmVzb2x2ZSBvcHRzLm91dHB1dCBpZiBvcHRzLm91dHB1dFxuICAgIGZvciBzb3VyY2UgaW4gb3B0cy5hcmd1bWVudHNcbiAgICAgICAgc291cmNlID0gcGF0aC5yZXNvbHZlIHNvdXJjZVxuICAgICAgICBcbiAgICAgICAgaWYgb3B0cy53YXRjaFxuICAgICAgICAgICAgd2F0Y2hQYXRoIHNvdXJjZVxuICAgICAgICBlbHNlXG4gICAgICAgICAgICBjb21waWxlUGF0aCBzb3VyY2UsIHllc1xuXG5leHBvcnRzLnJ1biA9IHJ1blxuICAgICAgICBcbnN0YXJ0UmVwbCA9IC0+XG4gICAgXG4gICAgIyBNYWtlIHRoZSBSRVBMIHVzZSB0aGUgZ2xvYmFsIGNvbnRleHQgc28gYXMgdG8gXG4gICAgIyAgIChhKSBiZSBjb25zaXN0ZW50IHdpdGggdGhlIGBub2RlYCBSRVBMIGFuZCwgdGhlcmVmb3JlLCBcbiAgICAjICAgKGIpIG1ha2UgcGFja2FnZXMgdGhhdCBtb2RpZnkgbmF0aXZlIHByb3RvdHlwZXMgKHN1Y2ggYXMgJ2NvbG9ycycgYW5kICdzdWdhcicpIHdvcmsgYXMgZXhwZWN0ZWQuXG4gICAgXG4gICAgcmVwbENsaU9wdHMgPSB1c2VHbG9iYWw6IHllc1xuICAgIG9wdHMucHJlbHVkZSA9IG1ha2VQcmVsdWRlIG9wdHMucmVxdWlyZSBpZiBvcHRzLnJlcXVpcmVcbiAgICByZXBsQ2xpT3B0cy5wcmVsdWRlID0gb3B0cy5wcmVsdWRlXG4gICAgcmVxdWlyZSgnLi9yZXBsJykuc3RhcnQgcmVwbENsaU9wdHNcblxubWFrZVByZWx1ZGUgPSAocmVxdWlyZXMpIC0+XG4gICAgXG4gICAgcmVxdWlyZXMubWFwIChtb2R1bGUpIC0+XG4gICAgICAgIFtfLCBuYW1lLCBtb2R1bGVdID0gbWF0Y2ggaWYgbWF0Y2ggPSBtb2R1bGUubWF0Y2goL14oLiopPSguKikkLylcbiAgICAgICAgbmFtZSB8fD0gaGVscGVycy5iYXNlRmlsZU5hbWUgbW9kdWxlLCB5ZXMsIHVzZVdpblBhdGhTZXBcbiAgICAgICAgXCIje25hbWV9ID0gcmVxdWlyZSgnI3ttb2R1bGV9JylcIlxuICAgIC5qb2luICc7J1xuXG4jICAwMDAwMDAwICAgMDAwMDAwMCAgIDAwICAgICAwMCAgMDAwMDAwMDAgICAwMDAgIDAwMCAgICAgIDAwMDAwMDAwICBcbiMgMDAwICAgICAgIDAwMCAgIDAwMCAgMDAwICAgMDAwICAwMDAgICAwMDAgIDAwMCAgMDAwICAgICAgMDAwICAgICAgIFxuIyAwMDAgICAgICAgMDAwICAgMDAwICAwMDAwMDAwMDAgIDAwMDAwMDAwICAgMDAwICAwMDAgICAgICAwMDAwMDAwICAgXG4jIDAwMCAgICAgICAwMDAgICAwMDAgIDAwMCAwIDAwMCAgMDAwICAgICAgICAwMDAgIDAwMCAgICAgIDAwMCAgICAgICBcbiMgIDAwMDAwMDAgICAwMDAwMDAwICAgMDAwICAgMDAwICAwMDAgICAgICAgIDAwMCAgMDAwMDAwMCAgMDAwMDAwMDAgIFxuXG4jIENvbXBpbGUgYSBzY3JpcHQgb3IgYSBkaXJlY3RvcnkuIElmIGEgZGlyZWN0b3J5IGlzIHBhc3NlZCwgcmVjdXJzaXZlbHkgY29tcGlsZSBhbGwgJy5jb2ZmZWUnIGFuZCAnLmtvZmZlZScgZmlsZXMuXG5cbmNvbXBpbGVQYXRoID0gKHNvdXJjZSwgdG9wTGV2ZWwgPSBubykgLT5cblxuICAgIHJldHVybiBpZiBub3QgdG9wTGV2ZWwgYW5kIGhpZGRlbiBzb3VyY2VcbiAgICAgICAgICAgICAgXG4gICAgdHJ5XG4gICAgICAgIHN0YXRzID0gZnMuc3RhdFN5bmMgc291cmNlXG4gICAgY2F0Y2ggZXJyXG4gICAgICAgIGlmIGVyci5jb2RlIGlzICdFTk9FTlQnXG4gICAgICAgICAgICBlcnJvciBcIkNvbW1hbmQuY29tcGlsZVBhdGggY2FuJ3Qgc3RhdCAnI3tzb3VyY2V9J1wiXG4gICAgICAgICAgICBwcm9jZXNzLmV4aXQgMVxuICAgICAgICB0aHJvdyBlcnJcbiAgICAgICAgXG4gICAgaWYgc3RhdHMuaXNEaXJlY3RvcnkoKVxuICAgICAgICBcbiAgICAgICAgaWYgcGF0aC5iYXNlbmFtZShzb3VyY2UpIGluIFsnbm9kZV9tb2R1bGVzJywgJy5naXQnXVxuICAgICAgICAgICAgcmV0dXJuXG4gICAgICAgICAgICBcbiAgICAgICAgaWYgb3B0cy5ydW5cbiAgICAgICAgICAgIGNvbXBpbGVQYXRoIGZpbmREaXJlY3RvcnlJbmRleChzb3VyY2UpLCB0b3BMZXZlbFxuICAgICAgICAgICAgcmV0dXJuXG4gICAgICAgICAgICAgICAgIFxuICAgICAgICBsb2cgJ0NvbW1hbmQuY29tcGlsZVBhdGggZGlyOicsIHNvdXJjZSBpZiBvcHRzLkRlYnVnXG4gICAgICAgIFxuICAgICAgICB0cnlcbiAgICAgICAgICAgIGZpbGVzID0gZnMucmVhZGRpclN5bmMgc291cmNlXG4gICAgICAgIGNhdGNoIGVyclxuICAgICAgICAgICAgaWYgZXJyLmNvZGUgaXMgJ0VOT0VOVCcgdGhlbiByZXR1cm4gXG4gICAgICAgICAgICB0aHJvdyBlcnJcbiAgICAgICAgICAgIFxuICAgICAgICBmb3IgZmlsZSBpbiBmaWxlc1xuICAgICAgICAgICAgY29tcGlsZVBhdGggcGF0aC5qb2luIHNvdXJjZSwgZmlsZVxuICAgICAgICAgICAgXG4gICAgZWxzZSBpZiB0b3BMZXZlbCBvciBoZWxwZXJzLmlzQ29mZmVlIHNvdXJjZVxuICAgICAgICBcbiAgICAgICAgdHJ5XG4gICAgICAgICAgICBjb2RlID0gZnMucmVhZEZpbGVTeW5jIHNvdXJjZVxuICAgICAgICBjYXRjaCBlcnJcbiAgICAgICAgICAgIGlmIGVyci5jb2RlIGlzICdFTk9FTlQnIHRoZW4gcmV0dXJuXG4gICAgICAgICAgICB0aHJvdyBlcnJcbiAgICAgICAgXG4gICAgICAgIGxvZyAnQ29tbWFuZC5jb21waWxlUGF0aCBmaWxlOicsIHNvdXJjZSBpZiBvcHRzLkRlYnVnXG4gICAgICAgICAgICBcbiAgICAgICAgY29tcGlsZVNjcmlwdCBjb2RlLnRvU3RyaW5nKCksIHNvdXJjZVxuICAgICAgICBcbmZpbmREaXJlY3RvcnlJbmRleCA9IChzb3VyY2UpIC0+XG5cbiAgICBmb3IgZXh0IGluIEtvZmZlZS5GSUxFX0VYVEVOU0lPTlNcbiAgICAgICAgaW5kZXggPSBwYXRoLmpvaW4gc291cmNlLCBcImluZGV4I3tleHR9XCJcbiAgICAgICAgdHJ5XG4gICAgICAgICAgICByZXR1cm4gaW5kZXggaWYgKGZzLnN0YXRTeW5jIGluZGV4KS5pc0ZpbGUoKVxuICAgICAgICBjYXRjaCBlcnJcbiAgICAgICAgICAgIHRocm93IGVyciB1bmxlc3MgZXJyLmNvZGUgaXMgJ0VOT0VOVCdcbiAgICBlcnJvciBcIk1pc3NpbmcgaW5kZXguY29mZmVlIGluICN7c291cmNlfVwiXG4gICAgcHJvY2Vzcy5leGl0IDFcblxuIyAgMDAwMDAwMCAgIDAwMDAwMDAgICAwMCAgICAgMDAgIDAwMDAwMDAwICAgMDAwICAwMDAgICAgICAwMDAwMDAwMCAgIDAwMDAwMDAgICAwMDAwMDAwICAwMDAwMDAwMCAgIDAwMCAgMDAwMDAwMDAgICAwMDAwMDAwMDAgIFxuIyAwMDAgICAgICAgMDAwICAgMDAwICAwMDAgICAwMDAgIDAwMCAgIDAwMCAgMDAwICAwMDAgICAgICAwMDAgICAgICAgMDAwICAgICAgIDAwMCAgICAgICAwMDAgICAwMDAgIDAwMCAgMDAwICAgMDAwICAgICAwMDAgICAgIFxuIyAwMDAgICAgICAgMDAwICAgMDAwICAwMDAwMDAwMDAgIDAwMDAwMDAwICAgMDAwICAwMDAgICAgICAwMDAwMDAwICAgMDAwMDAwMCAgIDAwMCAgICAgICAwMDAwMDAwICAgIDAwMCAgMDAwMDAwMDAgICAgICAwMDAgICAgIFxuIyAwMDAgICAgICAgMDAwICAgMDAwICAwMDAgMCAwMDAgIDAwMCAgICAgICAgMDAwICAwMDAgICAgICAwMDAgICAgICAgICAgICAwMDAgIDAwMCAgICAgICAwMDAgICAwMDAgIDAwMCAgMDAwICAgICAgICAgICAwMDAgICAgIFxuIyAgMDAwMDAwMCAgIDAwMDAwMDAgICAwMDAgICAwMDAgIDAwMCAgICAgICAgMDAwICAwMDAwMDAwICAwMDAwMDAwMCAgMDAwMDAwMCAgICAwMDAwMDAwICAwMDAgICAwMDAgIDAwMCAgMDAwICAgICAgICAgICAwMDAgICAgIFxuXG4jIENvbXBpbGUgYSBzaW5nbGUgc291cmNlIHNjcmlwdCwgY29udGFpbmluZyB0aGUgZ2l2ZW4gY29kZSwgYWNjb3JkaW5nIHRvIHRoZSByZXF1ZXN0ZWQgb3B0aW9ucy4gXG4jIElmIGV2YWx1YXRpbmcgdGhlIHNjcmlwdCBkaXJlY3RseSBzZXRzIGBfX2ZpbGVuYW1lYCwgYF9fZGlybmFtZWAgYW5kIGBtb2R1bGUuZmlsZW5hbWVgIHRvIGJlIGNvcnJlY3QgcmVsYXRpdmUgdG8gdGhlIHNjcmlwdCdzIHBhdGguXG5cbmNvbXBpbGVTY3JpcHQgPSAoaW5wdXQsIGZpbGUgPSBudWxsKSAtPlxuICAgIFxuICAgIG8gPSBvcHRzXG4gICAgb3B0aW9ucyA9IGNvbXBpbGVPcHRpb25zIGZpbGVcbiAgICBcbiAgICB0cnlcbiAgICAgICAgdCA9IHRhc2sgPSB7ZmlsZSwgaW5wdXQsIG9wdGlvbnN9XG4gICAgICAgIEtvZmZlZS5lbWl0ICdjb21waWxlJywgdGFza1xuICAgICAgICBpZiBvLnRva2Vuc1xuICAgICAgICAgICAgcHJpbnRUb2tlbnMgS29mZmVlLnRva2VucyB0LmlucHV0LCB0Lm9wdGlvbnNcbiAgICAgICAgZWxzZSBpZiBvLm5vZGVzXG4gICAgICAgICAgICBwcmludExpbmUgS29mZmVlLm5vZGVzKHQuaW5wdXQsIHQub3B0aW9ucykudG9TdHJpbmcoKS50cmltKClcbiAgICAgICAgZWxzZSBpZiBvLnJ1blxuICAgICAgICAgICAgS29mZmVlLnJlZ2lzdGVyKClcbiAgICAgICAgICAgIEtvZmZlZS5ldmFsIG9wdHMucHJlbHVkZSwgdC5vcHRpb25zIGlmIG9wdHMucHJlbHVkZVxuICAgICAgICAgICAgIyBsb2cgXCJDb21tYW5kLmNvbXBpbGVTY3JpcHQgS29mZmVlLnJ1biBpbnB1dDpcIiwgdC5pbnB1dCBpZiBvcHRzLkRlYnVnXG4gICAgICAgICAgICB0Lm9wdGlvbnMuZmlsZW5hbWUgPz0gb3B0aW9ucy5zb3VyY2VcbiAgICAgICAgICAgICMgbG9nIFwiQ29tbWFuZC5jb21waWxlU2NyaXB0IEtvZmZlZS5ydW4gb3B0aW9uczpcIiwgdC5vcHRpb25zIGlmIG9wdHMuRGVidWdcbiAgICAgICAgICAgICMgbG9nIFwiQ29tbWFuZC5jb21waWxlU2NyaXB0IEtvZmZlZS5ydW4gdGFzazpcIiwgdCBpZiBvcHRzLkRlYnVnXG4gICAgICAgICAgICBpZiBvcHRzLm5vb3AgdGhlbiBsb2cgXCJub29wIHJ1biAje2ZpbGV9XCJcbiAgICAgICAgICAgIGVsc2VcbiAgICAgICAgICAgICAgICBLb2ZmZWUucnVuIHQuaW5wdXQsIHQub3B0aW9uc1xuICAgICAgICBlbHNlXG4gICAgICAgICAgICBjb21waWxlZCA9IEtvZmZlZS5jb21waWxlIHQuaW5wdXQsIHQub3B0aW9uc1xuICAgICAgICAgICAgdC5vdXRwdXQgPSBjb21waWxlZFxuICAgICAgICAgICAgaWYgby5tYXBcbiAgICAgICAgICAgICAgICB0Lm91dHB1dCA9IGNvbXBpbGVkLmpzXG4gICAgICAgICAgICAgICAgdC5zb3VyY2VNYXAgPSBjb21waWxlZC52M1NvdXJjZU1hcFxuXG4gICAgICAgICAgICBLb2ZmZWUuZW1pdCAnc3VjY2VzcycsIHRhc2tcbiAgICAgICAgICAgIFxuICAgICAgICAgICAgaWYgby5qc1xuICAgICAgICAgICAgICAgIGlmIG9wdHMubm9vcCB0aGVuIGxvZyBcIm5vb3AganMgI3tmaWxlfVwiXG4gICAgICAgICAgICAgICAgZWxzZSBcbiAgICAgICAgICAgICAgICAgICAgcHJpbnRMaW5lIHQub3V0cHV0LnRyaW0oKVxuICAgICAgICAgICAgZWxzZSBpZiBvLmNvbXBpbGUgb3Igby5tYXBcbiAgICAgICAgICAgICAgICBpZiBvcHRzLm5vb3AgdGhlbiBsb2cgXCJub29wIHdyaXRlICN7b3B0aW9ucy5qc1BhdGh9XCJcbiAgICAgICAgICAgICAgICBlbHNlXG4gICAgICAgICAgICAgICAgICAgIHdyaXRlSnMgdC5maWxlLCB0Lm91dHB1dCwgb3B0aW9ucy5qc1BhdGgsIHQuc291cmNlTWFwXG4gICAgY2F0Y2ggZXJyXG4gICAgICAgIFxuICAgICAgICBLb2ZmZWUuZW1pdCAnZmFpbHVyZScsIGVyciwgdGFza1xuICAgICAgICByZXR1cm4gaWYgS29mZmVlLmxpc3RlbmVycygnZmFpbHVyZScpLmxlbmd0aFxuICAgICAgICBtZXNzYWdlID0gZXJyPy5zdGFjayBvciBcIiN7ZXJyfVwiXG4gICAgICAgIGlmIG8ud2F0Y2hcbiAgICAgICAgICAgIHByaW50TGluZSBtZXNzYWdlICsgJ1xceDA3J1xuICAgICAgICBlbHNlXG4gICAgICAgICAgICBwcmludFdhcm4gbWVzc2FnZVxuICAgICAgICAgICAgcHJvY2Vzcy5leGl0IDFcblxuY29tcGlsZU9wdGlvbnMgPSAoc291cmNlKSAtPiAjIFRoZSBjb21waWxlLXRpbWUgb3B0aW9ucyB0byBwYXNzIHRvIHRoZSBjb21waWxlci5cbiAgICBcbiAgICBjb3B0cyA9ICAgICAgICAgXG4gICAgICAgIHNvdXJjZTogICAgc291cmNlXG4gICAgICAgIHNvdXJjZU1hcDogb3B0cy5tYXBcbiAgICAgICAgaW5saW5lTWFwOiBvcHRzWydpbmxpbmUtbWFwJ11cbiAgICAgICAgZmVhdHVyZTogICBvcHRzLmZlYXR1cmVcbiAgICAgICAgYmFyZTogICAgICBvcHRzLmJhcmVcbiAgICAgICAgRGVidWc6ICAgICBvcHRzLkRlYnVnXG5cbiAgICBpZiBzb3VyY2VcbiAgICAgICAgXG4gICAgICAgIGN3ZCA9IHByb2Nlc3MuY3dkKClcbiAgICAgICAganNQYXRoID0gb3V0cHV0UGF0aCBzb3VyY2UsICcuanMnXG4gICAgICAgIGpzRGlyID0gcGF0aC5kaXJuYW1lIGpzUGF0aFxuICAgICAgICBjb3B0cyA9IGhlbHBlcnMubWVyZ2UgY29wdHMsIHtcbiAgICAgICAgICAgIGpzUGF0aFxuICAgICAgICAgICAgc291cmNlUm9vdDogcGF0aC5yZWxhdGl2ZSBqc0RpciwgY3dkXG4gICAgICAgICAgICBzb3VyY2VGaWxlczogW3BhdGgucmVsYXRpdmUgY3dkLCBzb3VyY2VdXG4gICAgICAgICAgICBnZW5lcmF0ZWRGaWxlOiBoZWxwZXJzLmJhc2VGaWxlTmFtZShqc1BhdGgsIG5vLCB1c2VXaW5QYXRoU2VwKVxuICAgICAgICB9XG4gICAgICAgICMgZWxzZVxuICAgICAgICAgICAgIyBjb3B0cyA9IGhlbHBlcnMubWVyZ2UgY29wdHMsXG4gICAgICAgICAgICAgICAgIyBzb3VyY2VSb290OiBcIlwiXG4gICAgICAgICAgICAgICAgIyBzb3VyY2VGaWxlczogW2hlbHBlcnMuYmFzZUZpbGVOYW1lIHNvdXJjZSwgbm8sIHVzZVdpblBhdGhTZXBdXG4gICAgICAgICAgICAgICAgIyBnZW5lcmF0ZWRGaWxlOiBoZWxwZXJzLmJhc2VGaWxlTmFtZShzb3VyY2UsIHllcywgdXNlV2luUGF0aFNlcCkgKyBcIi5qc1wiXG4gICAgY29wdHNcbiAgICAgICAgICAgIFxuIyBBdHRhY2ggdGhlIGFwcHJvcHJpYXRlIGxpc3RlbmVycyB0byBjb21waWxlIHNjcmlwdHMgaW5jb21pbmcgb3ZlciAqKnN0ZGluKiosIGFuZCB3cml0ZSB0aGVtIGJhY2sgdG8gKipzdGRvdXQqKi5cblxuY29tcGlsZVN0ZGlvID0gLT5cbiAgICBcbiAgICBidWZmZXJzID0gW11cbiAgICBzdGRpbiA9IHByb2Nlc3Mub3BlblN0ZGluKClcbiAgICBzdGRpbi5vbiAnZGF0YScsIChidWZmZXIpIC0+XG4gICAgICAgIGJ1ZmZlcnMucHVzaCBidWZmZXIgaWYgYnVmZmVyXG4gICAgc3RkaW4ub24gJ2VuZCcsIC0+XG4gICAgICAgIGNvbXBpbGVTY3JpcHQgQnVmZmVyLmNvbmNhdChidWZmZXJzKS50b1N0cmluZygpXG5cbiMgMDAwICAgMDAwICAgMDAwMDAwMCAgIDAwMDAwMDAwMCAgIDAwMDAwMDAgIDAwMCAgIDAwMCAgXG4jIDAwMCAwIDAwMCAgMDAwICAgMDAwICAgICAwMDAgICAgIDAwMCAgICAgICAwMDAgICAwMDAgIFxuIyAwMDAwMDAwMDAgIDAwMDAwMDAwMCAgICAgMDAwICAgICAwMDAgICAgICAgMDAwMDAwMDAwICBcbiMgMDAwICAgMDAwICAwMDAgICAwMDAgICAgIDAwMCAgICAgMDAwICAgICAgIDAwMCAgIDAwMCAgXG4jIDAwICAgICAwMCAgMDAwICAgMDAwICAgICAwMDAgICAgICAwMDAwMDAwICAwMDAgICAwMDAgIFxuXG53YXRjaFBhdGggPSAoc291cmNlKSAtPiAjIFdhdGNoIGEgZmlsZSBvciBkaXJlY3RvcnkuXG4gICAgXG4gICAgdHJ5XG4gICAgICAgIHN0YXRzID0gZnMuc3RhdFN5bmMgc291cmNlXG4gICAgY2F0Y2ggZXJyXG4gICAgICAgIHJldHVybiBpZiBlcnIuY29kZSBpcyAnRU5PRU5UJ1xuICAgICAgICByZXR1cm4gZXJyb3IgXCJDb21tYW5kLndhdGNoUGF0aCBjYW4ndCBzdGF0ICcje3NvdXJjZX0nXCIsIGVyclxuICAgICAgICAgICAgICAgIFxuICAgIGlmIHN0YXRzLmlzRGlyZWN0b3J5KClcbiAgICAgICAgd2F0Y2hEaXIgc291cmNlXG4gICAgZWxzZVxuICAgICAgICB3YXRjaEZpbGUgc291cmNlXG5cbiMgV2F0Y2ggYSBzaW5nbGUgZmlsZSB1c2luZyBgZnMud2F0Y2hgLCByZWNvbXBpbGluZyBpdCBldmVyeSB0aW1lIHRoZSBmaWxlIGlzIHVwZGF0ZWQuXG4jIE1heSBiZSB1c2VkIGluIGNvbWJpbmF0aW9uIHdpdGggb3RoZXIgb3B0aW9ucywgc3VjaCBhcyBgLS1wcmludGAuXG4gICAgICAgIFxud2F0Y2hGaWxlID0gKHNvdXJjZSkgLT5cbiAgICBcbiAgICByZXR1cm4gaWYgbm90IGhlbHBlcnMuaXNDb2ZmZWUgc291cmNlXG4gICAgXG4gICAgbG9nICdDb21tYW5kLndhdGNoRmlsZScsIHNvdXJjZSBpZiBvcHRzLkRlYnVnXG4gICAgXG4gICAgd2F0Y2hlciAgICAgICAgPSBudWxsXG4gICAgcHJldlN0YXRzICAgICAgPSBudWxsXG4gICAgY29tcGlsZVRpbWVvdXQgPSBudWxsXG5cbiAgICBzdGFydFdhdGNoZXIgPSAtPlxuICAgICAgICBcbiAgICAgICAgd2F0Y2hlciA9IGZzLndhdGNoIHNvdXJjZVxuICAgICAgICAub24gJ2NoYW5nZScsIChjaGFuZ2UpIC0+XG4gICAgICAgICAgICBcbiAgICAgICAgICAgIHJldHVybiBpZiBjaGFuZ2UgIT0gJ2NoYW5nZSdcbiAgICAgICAgICAgIFxuICAgICAgICAgICAgbG9nICdDb21tYW5kLndhdGNoRmlsZScsIGNoYW5nZSwgc291cmNlIGlmIG9wdHMuRGVidWdcblxuICAgICAgICAgICAgY2xlYXJUaW1lb3V0IGNvbXBpbGVUaW1lb3V0XG4gICAgICAgICAgICBjb21waWxlVGltZW91dCA9IHdhaXQgMjUsIC0+XG4gICAgICAgICAgICAgICAgXG4gICAgICAgICAgICAgICAgZnMuc3RhdCBzb3VyY2UsIChlcnIsIHN0YXRzKSAtPlxuICAgICAgICAgICAgICAgICAgICByZXR1cm4gd2F0Y2hlci5jbG9zZSgpIGlmIGVycj8uY29kZSBpcyAnRU5PRU5UJ1xuICAgICAgICAgICAgICAgICAgICByZXR1cm4gZXJyb3IgZXJyIGlmIGVyclxuICAgICAgICAgICAgICAgICAgICByZXR1cm4gaWYgcHJldlN0YXRzIGFuZCBzdGF0cy5tdGltZS5nZXRUaW1lKCkgaXMgcHJldlN0YXRzLm10aW1lLmdldFRpbWUoKSBhbmQgc3RhdHMuc2l6ZSBpcyBwcmV2U3RhdHMuc2l6ZVxuICAgICAgICAgICAgICAgICAgICBwcmV2U3RhdHMgPSBzdGF0c1xuICAgICAgICAgICAgICAgICAgICBmcy5yZWFkRmlsZSBzb3VyY2UsIChlcnIsIGNvZGUpIC0+XG4gICAgICAgICAgICAgICAgICAgICAgICByZXR1cm4gZXJyb3IgZXJyIGlmIGVyclxuICAgICAgICAgICAgICAgICAgICAgICAgbG9nICdDb21tYW5kLndhdGNoRmlsZSBjb21waWxlJywgc291cmNlIGlmIG9wdHMuRGVidWdcbiAgICAgICAgICAgICAgICAgICAgICAgIGNvbXBpbGVTY3JpcHQgY29kZS50b1N0cmluZygpLCBzb3VyY2VcbiAgICAgICAgICAgICAgICAgICAgICAgIFxuICAgICAgICAub24gJ2Vycm9yJywgKGVycikgLT5cbiAgICAgICAgICAgIHRocm93IGVyciB1bmxlc3MgZXJyLmNvZGUgaXMgJ0VQRVJNJ1xuXG4gICAgdHJ5XG4gICAgICAgIHN0YXJ0V2F0Y2hlcigpXG4gICAgY2F0Y2ggZXJyXG4gICAgICAgIGVycm9yIGVyclxuXG53YXRjaERpciA9IChzb3VyY2UpIC0+XG4gICAgXG4gICAgbG9nICdDb21tYW5kLndhdGNoRGlyJywgc291cmNlIGlmIG9wdHMuRGVidWdcbiAgICBcbiAgICB3YXRjaGVyID0gbnVsbFxuXG4gICAgc3RhcnRXYXRjaGVyID0gLT5cblxuICAgICAgICB0cnlcbiAgICAgICAgICAgIGZpbGVzID0gZnMucmVhZGRpclN5bmMgc291cmNlXG4gICAgICAgIGNhdGNoIGVyclxuICAgICAgICAgICAgcmV0dXJuIGlmIGVycj8uY29kZSBpcyAnRU5PRU5UJ1xuICAgICAgICAgICAgdGhyb3cgZXJyXG4gICAgICAgICAgICBcbiAgICAgICAgZm9yIGZpbGUgaW4gZmlsZXNcbiAgICAgICAgICAgIGNvbnRpbnVlIGlmIGZpbGVbMF0gPT0gJy4nXG4gICAgICAgICAgICBjb250aW51ZSBpZiBmaWxlIGluIFsnbm9kZV9tb2R1bGVzJ11cbiAgICAgICAgICAgIHdhdGNoUGF0aCBwYXRoLmpvaW4gc291cmNlLCBmaWxlXG4gICAgICAgIFxuICAgICAgICB3YXRjaGVyID0gZnMud2F0Y2ggc291cmNlXG4gICAgICAgIC5vbiAnZXJyb3InLCAoZXJyKSAtPlxuICAgICAgICAgICAgdGhyb3cgZXJyIHVubGVzcyBlcnIuY29kZSBpcyAnRVBFUk0nXG4gICAgICAgICAgICB3YXRjaGVyLmNsb3NlKClcbiAgICAgICAgLm9uICdjaGFuZ2UnLCAoY2hhbmdlLCBwKSAtPlxuICAgICAgICAgICAgaWYgY2hhbmdlID09ICdyZW5hbWUnXG4gICAgICAgICAgICAgICAgbG9nICdDb21tYW5kLndhdGNoRGlyJywgY2hhbmdlLCBwYXRoLmpvaW4gc291cmNlLCBwIGlmIG9wdHMuRGVidWdcbiAgICAgICAgICAgICAgICB3YXRjaFBhdGggcGF0aC5qb2luIHNvdXJjZSwgcFxuICAgICAgICAgICAgXG4gICAgdHJ5XG4gICAgICAgIHN0YXJ0V2F0Y2hlcigpXG4gICAgY2F0Y2ggZXJyXG4gICAgICAgIHJldHVybiBpZiBlcnIuY29kZSBpcyAnRU5PRU5UJ1xuICAgICAgICB0aHJvdyBlcnJcblxuIyBHZXQgdGhlIGNvcnJlc3BvbmRpbmcgb3V0cHV0IEphdmFTY3JpcHQgcGF0aCBmb3IgYSBzb3VyY2UgZmlsZS5cbiAgICBcbm91dHB1dFBhdGggPSAoc291cmNlLCBleHRlbnNpb24pIC0+XG4gICAgXG4gICAgYmFzZW5hbWUgPSBoZWxwZXJzLmJhc2VGaWxlTmFtZSBzb3VyY2UsIHllcywgdXNlV2luUGF0aFNlcFxuICAgIGlmIG9wdHMub3V0cHV0XG4gICAgICAgIGRpciA9IG9wdHMub3V0cHV0XG4gICAgZWxzZVxuICAgICAgICBkaXIgPSBwYXRoLmRpcm5hbWUgc291cmNlXG4gICAgcGF0aC5qb2luIGRpciwgYmFzZW5hbWUgKyBleHRlbnNpb25cblxuIyBSZWN1cnNpdmVseSBta2RpciwgbGlrZSBgbWtkaXIgLXBgLlxuXG5ta2RpcnAgPSAoZGlyLCBmbikgLT5cbiAgICBtb2RlID0gMG83NzcgJiB+cHJvY2Vzcy51bWFzaygpXG5cbiAgICBkbyBta2RpcnMgPSAocCA9IGRpciwgZm4pIC0+XG4gICAgICAgIGZzLmV4aXN0cyBwLCAoZXhpc3RzKSAtPlxuICAgICAgICAgICAgaWYgZXhpc3RzXG4gICAgICAgICAgICAgICAgZm4oKVxuICAgICAgICAgICAgZWxzZVxuICAgICAgICAgICAgICAgIG1rZGlycyBwYXRoLmRpcm5hbWUocCksIC0+XG4gICAgICAgICAgICAgICAgICAgIGZzLm1rZGlyIHAsIG1vZGUsIChlcnIpIC0+XG4gICAgICAgICAgICAgICAgICAgICAgICByZXR1cm4gZm4gZXJyIGlmIGVyclxuICAgICAgICAgICAgICAgICAgICAgICAgZm4oKVxuXG4jIDAwMCAgIDAwMCAgMDAwMDAwMDAgICAwMDAgIDAwMDAwMDAwMCAgMDAwMDAwMDAgICAgICAgIDAwMCAgIDAwMDAwMDAgIFxuIyAwMDAgMCAwMDAgIDAwMCAgIDAwMCAgMDAwICAgICAwMDAgICAgIDAwMCAgICAgICAgICAgICAwMDAgIDAwMCAgICAgICBcbiMgMDAwMDAwMDAwICAwMDAwMDAwICAgIDAwMCAgICAgMDAwICAgICAwMDAwMDAwICAgICAgICAgMDAwICAwMDAwMDAwICAgXG4jIDAwMCAgIDAwMCAgMDAwICAgMDAwICAwMDAgICAgIDAwMCAgICAgMDAwICAgICAgIDAwMCAgIDAwMCAgICAgICAwMDAgIFxuIyAwMCAgICAgMDAgIDAwMCAgIDAwMCAgMDAwICAgICAwMDAgICAgIDAwMDAwMDAwICAgMDAwMDAwMCAgIDAwMDAwMDAgICBcblxuIyBXcml0ZSBvdXQgYSBKYXZhU2NyaXB0IHNvdXJjZSBmaWxlIHdpdGggdGhlIGNvbXBpbGVkIGNvZGUuIFxuIyBCeSBkZWZhdWx0LCBmaWxlcyBhcmUgd3JpdHRlbiBvdXQgaW4gYGN3ZGAgYXMgYC5qc2AgZmlsZXMgd2l0aCB0aGUgc2FtZSBuYW1lLCBidXQgdGhlIG91dHB1dCBkaXJlY3RvcnkgY2FuIGJlIGN1c3RvbWl6ZWQgd2l0aCBgLS1vdXRwdXRgLlxuIyBJZiBgZ2VuZXJhdGVkU291cmNlTWFwYCBpcyBwcm92aWRlZCwgdGhpcyB3aWxsIHdyaXRlIGEgYC5qcy5tYXBgIGZpbGUgaW50byB0aGUgc2FtZSBkaXJlY3RvcnkgYXMgdGhlIGAuanNgIGZpbGUuXG5cbndyaXRlSnMgPSAoc291cmNlLCBqcywganNQYXRoLCBnZW5lcmF0ZWRTb3VyY2VNYXAgPSBudWxsKSAtPlxuICAgIFxuICAgIHNvdXJjZU1hcFBhdGggPSBvdXRwdXRQYXRoIHNvdXJjZSwgJy5qcy5tYXAnXG4gICAganNEaXIgPSBwYXRoLmRpcm5hbWUganNQYXRoXG4gICAgY29tcGlsZSA9IC0+XG4gICAgICAgIGlmIG9wdHMuY29tcGlsZVxuICAgICAgICAgICAganMgPSAnICcgaWYganMubGVuZ3RoIDw9IDBcbiAgICAgICAgICAgIGlmIGdlbmVyYXRlZFNvdXJjZU1hcCB0aGVuIGpzID0gXCIje2pzfVxcbi8vIyBzb3VyY2VNYXBwaW5nVVJMPSN7aGVscGVycy5iYXNlRmlsZU5hbWUgc291cmNlTWFwUGF0aCwgbm8sIHVzZVdpblBhdGhTZXB9XFxuXCJcbiAgICAgICAgICAgIGZzLndyaXRlRmlsZSBqc1BhdGgsIGpzLCAoZXJyKSAtPlxuICAgICAgICAgICAgICAgIGlmIGVyclxuICAgICAgICAgICAgICAgICAgICBwcmludExpbmUgZXJyLm1lc3NhZ2VcbiAgICAgICAgICAgICAgICAgICAgcHJvY2Vzcy5leGl0IDFcbiAgICAgICAgICAgICAgICBlbHNlIGlmIG9wdHMuY29tcGlsZSBhbmQgb3B0cy53YXRjaFxuICAgICAgICAgICAgICAgICAgICB0aW1lTG9nIFwiY29tcGlsZWQgI3tzb3VyY2V9XCJcbiAgICAgICAgaWYgZ2VuZXJhdGVkU291cmNlTWFwXG4gICAgICAgICAgICBmcy53cml0ZUZpbGUgc291cmNlTWFwUGF0aCwgZ2VuZXJhdGVkU291cmNlTWFwLCAoZXJyKSAtPlxuICAgICAgICAgICAgICAgIGlmIGVyclxuICAgICAgICAgICAgICAgICAgICBwcmludExpbmUgXCJDb3VsZCBub3Qgd3JpdGUgc291cmNlIG1hcDogI3tlcnIubWVzc2FnZX1cIlxuICAgICAgICAgICAgICAgICAgICBwcm9jZXNzLmV4aXQgMVxuICAgIGZzLmV4aXN0cyBqc0RpciwgKGl0RXhpc3RzKSAtPlxuICAgICAgICBpZiBpdEV4aXN0cyB0aGVuIGNvbXBpbGUoKSBlbHNlIG1rZGlycCBqc0RpciwgY29tcGlsZVxuXG53YWl0ID0gKG1pbGxpc2Vjb25kcywgZnVuYykgLT4gc2V0VGltZW91dCBmdW5jLCBtaWxsaXNlY29uZHMgIyBDb252ZW5pZW5jZSBmb3IgY2xlYW5lciBzZXRUaW1lb3V0cy5cblxudGltZUxvZyA9IChtZXNzYWdlKSAtPiBsb2cgXCIjeyhuZXcgRGF0ZSkudG9Mb2NhbGVUaW1lU3RyaW5nKCl9IC0gI3ttZXNzYWdlfVwiXG5cbiMgMDAwMDAwMDAwICAgMDAwMDAwMCAgIDAwMCAgIDAwMCAgMDAwMDAwMDAgIDAwMCAgIDAwMCAgIDAwMDAwMDAgIFxuIyAgICAwMDAgICAgIDAwMCAgIDAwMCAgMDAwICAwMDAgICAwMDAgICAgICAgMDAwMCAgMDAwICAwMDAgICAgICAgXG4jICAgIDAwMCAgICAgMDAwICAgMDAwICAwMDAwMDAwICAgIDAwMDAwMDAgICAwMDAgMCAwMDAgIDAwMDAwMDAgICBcbiMgICAgMDAwICAgICAwMDAgICAwMDAgIDAwMCAgMDAwICAgMDAwICAgICAgIDAwMCAgMDAwMCAgICAgICAwMDAgIFxuIyAgICAwMDAgICAgICAwMDAwMDAwICAgMDAwICAgMDAwICAwMDAwMDAwMCAgMDAwICAgMDAwICAwMDAwMDAwICAgXG5cbnByaW50VG9rZW5zID0gKHRva2VucykgLT5cbiAgICAjIHN0cmluZ3MgPSBmb3IgdG9rZW4gaW4gdG9rZW5zXG4gICAgICAgICMgdGFnID0gdG9rZW5bMF1cbiAgICAgICAgIyB2YWx1ZSA9IHRva2VuWzFdLnRvU3RyaW5nKCkucmVwbGFjZSgvXFxuLywgJ1xcXFxuJylcbiAgICAgICAgIyBcIlsje3RhZ30gI3t2YWx1ZX1dXCJcbiAgICAjIHByaW50TGluZSBzdHJpbmdzLmpvaW4oJyAnKVxuICAgIGZvciBpbmRleCBpbiBbMC4uLnRva2Vucy5sZW5ndGhdXG4gICAgICAgIHRva2VuID0gdG9rZW5zW2luZGV4XVxuICAgICAgICB0YWcgICA9IHRva2VuWzBdXG4gICAgICAgIHZhbHVlID0gdG9rZW5bMV0udG9TdHJpbmcoKS5yZXBsYWNlKC9cXG4vLCAnXFxcXG4nKVxuICAgICAgICBpZiB0YWcgPT0gJ1RFUk1JTkFUT1InXG4gICAgICAgICAgICBwcmludCAnXFxuXFxuJ1xuICAgICAgICBlbHNlIGlmIHRhZyA9PSAnSU5ERU5UJ1xuICAgICAgICAgICAgcHJpbnQgJ0lORCAnXG4gICAgICAgIGVsc2UgaWYgdGFnID09ICdPVVRERU5UJ1xuICAgICAgICAgICAgcHJpbnQgJ09VVCAnXG4gICAgICAgIGVsc2UgaWYgdGFnIGluIFsnQ0xBU1MnLCAnUEFSQU1fU1RBUlQnLCAnUEFSQU1fRU5EJywgJ05VTEwnXVxuICAgICAgICAgICAgcHJpbnQgXCIje2luZGV4fSAje3RhZ30gXCJcbiAgICAgICAgZWxzZSBpZiB0YWcgaXMgdmFsdWVcbiAgICAgICAgICAgIHByaW50IFwiI3tpbmRleH0gI3t0YWd9IFwiXG4gICAgICAgIGVsc2VcbiAgICAgICAgICAgIHByaW50IFwiI3tpbmRleH0gI3t0YWd9PSN7dmFsdWV9IFwiXG4gICAgICAgIFxudmVyc2lvbiA9IC0+IHByaW50TGluZSBcIiN7S29mZmVlLlZFUlNJT059XCJcbnVzYWdlICAgPSAtPiBcblxuICAgIGxpbmVzID0gW1wiI3tCQU5ORVJ9XFxuXCJdXG4gICAgXG4gICAgcnVsZXMgPSBTV0lUQ0hFUy5tYXAgKHJ1bGUpIC0+XG4gICAgICAgIHJ1bGUudW5zaGlmdCBudWxsIGlmIHJ1bGUubGVuZ3RoIDwgM1xuICAgICAgICBbc2hvcnQsIGxvbmcsIGRlc2NyaXB0aW9uXSA9IHJ1bGVcbiAgICAgICAgbWF0Y2ggICAgPSBsb25nLm1hdGNoKC9cXFsoXFx3KyhcXCo/KSlcXF0vKVxuICAgICAgICBsb25nRmxhZyA9IGxvbmcubWF0Y2goL14oLS1cXHdbXFx3XFwtXSopLylbMV1cbiAgICAgICAgbGV0dGVyICAgPSBpZiBzaG9ydCB0aGVuIHNob3J0ICsgJywgJyBlbHNlICcgICAgJ1xuICAgICAgICBvcHRpb24gICA9IGhlbHBlcnMucGFkIGxldHRlciArIGxvbmdcbiAgICAgICAgbGluZXMucHVzaCAnICAgICcgKyBvcHRpb24gKyBkZXNjcmlwdGlvblxuICAgICAgICBcbiAgICBsb2cgXCJcXG4jeyBsaW5lcy5qb2luKCdcXG4nKSB9XFxuXCJcbiAgICAgICAgXG5mZWF0dXJlcyA9IC0+XG4gICAgXG4gICAgZiA9IChmKSAtPiBcIiAgICAje2hlbHBlcnMucGFkIGZbMF19I3tmWzFdfVwiXG4gICAgICAgIFxuICAgIGxvZyBcIlxcbkZlYXR1cmVzOlxcblxcbiN7IEZFQVRVUkVTLm1hcChmKS5qb2luKCdcXG4nKSB9XFxuXCJcbiJdfQ==
//# sourceURL=../src/command.coffee