
/*
000   000   0000000   00000000  00000000  00000000  00000000  
000  000   000   000  000       000       000       000       
0000000    000   000  000000    000000    0000000   0000000   
000  000   000   000  000       000       000       000       
000   000   0000000   000       000       00000000  00000000
 */
var FILE_EXTENSIONS, Lexer, SourceMap, base64encode, compile, formatSourcePosition, fs, getSourceMap, helpers, lexer, parser, path, pkg, sourceMaps, sources, vm, withPrettyErrors,
  hasProp = {}.hasOwnProperty;

fs = require('fs');

vm = require('vm');

path = require('path');

Lexer = require('./lexer').Lexer;

parser = require('./parser').parser;

helpers = require('./helpers');

SourceMap = require('./sourcemap');

pkg = require('../package.json');

exports.VERSION = pkg.version;

exports.FILE_EXTENSIONS = FILE_EXTENSIONS = ['.coffee', '.koffee'];

exports.helpers = helpers;

base64encode = function(src) {
  switch (false) {
    case typeof Buffer !== 'function':
      return Buffer.from(src).toString('base64');
    case typeof btoa !== 'function':
      return btoa(encodeURIComponent(src).replace(/%([0-9A-F]{2})/g, function(match, p1) {
        return String.fromCharCode('0x' + p1);
      }));
    default:
      throw new Error('Unable to base64 encode inline sourcemap.');
  }
};

withPrettyErrors = function(fn) {
  return function(code, options) {
    var err;
    if (options == null) {
      options = {};
    }
    try {
      return fn.call(this, code, options);
    } catch (error) {
      err = error;
      if (typeof code !== 'string') {
        throw new Error(err.toString());
      } else {
        throw helpers.updateSyntaxError(err, code, options.filename);
      }
    }
  };
};

sources = {};

sourceMaps = {};

exports.compile = compile = withPrettyErrors(function(code, options) {
  var currentColumn, currentLine, encoded, extend, filename, fragment, fragments, generateSourceMap, header, i, j, js, len, len1, map, merge, newLines, ref, ref1, sourceMapDataURI, sourceURL, token, tokens, v3SourceMap;
  merge = helpers.merge, extend = helpers.extend;
  options = extend({}, options);
  generateSourceMap = options.sourceMap || options.inlineMap || (options.filename == null);
  filename = options.filename || '<anonymous>';
  sources[filename] = code;
  if (generateSourceMap) {
    map = new SourceMap;
  }
  tokens = lexer.tokenize(code, options);
  options.referencedVars = (function() {
    var i, len, results;
    results = [];
    for (i = 0, len = tokens.length; i < len; i++) {
      token = tokens[i];
      if (token[0] === 'IDENTIFIER') {
        results.push(token[1]);
      }
    }
    return results;
  })();
  if (!((options.bare != null) && options.bare === true)) {
    for (i = 0, len = tokens.length; i < len; i++) {
      token = tokens[i];
      if ((ref = token[0]) === 'IMPORT' || ref === 'EXPORT') {
        options.bare = true;
        break;
      }
    }
  }
  fragments = parser.parse(tokens).compileToFragments(options);
  currentLine = 0;
  if (options.header) {
    currentLine += 1;
  }
  if (options.shiftLine) {
    currentLine += 1;
  }
  currentColumn = 0;
  js = "";
  for (j = 0, len1 = fragments.length; j < len1; j++) {
    fragment = fragments[j];
    if (generateSourceMap) {
      if (fragment.locationData && !/^[;\s]*$/.test(fragment.code)) {
        map.add([fragment.locationData.first_line, fragment.locationData.first_column], [currentLine, currentColumn], {
          noReplace: true
        });
      }
      newLines = helpers.count(fragment.code, "\n");
      currentLine += newLines;
      if (newLines) {
        currentColumn = fragment.code.length - (fragment.code.lastIndexOf("\n") + 1);
      } else {
        currentColumn += fragment.code.length;
      }
    }
    js += fragment.code;
  }
  if (options.header) {
    header = "Generated by koffee " + this.VERSION;
    js = "// " + header + "\n" + js;
  }
  if (generateSourceMap) {
    v3SourceMap = map.generate(options, code);
    sourceMaps[filename] = map;
  }
  if (options.inlineMap) {
    encoded = base64encode(JSON.stringify(v3SourceMap));
    sourceMapDataURI = "//# sourceMappingURL=data:application/json;base64," + encoded;
    sourceURL = "//# sourceURL=" + ((ref1 = options.filename) != null ? ref1 : 'koffee');
    js = js + "\n" + sourceMapDataURI + "\n" + sourceURL;
  }
  if (options.sourceMap) {
    return {
      js: js,
      sourceMap: map,
      v3SourceMap: JSON.stringify(v3SourceMap, null, 2)
    };
  } else {
    return js;
  }
});

exports.tokens = withPrettyErrors(function(code, options) {
  return lexer.tokenize(code, options);
});

exports.nodes = withPrettyErrors(function(source, options) {
  if (typeof source === 'string') {
    return parser.parse(lexer.tokenize(source, options));
  } else {
    return parser.parse(source);
  }
});

exports.run = function(code, options) {
  var answer, dir, mainModule, ref;
  if (options == null) {
    options = {};
  }
  mainModule = require.main;
  mainModule.filename = process.argv[1] = options.filename ? fs.realpathSync(options.filename) : '<anonymous>';
  mainModule.moduleCache && (mainModule.moduleCache = {});
  dir = options.filename != null ? path.dirname(fs.realpathSync(options.filename)) : fs.realpathSync('.');
  mainModule.paths = require('module')._nodeModulePaths(dir);
  if (!helpers.isCoffee(mainModule.filename) || require.extensions) {
    answer = compile(code, options);
    code = (ref = answer.js) != null ? ref : answer;
  }
  return mainModule._compile(code, mainModule.filename);
};

exports["eval"] = function(code, options) {
  var Module, _module, _require, createContext, i, isContext, js, k, len, o, r, ref, ref1, ref2, ref3, sandbox, v;
  if (options == null) {
    options = {};
  }
  if (!(code = code.trim())) {
    return;
  }
  createContext = (ref = vm.Script.createContext) != null ? ref : vm.createContext;
  isContext = (ref1 = vm.isContext) != null ? ref1 : function(ctx) {
    return options.sandbox instanceof createContext().constructor;
  };
  if (createContext) {
    if (options.sandbox != null) {
      if (isContext(options.sandbox)) {
        sandbox = options.sandbox;
      } else {
        sandbox = createContext();
        ref2 = options.sandbox;
        for (k in ref2) {
          if (!hasProp.call(ref2, k)) continue;
          v = ref2[k];
          sandbox[k] = v;
        }
      }
      sandbox.global = sandbox.root = sandbox.GLOBAL = sandbox;
    } else {
      sandbox = global;
    }
    sandbox.__filename = options.filename || 'eval';
    sandbox.__dirname = path.dirname(sandbox.__filename);
    if (!(sandbox !== global || sandbox.module || sandbox.require)) {
      Module = require('module');
      sandbox.module = _module = new Module(options.modulename || 'eval');
      sandbox.require = _require = function(path) {
        return Module._load(path, _module, true);
      };
      _module.filename = sandbox.__filename;
      ref3 = Object.getOwnPropertyNames(require);
      for (i = 0, len = ref3.length; i < len; i++) {
        r = ref3[i];
        if (r !== 'paths' && r !== 'arguments' && r !== 'caller') {
          _require[r] = require[r];
        }
      }
      _require.paths = _module.paths = Module._nodeModulePaths(process.cwd());
      _require.resolve = function(request) {
        return Module._resolveFilename(request, _module);
      };
    }
  }
  o = {};
  for (k in options) {
    if (!hasProp.call(options, k)) continue;
    v = options[k];
    o[k] = v;
  }
  o.bare = true;
  js = compile(code, o);
  if (sandbox === global) {
    return vm.runInThisContext(js);
  } else {
    return vm.runInContext(js, sandbox);
  }
};

exports.register = function() {
  return require('./register');
};

exports._compileFile = function(filename, sourceMap, inlineMap) {
  var answer, err, raw, stripped;
  if (sourceMap == null) {
    sourceMap = false;
  }
  if (inlineMap == null) {
    inlineMap = false;
  }
  raw = fs.readFileSync(filename, 'utf8');
  stripped = raw.charCodeAt(0) === 0xFEFF ? raw.substring(1) : raw;
  try {
    answer = compile(stripped, {
      filename: filename,
      sourceMap: sourceMap,
      inlineMap: inlineMap,
      sourceFiles: [filename]
    });
  } catch (error) {
    err = error;
    throw helpers.updateSyntaxError(err, stripped, filename);
  }
  return answer;
};

lexer = new Lexer;

parser.lexer = {
  lex: function() {
    var ref, tag, token;
    token = parser.tokens[this.pos++];
    if (token) {
      tag = token[0], this.yytext = token[1], this.yylloc = token[2];
      parser.errorToken = token.origin || token;
      if (((ref = this.yylloc) != null ? ref.first_line : void 0) == null) {
        console.log('DAFUK', token);
      }
      this.yylineno = this.yylloc.first_line;
    } else {
      tag = '';
    }
    return tag;
  },
  setInput: function(tokens) {
    parser.tokens = tokens;
    return this.pos = 0;
  },
  upcomingInput: function() {
    return "";
  }
};

parser.yy = require('./nodes');

parser.yy.parseError = function(message, arg) {
  var errorLoc, errorTag, errorText, errorToken, token, tokens;
  token = arg.token;
  errorToken = parser.errorToken, tokens = parser.tokens;
  errorTag = errorToken[0], errorText = errorToken[1], errorLoc = errorToken[2];
  errorText = (function() {
    switch (false) {
      case errorToken !== tokens[tokens.length - 1]:
        return 'end of input';
      case errorTag !== 'INDENT' && errorTag !== 'OUTDENT':
        return 'indentation';
      case errorTag !== 'IDENTIFIER' && errorTag !== 'NUMBER' && errorTag !== 'INFINITY' && errorTag !== 'STRING' && errorTag !== 'STRING_START' && errorTag !== 'REGEX' && errorTag !== 'REGEX_START':
        return errorTag.replace(/_START$/, '').toLowerCase();
      default:
        return helpers.nameWhitespaceCharacter(errorText);
    }
  })();
  return helpers.throwSyntaxError("unexpected " + errorText, errorLoc);
};

getSourceMap = function(filename) {
  var answer;
  if (sourceMaps[filename] != null) {
    return sourceMaps[filename];
  } else if (sourceMaps['<anonymous>'] != null) {
    return sourceMaps['<anonymous>'];
  } else if (sources[filename] != null) {
    answer = compile(sources[filename], {
      filename: filename,
      sourceMap: true
    });
    return answer.sourceMap;
  } else {
    return null;
  }
};

Error.prepareStackTrace = function(err, stack) {
  var frame, frames, getSourceMapping;
  getSourceMapping = function(filename, line, column) {
    var answer, sourceMap;
    sourceMap = getSourceMap(filename);
    if (sourceMap != null) {
      answer = sourceMap.sourceLocation([line - 1, column - 1]);
    }
    if (answer != null) {
      return [answer[0] + 1, answer[1] + 1];
    } else {
      return null;
    }
  };
  frames = (function() {
    var i, len, results;
    results = [];
    for (i = 0, len = stack.length; i < len; i++) {
      frame = stack[i];
      if (frame.getFunction() === exports.run) {
        break;
      }
      results.push("        at " + (formatSourcePosition(frame, getSourceMapping)));
    }
    return results;
  })();
  return (err.toString()) + "\n" + (frames.join('\n')) + "\n";
};

formatSourcePosition = function(frame, getSourceMapping) {
  var as, column, fileLocation, filename, functionName, isConstructor, isMethodCall, line, methodName, source, tp, typeName;
  filename = void 0;
  fileLocation = '';
  if (frame.isNative()) {
    fileLocation = "native";
  } else {
    if (frame.isEval()) {
      filename = frame.getScriptNameOrSourceURL();
      if (!filename) {
        fileLocation = (frame.getEvalOrigin()) + ", ";
      }
    } else {
      filename = frame.getFileName();
    }
    filename || (filename = "<anonymous>");
    line = frame.getLineNumber();
    column = frame.getColumnNumber();
    source = getSourceMapping(filename, line, column);
    fileLocation = source ? filename + ":" + source[0] + ":" + source[1] : filename + ":" + line + ":" + column;
  }
  functionName = frame.getFunctionName();
  isConstructor = frame.isConstructor();
  isMethodCall = !(frame.isToplevel() || isConstructor);
  if (isMethodCall) {
    methodName = frame.getMethodName();
    typeName = frame.getTypeName();
    if (functionName) {
      tp = as = '';
      if (typeName && functionName.indexOf(typeName)) {
        tp = typeName + ".";
      }
      if (methodName && functionName.indexOf("." + methodName) !== functionName.length - methodName.length - 1) {
        as = " [as " + methodName + "]";
      }
      return "" + tp + functionName + as + " (" + fileLocation + ")";
    } else {
      return typeName + "." + (methodName || '<anonymous>') + " (" + fileLocation + ")";
    }
  } else if (isConstructor) {
    return "new " + (functionName || '<anonymous>') + " (" + fileLocation + ")";
  } else if (functionName) {
    return functionName + " (" + fileLocation + ")";
  } else {
    return fileLocation;
  }
};

//# sourceMappingURL=data:application/json;base64,eyJ2ZXJzaW9uIjozLCJmaWxlIjoia29mZmVlLmpzIiwic291cmNlUm9vdCI6Ii4iLCJzb3VyY2VzIjpbIiJdLCJuYW1lcyI6W10sIm1hcHBpbmdzIjoiO0FBQUE7Ozs7Ozs7QUFBQSxJQUFBLDhLQUFBO0VBQUE7O0FBV0EsRUFBQSxHQUFZLE9BQUEsQ0FBUSxJQUFSOztBQUNaLEVBQUEsR0FBWSxPQUFBLENBQVEsSUFBUjs7QUFDWixJQUFBLEdBQVksT0FBQSxDQUFRLE1BQVI7O0FBQ1gsUUFBVyxPQUFBLENBQVEsU0FBUjs7QUFDWCxTQUFXLE9BQUEsQ0FBUSxVQUFSOztBQUNaLE9BQUEsR0FBWSxPQUFBLENBQVEsV0FBUjs7QUFDWixTQUFBLEdBQVksT0FBQSxDQUFRLGFBQVI7O0FBQ1osR0FBQSxHQUFZLE9BQUEsQ0FBUSxpQkFBUjs7QUFFWixPQUFPLENBQUMsT0FBUixHQUFrQixHQUFHLENBQUM7O0FBRXRCLE9BQU8sQ0FBQyxlQUFSLEdBQTBCLGVBQUEsR0FBa0IsQ0FBQyxTQUFELEVBQVksU0FBWjs7QUFFNUMsT0FBTyxDQUFDLE9BQVIsR0FBa0I7O0FBRWxCLFlBQUEsR0FBZSxTQUFDLEdBQUQ7QUFFWCxVQUFBLEtBQUE7QUFBQSxTQUNTLE9BQU8sTUFBUCxLQUFpQixVQUQxQjthQUVRLE1BQU0sQ0FBQyxJQUFQLENBQVksR0FBWixDQUFnQixDQUFDLFFBQWpCLENBQTBCLFFBQTFCO0FBRlIsU0FHUyxPQUFPLElBQVAsS0FBZSxVQUh4QjthQVFRLElBQUEsQ0FBSyxrQkFBQSxDQUFtQixHQUFuQixDQUF1QixDQUFDLE9BQXhCLENBQWdDLGlCQUFoQyxFQUFtRCxTQUFDLEtBQUQsRUFBUSxFQUFSO2VBQ3BELE1BQU0sQ0FBQyxZQUFQLENBQW9CLElBQUEsR0FBTyxFQUEzQjtNQURvRCxDQUFuRCxDQUFMO0FBUlI7QUFXUSxZQUFNLElBQUksS0FBSixDQUFVLDJDQUFWO0FBWGQ7QUFGVzs7QUFpQmYsZ0JBQUEsR0FBbUIsU0FBQyxFQUFEO1NBRWYsU0FBQyxJQUFELEVBQU8sT0FBUDtBQUNJLFFBQUE7O01BREcsVUFBVTs7QUFDYjthQUNJLEVBQUUsQ0FBQyxJQUFILENBQVEsSUFBUixFQUFXLElBQVgsRUFBaUIsT0FBakIsRUFESjtLQUFBLGFBQUE7TUFFTTtNQUNGLElBQUcsT0FBTyxJQUFQLEtBQWUsUUFBbEI7QUFDSSxjQUFNLElBQUksS0FBSixDQUFVLEdBQUcsQ0FBQyxRQUFKLENBQUEsQ0FBVixFQURWO09BQUEsTUFBQTtBQUdJLGNBQU0sT0FBTyxDQUFDLGlCQUFSLENBQTBCLEdBQTFCLEVBQStCLElBQS9CLEVBQXFDLE9BQU8sQ0FBQyxRQUE3QyxFQUhWO09BSEo7O0VBREo7QUFGZTs7QUFtQm5CLE9BQUEsR0FBVTs7QUFJVixVQUFBLEdBQWE7O0FBbUJiLE9BQU8sQ0FBQyxPQUFSLEdBQWtCLE9BQUEsR0FBVSxnQkFBQSxDQUFpQixTQUFDLElBQUQsRUFBTyxPQUFQO0FBRXpDLE1BQUE7RUFBQyxxQkFBRCxFQUFRO0VBQ1IsT0FBQSxHQUFVLE1BQUEsQ0FBTyxFQUFQLEVBQVcsT0FBWDtFQU1WLGlCQUFBLEdBQW9CLE9BQU8sQ0FBQyxTQUFSLElBQXFCLE9BQU8sQ0FBQyxTQUE3QixJQUE4QztFQUNsRSxRQUFBLEdBQVcsT0FBTyxDQUFDLFFBQVIsSUFBb0I7RUFFL0IsT0FBUSxDQUFBLFFBQUEsQ0FBUixHQUFvQjtFQUNwQixJQUF1QixpQkFBdkI7SUFBQSxHQUFBLEdBQU0sSUFBSSxVQUFWOztFQUVBLE1BQUEsR0FBUyxLQUFLLENBQUMsUUFBTixDQUFlLElBQWYsRUFBcUIsT0FBckI7RUFJVCxPQUFPLENBQUMsY0FBUjs7QUFDSTtTQUFBLHdDQUFBOztVQUFrQyxLQUFNLENBQUEsQ0FBQSxDQUFOLEtBQVk7cUJBQTlDLEtBQU0sQ0FBQSxDQUFBOztBQUFOOzs7RUFLSixJQUFBLENBQUEsQ0FBTyxzQkFBQSxJQUFrQixPQUFPLENBQUMsSUFBUixLQUFnQixJQUF6QyxDQUFBO0FBQ0ksU0FBQSx3Q0FBQTs7TUFDSSxXQUFHLEtBQU0sQ0FBQSxDQUFBLEVBQU4sS0FBYSxRQUFiLElBQUEsR0FBQSxLQUF1QixRQUExQjtRQUNJLE9BQU8sQ0FBQyxJQUFSLEdBQWU7QUFDZixjQUZKOztBQURKLEtBREo7O0VBTUEsU0FBQSxHQUFZLE1BQU0sQ0FBQyxLQUFQLENBQWEsTUFBYixDQUFvQixDQUFDLGtCQUFyQixDQUF3QyxPQUF4QztFQUVaLFdBQUEsR0FBYztFQUNkLElBQW9CLE9BQU8sQ0FBQyxNQUE1QjtJQUFBLFdBQUEsSUFBZSxFQUFmOztFQUNBLElBQW9CLE9BQU8sQ0FBQyxTQUE1QjtJQUFBLFdBQUEsSUFBZSxFQUFmOztFQUNBLGFBQUEsR0FBZ0I7RUFDaEIsRUFBQSxHQUFLO0FBRUwsT0FBQSw2Q0FBQTs7SUFFSSxJQUFHLGlCQUFIO01BRUksSUFBRyxRQUFRLENBQUMsWUFBVCxJQUEwQixDQUFJLFVBQVUsQ0FBQyxJQUFYLENBQWdCLFFBQVEsQ0FBQyxJQUF6QixDQUFqQztRQUNJLEdBQUcsQ0FBQyxHQUFKLENBQ0ksQ0FBQyxRQUFRLENBQUMsWUFBWSxDQUFDLFVBQXZCLEVBQW1DLFFBQVEsQ0FBQyxZQUFZLENBQUMsWUFBekQsQ0FESixFQUVJLENBQUMsV0FBRCxFQUFjLGFBQWQsQ0FGSixFQUdJO1VBQUMsU0FBQSxFQUFXLElBQVo7U0FISixFQURKOztNQUtBLFFBQUEsR0FBVyxPQUFPLENBQUMsS0FBUixDQUFjLFFBQVEsQ0FBQyxJQUF2QixFQUE2QixJQUE3QjtNQUNYLFdBQUEsSUFBZTtNQUNmLElBQUcsUUFBSDtRQUNJLGFBQUEsR0FBZ0IsUUFBUSxDQUFDLElBQUksQ0FBQyxNQUFkLEdBQXVCLENBQUMsUUFBUSxDQUFDLElBQUksQ0FBQyxXQUFkLENBQTBCLElBQTFCLENBQUEsR0FBa0MsQ0FBbkMsRUFEM0M7T0FBQSxNQUFBO1FBR0ksYUFBQSxJQUFpQixRQUFRLENBQUMsSUFBSSxDQUFDLE9BSG5DO09BVEo7O0lBZUEsRUFBQSxJQUFNLFFBQVEsQ0FBQztBQWpCbkI7RUFtQkEsSUFBRyxPQUFPLENBQUMsTUFBWDtJQUNJLE1BQUEsR0FBUyxzQkFBQSxHQUF1QixJQUFDLENBQUE7SUFDakMsRUFBQSxHQUFLLEtBQUEsR0FBTSxNQUFOLEdBQWEsSUFBYixHQUFpQixHQUYxQjs7RUFJQSxJQUFHLGlCQUFIO0lBQ0ksV0FBQSxHQUFjLEdBQUcsQ0FBQyxRQUFKLENBQWEsT0FBYixFQUFzQixJQUF0QjtJQUNkLFVBQVcsQ0FBQSxRQUFBLENBQVgsR0FBdUIsSUFGM0I7O0VBSUEsSUFBRyxPQUFPLENBQUMsU0FBWDtJQUNJLE9BQUEsR0FBVSxZQUFBLENBQWEsSUFBSSxDQUFDLFNBQUwsQ0FBZSxXQUFmLENBQWI7SUFDVixnQkFBQSxHQUFtQixvREFBQSxHQUFxRDtJQUN4RSxTQUFBLEdBQVksZ0JBQUEsR0FBZ0IsNENBQW9CLFFBQXBCO0lBQzVCLEVBQUEsR0FBUSxFQUFELEdBQUksSUFBSixHQUFRLGdCQUFSLEdBQXlCLElBQXpCLEdBQTZCLFVBSnhDOztFQU1BLElBQUcsT0FBTyxDQUFDLFNBQVg7V0FDSTtNQUNJLElBQUEsRUFESjtNQUVJLFNBQUEsRUFBVyxHQUZmO01BR0ksV0FBQSxFQUFhLElBQUksQ0FBQyxTQUFMLENBQWUsV0FBZixFQUE0QixJQUE1QixFQUFrQyxDQUFsQyxDQUhqQjtNQURKO0dBQUEsTUFBQTtXQU9JLEdBUEo7O0FBeEV5QyxDQUFqQjs7QUF5RjVCLE9BQU8sQ0FBQyxNQUFSLEdBQWlCLGdCQUFBLENBQWlCLFNBQUMsSUFBRCxFQUFPLE9BQVA7U0FDOUIsS0FBSyxDQUFDLFFBQU4sQ0FBZSxJQUFmLEVBQXFCLE9BQXJCO0FBRDhCLENBQWpCOztBQVlqQixPQUFPLENBQUMsS0FBUixHQUFnQixnQkFBQSxDQUFpQixTQUFDLE1BQUQsRUFBUyxPQUFUO0VBQzdCLElBQUcsT0FBTyxNQUFQLEtBQWlCLFFBQXBCO1dBQ0ksTUFBTSxDQUFDLEtBQVAsQ0FBYSxLQUFLLENBQUMsUUFBTixDQUFlLE1BQWYsRUFBdUIsT0FBdkIsQ0FBYixFQURKO0dBQUEsTUFBQTtXQUdJLE1BQU0sQ0FBQyxLQUFQLENBQWEsTUFBYixFQUhKOztBQUQ2QixDQUFqQjs7QUFjaEIsT0FBTyxDQUFDLEdBQVIsR0FBYyxTQUFDLElBQUQsRUFBTyxPQUFQO0FBRVYsTUFBQTs7SUFGaUIsVUFBVTs7RUFFM0IsVUFBQSxHQUFhLE9BQU8sQ0FBQztFQUdyQixVQUFVLENBQUMsUUFBWCxHQUFzQixPQUFPLENBQUMsSUFBSyxDQUFBLENBQUEsQ0FBYixHQUNmLE9BQU8sQ0FBQyxRQUFYLEdBQXlCLEVBQUUsQ0FBQyxZQUFILENBQWdCLE9BQU8sQ0FBQyxRQUF4QixDQUF6QixHQUFnRTtFQUdwRSxVQUFVLENBQUMsZ0JBQVgsVUFBVSxDQUFDLGNBQWlCO0VBRzVCLEdBQUEsR0FBUyx3QkFBSCxHQUNGLElBQUksQ0FBQyxPQUFMLENBQWEsRUFBRSxDQUFDLFlBQUgsQ0FBZ0IsT0FBTyxDQUFDLFFBQXhCLENBQWIsQ0FERSxHQUdGLEVBQUUsQ0FBQyxZQUFILENBQWdCLEdBQWhCO0VBQ0osVUFBVSxDQUFDLEtBQVgsR0FBbUIsT0FBQSxDQUFRLFFBQVIsQ0FBaUIsQ0FBQyxnQkFBbEIsQ0FBbUMsR0FBbkM7RUFHbkIsSUFBRyxDQUFJLE9BQU8sQ0FBQyxRQUFSLENBQWlCLFVBQVUsQ0FBQyxRQUE1QixDQUFKLElBQTZDLE9BQU8sQ0FBQyxVQUF4RDtJQUNJLE1BQUEsR0FBUyxPQUFBLENBQVEsSUFBUixFQUFjLE9BQWQ7SUFDVCxJQUFBLHFDQUFtQixPQUZ2Qjs7U0FJQSxVQUFVLENBQUMsUUFBWCxDQUFvQixJQUFwQixFQUEwQixVQUFVLENBQUMsUUFBckM7QUF2QlU7O0FBaUNkLE9BQU8sRUFBQyxJQUFELEVBQVAsR0FBZSxTQUFDLElBQUQsRUFBTyxPQUFQO0FBRVgsTUFBQTs7SUFGa0IsVUFBVTs7RUFFNUIsSUFBQSxDQUFjLENBQUEsSUFBQSxHQUFPLElBQUksQ0FBQyxJQUFMLENBQUEsQ0FBUCxDQUFkO0FBQUEsV0FBQTs7RUFDQSxhQUFBLG1EQUEwQyxFQUFFLENBQUM7RUFFN0MsU0FBQSwwQ0FBMkIsU0FBQyxHQUFEO1dBQ3ZCLE9BQU8sQ0FBQyxPQUFSLFlBQTJCLGFBQUEsQ0FBQSxDQUFlLENBQUM7RUFEcEI7RUFHM0IsSUFBRyxhQUFIO0lBQ0ksSUFBRyx1QkFBSDtNQUNJLElBQUcsU0FBQSxDQUFVLE9BQU8sQ0FBQyxPQUFsQixDQUFIO1FBQ0ksT0FBQSxHQUFVLE9BQU8sQ0FBQyxRQUR0QjtPQUFBLE1BQUE7UUFHSSxPQUFBLEdBQVUsYUFBQSxDQUFBO0FBQ1Y7QUFBQSxhQUFBLFNBQUE7OztVQUFBLE9BQVEsQ0FBQSxDQUFBLENBQVIsR0FBYTtBQUFiLFNBSko7O01BS0EsT0FBTyxDQUFDLE1BQVIsR0FBaUIsT0FBTyxDQUFDLElBQVIsR0FBZSxPQUFPLENBQUMsTUFBUixHQUFpQixRQU5yRDtLQUFBLE1BQUE7TUFRSSxPQUFBLEdBQVUsT0FSZDs7SUFTQSxPQUFPLENBQUMsVUFBUixHQUFxQixPQUFPLENBQUMsUUFBUixJQUFvQjtJQUN6QyxPQUFPLENBQUMsU0FBUixHQUF1QixJQUFJLENBQUMsT0FBTCxDQUFhLE9BQU8sQ0FBQyxVQUFyQjtJQUV2QixJQUFBLENBQUEsQ0FBTyxPQUFBLEtBQVcsTUFBWCxJQUFxQixPQUFPLENBQUMsTUFBN0IsSUFBdUMsT0FBTyxDQUFDLE9BQXRELENBQUE7TUFDSSxNQUFBLEdBQVMsT0FBQSxDQUFRLFFBQVI7TUFDVCxPQUFPLENBQUMsTUFBUixHQUFrQixPQUFBLEdBQWEsSUFBSSxNQUFKLENBQVcsT0FBTyxDQUFDLFVBQVIsSUFBc0IsTUFBakM7TUFDL0IsT0FBTyxDQUFDLE9BQVIsR0FBa0IsUUFBQSxHQUFXLFNBQUMsSUFBRDtlQUFXLE1BQU0sQ0FBQyxLQUFQLENBQWEsSUFBYixFQUFtQixPQUFuQixFQUE0QixJQUE1QjtNQUFYO01BQzdCLE9BQU8sQ0FBQyxRQUFSLEdBQW1CLE9BQU8sQ0FBQztBQUMzQjtBQUFBLFdBQUEsc0NBQUE7O1lBQWlELENBQUEsS0FBVSxPQUFWLElBQUEsQ0FBQSxLQUFtQixXQUFuQixJQUFBLENBQUEsS0FBZ0M7VUFDN0UsUUFBUyxDQUFBLENBQUEsQ0FBVCxHQUFjLE9BQVEsQ0FBQSxDQUFBOztBQUQxQjtNQUdBLFFBQVEsQ0FBQyxLQUFULEdBQWlCLE9BQU8sQ0FBQyxLQUFSLEdBQWdCLE1BQU0sQ0FBQyxnQkFBUCxDQUF3QixPQUFPLENBQUMsR0FBUixDQUFBLENBQXhCO01BQ2pDLFFBQVEsQ0FBQyxPQUFULEdBQW1CLFNBQUMsT0FBRDtlQUFhLE1BQU0sQ0FBQyxnQkFBUCxDQUF3QixPQUF4QixFQUFpQyxPQUFqQztNQUFiLEVBVHZCO0tBYko7O0VBdUJBLENBQUEsR0FBSTtBQUNKLE9BQUEsWUFBQTs7O0lBQUEsQ0FBRSxDQUFBLENBQUEsQ0FBRixHQUFPO0FBQVA7RUFDQSxDQUFDLENBQUMsSUFBRixHQUFTO0VBQ1QsRUFBQSxHQUFLLE9BQUEsQ0FBUSxJQUFSLEVBQWMsQ0FBZDtFQUNMLElBQUcsT0FBQSxLQUFXLE1BQWQ7V0FDSSxFQUFFLENBQUMsZ0JBQUgsQ0FBb0IsRUFBcEIsRUFESjtHQUFBLE1BQUE7V0FHSSxFQUFFLENBQUMsWUFBSCxDQUFnQixFQUFoQixFQUFvQixPQUFwQixFQUhKOztBQW5DVzs7QUE4Q2YsT0FBTyxDQUFDLFFBQVIsR0FBbUIsU0FBQTtTQUFHLE9BQUEsQ0FBUSxZQUFSO0FBQUg7O0FBRW5CLE9BQU8sQ0FBQyxZQUFSLEdBQXVCLFNBQUMsUUFBRCxFQUFXLFNBQVgsRUFBMkIsU0FBM0I7QUFFbkIsTUFBQTs7SUFGOEIsWUFBWTs7O0lBQUksWUFBWTs7RUFFMUQsR0FBQSxHQUFNLEVBQUUsQ0FBQyxZQUFILENBQWdCLFFBQWhCLEVBQTBCLE1BQTFCO0VBRU4sUUFBQSxHQUFjLEdBQUcsQ0FBQyxVQUFKLENBQWUsQ0FBZixDQUFBLEtBQXFCLE1BQXhCLEdBQW9DLEdBQUcsQ0FBQyxTQUFKLENBQWMsQ0FBZCxDQUFwQyxHQUF5RDtBQUVwRTtJQUNJLE1BQUEsR0FBUyxPQUFBLENBQVEsUUFBUixFQUFrQjtNQUN2QixVQUFBLFFBRHVCO01BQ2IsV0FBQSxTQURhO01BQ0YsV0FBQSxTQURFO01BRXZCLFdBQUEsRUFBYSxDQUFDLFFBQUQsQ0FGVTtLQUFsQixFQURiO0dBQUEsYUFBQTtJQUtNO0FBSUYsVUFBTSxPQUFPLENBQUMsaUJBQVIsQ0FBMEIsR0FBMUIsRUFBK0IsUUFBL0IsRUFBeUMsUUFBekMsRUFUVjs7U0FXQTtBQWpCbUI7O0FBeUJ2QixLQUFBLEdBQVEsSUFBSTs7QUFNWixNQUFNLENBQUMsS0FBUCxHQUVJO0VBQUEsR0FBQSxFQUFLLFNBQUE7QUFDRCxRQUFBO0lBQUEsS0FBQSxHQUFRLE1BQU0sQ0FBQyxNQUFPLENBQUEsSUFBQyxDQUFBLEdBQUQsRUFBQTtJQUN0QixJQUFHLEtBQUg7TUFDSyxjQUFELEVBQU0sSUFBQyxDQUFBLGlCQUFQLEVBQWUsSUFBQyxDQUFBO01BQ2hCLE1BQU0sQ0FBQyxVQUFQLEdBQW9CLEtBQUssQ0FBQyxNQUFOLElBQWdCO01BQ3BDLElBQWtDLCtEQUFsQztRQUFBLE9BQU8sQ0FBQyxHQUFSLENBQVksT0FBWixFQUFxQixLQUFyQixFQUFBOztNQUNBLElBQUMsQ0FBQSxRQUFELEdBQVksSUFBQyxDQUFBLE1BQU0sQ0FBQyxXQUp4QjtLQUFBLE1BQUE7TUFNSSxHQUFBLEdBQU0sR0FOVjs7V0FPQTtFQVRDLENBQUw7RUFVQSxRQUFBLEVBQVUsU0FBQyxNQUFEO0lBQ04sTUFBTSxDQUFDLE1BQVAsR0FBZ0I7V0FDaEIsSUFBQyxDQUFBLEdBQUQsR0FBTztFQUZELENBVlY7RUFhQSxhQUFBLEVBQWUsU0FBQTtXQUNYO0VBRFcsQ0FiZjs7O0FBZ0JKLE1BQU0sQ0FBQyxFQUFQLEdBQVksT0FBQSxDQUFRLFNBQVI7O0FBSVosTUFBTSxDQUFDLEVBQUUsQ0FBQyxVQUFWLEdBQXVCLFNBQUMsT0FBRCxFQUFVLEdBQVY7QUFNbkIsTUFBQTtFQU44QixRQUFEO0VBTTVCLDhCQUFELEVBQWE7RUFDWix3QkFBRCxFQUFXLHlCQUFYLEVBQXNCO0VBRXRCLFNBQUE7QUFBWSxZQUFBLEtBQUE7QUFBQSxXQUNILFVBQUEsS0FBYyxNQUFPLENBQUEsTUFBTSxDQUFDLE1BQVAsR0FBZ0IsQ0FBaEIsQ0FEbEI7ZUFFSjtBQUZJLFdBR0gsUUFBQSxLQUFhLFFBQWIsSUFBQSxRQUFBLEtBQXVCLFNBSHBCO2VBSUo7QUFKSSxXQUtILFFBQUEsS0FBYSxZQUFiLElBQUEsUUFBQSxLQUEyQixRQUEzQixJQUFBLFFBQUEsS0FBcUMsVUFBckMsSUFBQSxRQUFBLEtBQWlELFFBQWpELElBQUEsUUFBQSxLQUEyRCxjQUEzRCxJQUFBLFFBQUEsS0FBMkUsT0FBM0UsSUFBQSxRQUFBLEtBQW9GLGFBTGpGO2VBTUosUUFBUSxDQUFDLE9BQVQsQ0FBaUIsU0FBakIsRUFBNEIsRUFBNUIsQ0FBK0IsQ0FBQyxXQUFoQyxDQUFBO0FBTkk7ZUFRSixPQUFPLENBQUMsdUJBQVIsQ0FBZ0MsU0FBaEM7QUFSSTs7U0FjWixPQUFPLENBQUMsZ0JBQVIsQ0FBeUIsYUFBQSxHQUFjLFNBQXZDLEVBQW9ELFFBQXBEO0FBdkJtQjs7QUErQnZCLFlBQUEsR0FBZSxTQUFDLFFBQUQ7QUFLWCxNQUFBO0VBQUEsSUFBRyw0QkFBSDtXQUNJLFVBQVcsQ0FBQSxRQUFBLEVBRGY7R0FBQSxNQUVLLElBQUcsaUNBQUg7V0FDRCxVQUFXLENBQUEsYUFBQSxFQURWO0dBQUEsTUFFQSxJQUFHLHlCQUFIO0lBQ0QsTUFBQSxHQUFTLE9BQUEsQ0FBUSxPQUFRLENBQUEsUUFBQSxDQUFoQixFQUNMO01BQUEsUUFBQSxFQUFVLFFBQVY7TUFDQSxTQUFBLEVBQVcsSUFEWDtLQURLO1dBR1QsTUFBTSxDQUFDLFVBSk47R0FBQSxNQUFBO1dBTUQsS0FOQzs7QUFUTTs7QUEyQmYsS0FBSyxDQUFDLGlCQUFOLEdBQTBCLFNBQUMsR0FBRCxFQUFNLEtBQU47QUFFdEIsTUFBQTtFQUFBLGdCQUFBLEdBQW1CLFNBQUMsUUFBRCxFQUFXLElBQVgsRUFBaUIsTUFBakI7QUFDZixRQUFBO0lBQUEsU0FBQSxHQUFZLFlBQUEsQ0FBYSxRQUFiO0lBQ1osSUFBNEQsaUJBQTVEO01BQUEsTUFBQSxHQUFTLFNBQVMsQ0FBQyxjQUFWLENBQXlCLENBQUMsSUFBQSxHQUFPLENBQVIsRUFBVyxNQUFBLEdBQVMsQ0FBcEIsQ0FBekIsRUFBVDs7SUFDQSxJQUFHLGNBQUg7YUFBZ0IsQ0FBQyxNQUFPLENBQUEsQ0FBQSxDQUFQLEdBQVksQ0FBYixFQUFnQixNQUFPLENBQUEsQ0FBQSxDQUFQLEdBQVksQ0FBNUIsRUFBaEI7S0FBQSxNQUFBO2FBQW9ELEtBQXBEOztFQUhlO0VBS25CLE1BQUE7O0FBQVM7U0FBQSx1Q0FBQTs7TUFDTCxJQUFTLEtBQUssQ0FBQyxXQUFOLENBQUEsQ0FBQSxLQUF1QixPQUFPLENBQUMsR0FBeEM7QUFBQSxjQUFBOzttQkFDQSxhQUFBLEdBQWEsQ0FBQyxvQkFBQSxDQUFxQixLQUFyQixFQUE0QixnQkFBNUIsQ0FBRDtBQUZSOzs7U0FJUCxDQUFDLEdBQUcsQ0FBQyxRQUFKLENBQUEsQ0FBRCxDQUFBLEdBQWdCLElBQWhCLEdBQW1CLENBQUMsTUFBTSxDQUFDLElBQVAsQ0FBWSxJQUFaLENBQUQsQ0FBbkIsR0FBcUM7QUFYakI7O0FBZ0IxQixvQkFBQSxHQUF1QixTQUFDLEtBQUQsRUFBUSxnQkFBUjtBQUVuQixNQUFBO0VBQUEsUUFBQSxHQUFXO0VBQ1gsWUFBQSxHQUFlO0VBRWYsSUFBRyxLQUFLLENBQUMsUUFBTixDQUFBLENBQUg7SUFDSSxZQUFBLEdBQWUsU0FEbkI7R0FBQSxNQUFBO0lBR0ksSUFBRyxLQUFLLENBQUMsTUFBTixDQUFBLENBQUg7TUFDSSxRQUFBLEdBQVcsS0FBSyxDQUFDLHdCQUFOLENBQUE7TUFDWCxJQUFBLENBQW1ELFFBQW5EO1FBQUEsWUFBQSxHQUFpQixDQUFDLEtBQUssQ0FBQyxhQUFOLENBQUEsQ0FBRCxDQUFBLEdBQXVCLEtBQXhDO09BRko7S0FBQSxNQUFBO01BSUksUUFBQSxHQUFXLEtBQUssQ0FBQyxXQUFOLENBQUEsRUFKZjs7SUFNQSxhQUFBLFdBQWE7SUFFYixJQUFBLEdBQU8sS0FBSyxDQUFDLGFBQU4sQ0FBQTtJQUNQLE1BQUEsR0FBUyxLQUFLLENBQUMsZUFBTixDQUFBO0lBR1QsTUFBQSxHQUFTLGdCQUFBLENBQWlCLFFBQWpCLEVBQTJCLElBQTNCLEVBQWlDLE1BQWpDO0lBQ1QsWUFBQSxHQUNPLE1BQUgsR0FDTyxRQUFELEdBQVUsR0FBVixHQUFhLE1BQU8sQ0FBQSxDQUFBLENBQXBCLEdBQXVCLEdBQXZCLEdBQTBCLE1BQU8sQ0FBQSxDQUFBLENBRHZDLEdBR08sUUFBRCxHQUFVLEdBQVYsR0FBYSxJQUFiLEdBQWtCLEdBQWxCLEdBQXFCLE9BcEJuQzs7RUFzQkEsWUFBQSxHQUFlLEtBQUssQ0FBQyxlQUFOLENBQUE7RUFDZixhQUFBLEdBQWdCLEtBQUssQ0FBQyxhQUFOLENBQUE7RUFDaEIsWUFBQSxHQUFlLENBQUksQ0FBQyxLQUFLLENBQUMsVUFBTixDQUFBLENBQUEsSUFBc0IsYUFBdkI7RUFFbkIsSUFBRyxZQUFIO0lBQ0ksVUFBQSxHQUFhLEtBQUssQ0FBQyxhQUFOLENBQUE7SUFDYixRQUFBLEdBQVcsS0FBSyxDQUFDLFdBQU4sQ0FBQTtJQUVYLElBQUcsWUFBSDtNQUNJLEVBQUEsR0FBSyxFQUFBLEdBQUs7TUFDVixJQUFHLFFBQUEsSUFBYSxZQUFZLENBQUMsT0FBYixDQUFxQixRQUFyQixDQUFoQjtRQUNJLEVBQUEsR0FBUSxRQUFELEdBQVUsSUFEckI7O01BRUEsSUFBRyxVQUFBLElBQWUsWUFBWSxDQUFDLE9BQWIsQ0FBcUIsR0FBQSxHQUFJLFVBQXpCLENBQUEsS0FBMEMsWUFBWSxDQUFDLE1BQWIsR0FBc0IsVUFBVSxDQUFDLE1BQWpDLEdBQTBDLENBQXRHO1FBQ0ksRUFBQSxHQUFLLE9BQUEsR0FBUSxVQUFSLEdBQW1CLElBRDVCOzthQUdBLEVBQUEsR0FBRyxFQUFILEdBQVEsWUFBUixHQUF1QixFQUF2QixHQUEwQixJQUExQixHQUE4QixZQUE5QixHQUEyQyxJQVAvQztLQUFBLE1BQUE7YUFTTyxRQUFELEdBQVUsR0FBVixHQUFZLENBQUMsVUFBQSxJQUFjLGFBQWYsQ0FBWixHQUF5QyxJQUF6QyxHQUE2QyxZQUE3QyxHQUEwRCxJQVRoRTtLQUpKO0dBQUEsTUFjSyxJQUFHLGFBQUg7V0FDRCxNQUFBLEdBQU0sQ0FBQyxZQUFBLElBQWdCLGFBQWpCLENBQU4sR0FBcUMsSUFBckMsR0FBeUMsWUFBekMsR0FBc0QsSUFEckQ7R0FBQSxNQUVBLElBQUcsWUFBSDtXQUNFLFlBQUQsR0FBYyxJQUFkLEdBQWtCLFlBQWxCLEdBQStCLElBRGhDO0dBQUEsTUFBQTtXQUdELGFBSEM7O0FBL0NjIiwic291cmNlc0NvbnRlbnQiOlsiIyMjXG4wMDAgICAwMDAgICAwMDAwMDAwICAgMDAwMDAwMDAgIDAwMDAwMDAwICAwMDAwMDAwMCAgMDAwMDAwMDAgIFxuMDAwICAwMDAgICAwMDAgICAwMDAgIDAwMCAgICAgICAwMDAgICAgICAgMDAwICAgICAgIDAwMCAgICAgICBcbjAwMDAwMDAgICAgMDAwICAgMDAwICAwMDAwMDAgICAgMDAwMDAwICAgIDAwMDAwMDAgICAwMDAwMDAwICAgXG4wMDAgIDAwMCAgIDAwMCAgIDAwMCAgMDAwICAgICAgIDAwMCAgICAgICAwMDAgICAgICAgMDAwICAgICAgIFxuMDAwICAgMDAwICAgMDAwMDAwMCAgIDAwMCAgICAgICAwMDAgICAgICAgMDAwMDAwMDAgIDAwMDAwMDAwICBcbiMjI1xuXG4jIFRoaXMgbW9kdWxlIGNvbnRhaW5zIHRoZSBtYWluIGVudHJ5IGZ1bmN0aW9ucyBmb3IgdG9rZW5pemluZywgXG4jIHBhcnNpbmcsIGFuZCBjb21waWxpbmcga29mZmVlIGludG8gSmF2YVNjcmlwdC5cblxuZnMgICAgICAgID0gcmVxdWlyZSAnZnMnXG52bSAgICAgICAgPSByZXF1aXJlICd2bSdcbnBhdGggICAgICA9IHJlcXVpcmUgJ3BhdGgnXG57TGV4ZXJ9ICAgPSByZXF1aXJlICcuL2xleGVyJ1xue3BhcnNlcn0gID0gcmVxdWlyZSAnLi9wYXJzZXInXG5oZWxwZXJzICAgPSByZXF1aXJlICcuL2hlbHBlcnMnXG5Tb3VyY2VNYXAgPSByZXF1aXJlICcuL3NvdXJjZW1hcCdcbnBrZyAgICAgICA9IHJlcXVpcmUgJy4uL3BhY2thZ2UuanNvbidcblxuZXhwb3J0cy5WRVJTSU9OID0gcGtnLnZlcnNpb24gIyBUaGUgY3VycmVudCB2ZXJzaW9uIG51bWJlci5cblxuZXhwb3J0cy5GSUxFX0VYVEVOU0lPTlMgPSBGSUxFX0VYVEVOU0lPTlMgPSBbJy5jb2ZmZWUnLCAnLmtvZmZlZSddXG5cbmV4cG9ydHMuaGVscGVycyA9IGhlbHBlcnNcbiAgICBcbmJhc2U2NGVuY29kZSA9IChzcmMpIC0+XG4gICAgXG4gICAgc3dpdGNoXG4gICAgICAgIHdoZW4gdHlwZW9mIEJ1ZmZlciBpcyAnZnVuY3Rpb24nXG4gICAgICAgICAgICBCdWZmZXIuZnJvbShzcmMpLnRvU3RyaW5nKCdiYXNlNjQnKVxuICAgICAgICB3aGVuIHR5cGVvZiBidG9hIGlzICdmdW5jdGlvbidcbiAgICAgICAgICAgICMgVGhlIGNvbnRlbnRzIG9mIGEgYDxzY3JpcHQ+YCBibG9jayBhcmUgZW5jb2RlZCB2aWEgVVRGLTE2LCBzbyBpZiBhbnkgZXh0ZW5kZWRcbiAgICAgICAgICAgICMgY2hhcmFjdGVycyBhcmUgdXNlZCBpbiB0aGUgYmxvY2ssIGJ0b2Egd2lsbCBmYWlsIGFzIGl0IG1heGVzIG91dCBhdCBVVEYtOC5cbiAgICAgICAgICAgICMgU2VlIGh0dHBzOi8vZGV2ZWxvcGVyLm1vemlsbGEub3JnL2VuLVVTL2RvY3MvV2ViL0FQSS9XaW5kb3dCYXNlNjQvQmFzZTY0X2VuY29kaW5nX2FuZF9kZWNvZGluZyNUaGVfVW5pY29kZV9Qcm9ibGVtXG4gICAgICAgICAgICAjIGZvciB0aGUgZ29yeSBkZXRhaWxzLCBhbmQgZm9yIHRoZSBzb2x1dGlvbiBpbXBsZW1lbnRlZCBoZXJlLlxuICAgICAgICAgICAgYnRvYSBlbmNvZGVVUklDb21wb25lbnQoc3JjKS5yZXBsYWNlIC8lKFswLTlBLUZdezJ9KS9nLCAobWF0Y2gsIHAxKSAtPlxuICAgICAgICAgICAgICAgIFN0cmluZy5mcm9tQ2hhckNvZGUgJzB4JyArIHAxXG4gICAgICAgIGVsc2VcbiAgICAgICAgICAgIHRocm93IG5ldyBFcnJvcignVW5hYmxlIHRvIGJhc2U2NCBlbmNvZGUgaW5saW5lIHNvdXJjZW1hcC4nKVxuXG4jIFdyYXBwZXIgdG8gYWRkIHNvdXJjZSBmaWxlIGluZm9ybWF0aW9uIHRvIFN5bnRheEVycm9ycyB0aHJvd24gYnkgdGhlIGxleGVyL3BhcnNlci9jb21waWxlci5cblxud2l0aFByZXR0eUVycm9ycyA9IChmbikgLT5cbiAgICBcbiAgICAoY29kZSwgb3B0aW9ucyA9IHt9KSAtPlxuICAgICAgICB0cnlcbiAgICAgICAgICAgIGZuLmNhbGwgQCwgY29kZSwgb3B0aW9uc1xuICAgICAgICBjYXRjaCBlcnJcbiAgICAgICAgICAgIGlmIHR5cGVvZiBjb2RlICE9ICdzdHJpbmcnICMgU3VwcG9ydCBgS29mZmVlLm5vZGVzKHRva2VucylgLlxuICAgICAgICAgICAgICAgIHRocm93IG5ldyBFcnJvcihlcnIudG9TdHJpbmcoKSlcbiAgICAgICAgICAgIGVsc2VcbiAgICAgICAgICAgICAgICB0aHJvdyBoZWxwZXJzLnVwZGF0ZVN5bnRheEVycm9yIGVyciwgY29kZSwgb3B0aW9ucy5maWxlbmFtZVxuXG4jIEZvciBlYWNoIGNvbXBpbGVkIGZpbGUsIHNhdmUgaXRzIHNvdXJjZSBpbiBtZW1vcnkgaW4gY2FzZSB3ZSBuZWVkIHRvXG4jIHJlY29tcGlsZSBpdCBsYXRlci4gV2UgbWlnaHQgbmVlZCB0byByZWNvbXBpbGUgaWYgdGhlIGZpcnN0IGNvbXBpbGF0aW9uXG4jIGRpZG7igJl0IGNyZWF0ZSBhIHNvdXJjZSBtYXAgKGZhc3RlcikgYnV0IHNvbWV0aGluZyB3ZW50IHdyb25nIGFuZCB3ZSBuZWVkXG4jIGEgc3RhY2sgdHJhY2UuIEFzc3VtaW5nIHRoYXQgbW9zdCBvZiB0aGUgdGltZSwgY29kZSBpc27igJl0IHRocm93aW5nXG4jIGV4Y2VwdGlvbnMsIGl04oCZcyBwcm9iYWJseSBtb3JlIGVmZmljaWVudCB0byBjb21waWxlIHR3aWNlIG9ubHkgd2hlbiB3ZVxuIyBuZWVkIGEgc3RhY2sgdHJhY2UsIHJhdGhlciB0aGFuIGFsd2F5cyBnZW5lcmF0aW5nIGEgc291cmNlIG1hcCBldmVuIHdoZW5cbiMgaXTigJlzIG5vdCBsaWtlbHkgdG8gYmUgdXNlZC4gU2F2ZSBpbiBmb3JtIG9mIGBmaWxlbmFtZWA6IGAoc291cmNlKWBcblxuc291cmNlcyA9IHt9XG5cbiMgQWxzbyBzYXZlIHNvdXJjZSBtYXBzIGlmIGdlbmVyYXRlZCwgaW4gZm9ybSBvZiBgZmlsZW5hbWVgOiBgKHNvdXJjZSBtYXApYC5cblxuc291cmNlTWFwcyA9IHt9XG5cbiMgIDAwMDAwMDAgICAwMDAwMDAwICAgMDAgICAgIDAwICAwMDAwMDAwMCAgIDAwMCAgMDAwICAgICAgMDAwMDAwMDAgIFxuIyAwMDAgICAgICAgMDAwICAgMDAwICAwMDAgICAwMDAgIDAwMCAgIDAwMCAgMDAwICAwMDAgICAgICAwMDAgICAgICAgXG4jIDAwMCAgICAgICAwMDAgICAwMDAgIDAwMDAwMDAwMCAgMDAwMDAwMDAgICAwMDAgIDAwMCAgICAgIDAwMDAwMDAgICBcbiMgMDAwICAgICAgIDAwMCAgIDAwMCAgMDAwIDAgMDAwICAwMDAgICAgICAgIDAwMCAgMDAwICAgICAgMDAwICAgICAgIFxuIyAgMDAwMDAwMCAgIDAwMDAwMDAgICAwMDAgICAwMDAgIDAwMCAgICAgICAgMDAwICAwMDAwMDAwICAwMDAwMDAwMCAgXG5cbiMgQ29tcGlsZSBrb2ZmZWUgdG8gSmF2YVNjcmlwdCwgdXNpbmcgdGhlIEppc29uIGNvbXBpbGVyLlxuI1xuIyBJZiBgb3B0aW9ucy5zb3VyY2VNYXBgIGlzIHNwZWNpZmllZCwgdGhlbiBgb3B0aW9ucy5maWxlbmFtZWAgbXVzdCBhbHNvIGJlXG4jIHNwZWNpZmllZC4gQWxsIG9wdGlvbnMgdGhhdCBjYW4gYmUgcGFzc2VkIHRvIGBTb3VyY2VNYXAjZ2VuZXJhdGVgIG1heSBhbHNvXG4jIGJlIHBhc3NlZCBoZXJlLlxuI1xuIyBUaGlzIHJldHVybnMgYSBqYXZhc2NyaXB0IHN0cmluZywgdW5sZXNzIGBvcHRpb25zLnNvdXJjZU1hcGAgaXMgcGFzc2VkLFxuIyBpbiB3aGljaCBjYXNlIHRoaXMgcmV0dXJucyBhIGB7anMsIHYzU291cmNlTWFwLCBzb3VyY2VNYXB9YFxuIyBvYmplY3QsIHdoZXJlIHNvdXJjZU1hcCBpcyBhIHNvdXJjZW1hcC5jb2ZmZWUjU291cmNlTWFwIG9iamVjdCwgaGFuZHkgZm9yXG4jIGRvaW5nIHByb2dyYW1tYXRpYyBsb29rdXBzLlxuXG5leHBvcnRzLmNvbXBpbGUgPSBjb21waWxlID0gd2l0aFByZXR0eUVycm9ycyAoY29kZSwgb3B0aW9ucykgLT5cbiAgICBcbiAgICB7bWVyZ2UsIGV4dGVuZH0gPSBoZWxwZXJzXG4gICAgb3B0aW9ucyA9IGV4dGVuZCB7fSwgb3B0aW9uc1xuICAgIFxuICAgICMgQWx3YXlzIGdlbmVyYXRlIGEgc291cmNlIG1hcCBpZiBubyBmaWxlbmFtZSBpcyBwYXNzZWQgaW4sIHNpbmNlIHdpdGhvdXQgYVxuICAgICMgYSBmaWxlbmFtZSB3ZSBoYXZlIG5vIHdheSB0byByZXRyaWV2ZSB0aGlzIHNvdXJjZSBsYXRlciBpbiB0aGUgZXZlbnQgdGhhdFxuICAgICMgd2UgbmVlZCB0byByZWNvbXBpbGUgaXQgdG8gZ2V0IGEgc291cmNlIG1hcCBmb3IgYHByZXBhcmVTdGFja1RyYWNlYC5cbiAgICAgICAgXG4gICAgZ2VuZXJhdGVTb3VyY2VNYXAgPSBvcHRpb25zLnNvdXJjZU1hcCBvciBvcHRpb25zLmlubGluZU1hcCBvciBub3Qgb3B0aW9ucy5maWxlbmFtZT9cbiAgICBmaWxlbmFtZSA9IG9wdGlvbnMuZmlsZW5hbWUgb3IgJzxhbm9ueW1vdXM+J1xuXG4gICAgc291cmNlc1tmaWxlbmFtZV0gPSBjb2RlXG4gICAgbWFwID0gbmV3IFNvdXJjZU1hcCBpZiBnZW5lcmF0ZVNvdXJjZU1hcFxuXG4gICAgdG9rZW5zID0gbGV4ZXIudG9rZW5pemUgY29kZSwgb3B0aW9uc1xuXG4gICAgIyBQYXNzIGEgbGlzdCBvZiByZWZlcmVuY2VkIHZhcmlhYmxlcywgc28gdGhhdCBnZW5lcmF0ZWQgdmFyaWFibGVzIHdvbid0IGdldCB0aGUgc2FtZSBuYW1lLlxuICAgIFxuICAgIG9wdGlvbnMucmVmZXJlbmNlZFZhcnMgPSAoXG4gICAgICAgIHRva2VuWzFdIGZvciB0b2tlbiBpbiB0b2tlbnMgd2hlbiB0b2tlblswXSBpcyAnSURFTlRJRklFUidcbiAgICApXG5cbiAgICAjIENoZWNrIGZvciBpbXBvcnQgb3IgZXhwb3J0OyBpZiBmb3VuZCwgZm9yY2UgYmFyZSBtb2RlLlxuICAgICAgICBcbiAgICB1bmxlc3Mgb3B0aW9ucy5iYXJlPyBhbmQgb3B0aW9ucy5iYXJlIGlzIHllc1xuICAgICAgICBmb3IgdG9rZW4gaW4gdG9rZW5zXG4gICAgICAgICAgICBpZiB0b2tlblswXSBpbiBbJ0lNUE9SVCcsICdFWFBPUlQnXVxuICAgICAgICAgICAgICAgIG9wdGlvbnMuYmFyZSA9IHllc1xuICAgICAgICAgICAgICAgIGJyZWFrXG5cbiAgICBmcmFnbWVudHMgPSBwYXJzZXIucGFyc2UodG9rZW5zKS5jb21waWxlVG9GcmFnbWVudHMgb3B0aW9uc1xuXG4gICAgY3VycmVudExpbmUgPSAwXG4gICAgY3VycmVudExpbmUgKz0gMSBpZiBvcHRpb25zLmhlYWRlclxuICAgIGN1cnJlbnRMaW5lICs9IDEgaWYgb3B0aW9ucy5zaGlmdExpbmVcbiAgICBjdXJyZW50Q29sdW1uID0gMFxuICAgIGpzID0gXCJcIlxuICAgIFxuICAgIGZvciBmcmFnbWVudCBpbiBmcmFnbWVudHNcbiAgICAgICAgIyBVcGRhdGUgdGhlIHNvdXJjZW1hcCB3aXRoIGRhdGEgZnJvbSBlYWNoIGZyYWdtZW50LlxuICAgICAgICBpZiBnZW5lcmF0ZVNvdXJjZU1hcFxuICAgICAgICAgICAgIyBEbyBub3QgaW5jbHVkZSBlbXB0eSwgd2hpdGVzcGFjZSwgb3Igc2VtaWNvbG9uLW9ubHkgZnJhZ21lbnRzLlxuICAgICAgICAgICAgaWYgZnJhZ21lbnQubG9jYXRpb25EYXRhIGFuZCBub3QgL15bO1xcc10qJC8udGVzdCBmcmFnbWVudC5jb2RlXG4gICAgICAgICAgICAgICAgbWFwLmFkZChcbiAgICAgICAgICAgICAgICAgICAgW2ZyYWdtZW50LmxvY2F0aW9uRGF0YS5maXJzdF9saW5lLCBmcmFnbWVudC5sb2NhdGlvbkRhdGEuZmlyc3RfY29sdW1uXVxuICAgICAgICAgICAgICAgICAgICBbY3VycmVudExpbmUsIGN1cnJlbnRDb2x1bW5dXG4gICAgICAgICAgICAgICAgICAgIHtub1JlcGxhY2U6IHRydWV9KVxuICAgICAgICAgICAgbmV3TGluZXMgPSBoZWxwZXJzLmNvdW50IGZyYWdtZW50LmNvZGUsIFwiXFxuXCJcbiAgICAgICAgICAgIGN1cnJlbnRMaW5lICs9IG5ld0xpbmVzXG4gICAgICAgICAgICBpZiBuZXdMaW5lc1xuICAgICAgICAgICAgICAgIGN1cnJlbnRDb2x1bW4gPSBmcmFnbWVudC5jb2RlLmxlbmd0aCAtIChmcmFnbWVudC5jb2RlLmxhc3RJbmRleE9mKFwiXFxuXCIpICsgMSlcbiAgICAgICAgICAgIGVsc2VcbiAgICAgICAgICAgICAgICBjdXJyZW50Q29sdW1uICs9IGZyYWdtZW50LmNvZGUubGVuZ3RoXG5cbiAgICAgICAgIyBDb3B5IHRoZSBjb2RlIGZyb20gZWFjaCBmcmFnbWVudCBpbnRvIHRoZSBmaW5hbCBKYXZhU2NyaXB0LlxuICAgICAgICBqcyArPSBmcmFnbWVudC5jb2RlXG5cbiAgICBpZiBvcHRpb25zLmhlYWRlclxuICAgICAgICBoZWFkZXIgPSBcIkdlbmVyYXRlZCBieSBrb2ZmZWUgI3tAVkVSU0lPTn1cIlxuICAgICAgICBqcyA9IFwiLy8gI3toZWFkZXJ9XFxuI3tqc31cIlxuXG4gICAgaWYgZ2VuZXJhdGVTb3VyY2VNYXBcbiAgICAgICAgdjNTb3VyY2VNYXAgPSBtYXAuZ2VuZXJhdGUob3B0aW9ucywgY29kZSlcbiAgICAgICAgc291cmNlTWFwc1tmaWxlbmFtZV0gPSBtYXBcblxuICAgIGlmIG9wdGlvbnMuaW5saW5lTWFwXG4gICAgICAgIGVuY29kZWQgPSBiYXNlNjRlbmNvZGUgSlNPTi5zdHJpbmdpZnkgdjNTb3VyY2VNYXBcbiAgICAgICAgc291cmNlTWFwRGF0YVVSSSA9IFwiLy8jIHNvdXJjZU1hcHBpbmdVUkw9ZGF0YTphcHBsaWNhdGlvbi9qc29uO2Jhc2U2NCwje2VuY29kZWR9XCJcbiAgICAgICAgc291cmNlVVJMID0gXCIvLyMgc291cmNlVVJMPSN7b3B0aW9ucy5maWxlbmFtZSA/ICdrb2ZmZWUnfVwiXG4gICAgICAgIGpzID0gXCIje2pzfVxcbiN7c291cmNlTWFwRGF0YVVSSX1cXG4je3NvdXJjZVVSTH1cIlxuXG4gICAgaWYgb3B0aW9ucy5zb3VyY2VNYXBcbiAgICAgICAge1xuICAgICAgICAgICAganNcbiAgICAgICAgICAgIHNvdXJjZU1hcDogbWFwXG4gICAgICAgICAgICB2M1NvdXJjZU1hcDogSlNPTi5zdHJpbmdpZnkgdjNTb3VyY2VNYXAsIG51bGwsIDJcbiAgICAgICAgfVxuICAgIGVsc2VcbiAgICAgICAganNcblxuIyAwMDAwMDAwMDAgICAwMDAwMDAwICAgMDAwICAgMDAwICAwMDAwMDAwMCAgMDAwICAgMDAwICAgMDAwMDAwMCAgXG4jICAgIDAwMCAgICAgMDAwICAgMDAwICAwMDAgIDAwMCAgIDAwMCAgICAgICAwMDAwICAwMDAgIDAwMCAgICAgICBcbiMgICAgMDAwICAgICAwMDAgICAwMDAgIDAwMDAwMDAgICAgMDAwMDAwMCAgIDAwMCAwIDAwMCAgMDAwMDAwMCAgIFxuIyAgICAwMDAgICAgIDAwMCAgIDAwMCAgMDAwICAwMDAgICAwMDAgICAgICAgMDAwICAwMDAwICAgICAgIDAwMCAgXG4jICAgIDAwMCAgICAgIDAwMDAwMDAgICAwMDAgICAwMDAgIDAwMDAwMDAwICAwMDAgICAwMDAgIDAwMDAwMDAgICBcblxuIyBUb2tlbml6ZSBhIHN0cmluZyBvZiBrb2ZmZWUgY29kZSwgYW5kIHJldHVybiB0aGUgYXJyYXkgb2YgdG9rZW5zLlxuXG5leHBvcnRzLnRva2VucyA9IHdpdGhQcmV0dHlFcnJvcnMgKGNvZGUsIG9wdGlvbnMpIC0+XG4gICAgbGV4ZXIudG9rZW5pemUgY29kZSwgb3B0aW9uc1xuXG4jIDAwMCAgIDAwMCAgIDAwMDAwMDAgICAwMDAwMDAwICAgIDAwMDAwMDAwICAgMDAwMDAwMCAgXG4jIDAwMDAgIDAwMCAgMDAwICAgMDAwICAwMDAgICAwMDAgIDAwMCAgICAgICAwMDAgICAgICAgXG4jIDAwMCAwIDAwMCAgMDAwICAgMDAwICAwMDAgICAwMDAgIDAwMDAwMDAgICAwMDAwMDAwICAgXG4jIDAwMCAgMDAwMCAgMDAwICAgMDAwICAwMDAgICAwMDAgIDAwMCAgICAgICAgICAgIDAwMCAgXG4jIDAwMCAgIDAwMCAgIDAwMDAwMDAgICAwMDAwMDAwICAgIDAwMDAwMDAwICAwMDAwMDAwICAgXG5cbiMgUGFyc2UgYSBzdHJpbmcgb2YgS29mZmVlIGNvZGUgb3IgYW4gYXJyYXkgb2YgbGV4ZWQgdG9rZW5zLCBhbmQgcmV0dXJuIHRoZSBBU1QuIFxuIyBZb3UgY2FuIHRoZW4gY29tcGlsZSBpdCBieSBjYWxsaW5nIGAuY29tcGlsZSgpYCBvbiB0aGUgcm9vdCwgb3IgdHJhdmVyc2UgaXQgYnkgdXNpbmcgYC50cmF2ZXJzZUNoaWxkcmVuKClgIHdpdGggYSBjYWxsYmFjay5cblxuZXhwb3J0cy5ub2RlcyA9IHdpdGhQcmV0dHlFcnJvcnMgKHNvdXJjZSwgb3B0aW9ucykgLT5cbiAgICBpZiB0eXBlb2Ygc291cmNlIGlzICdzdHJpbmcnXG4gICAgICAgIHBhcnNlci5wYXJzZSBsZXhlci50b2tlbml6ZSBzb3VyY2UsIG9wdGlvbnNcbiAgICBlbHNlXG4gICAgICAgIHBhcnNlci5wYXJzZSBzb3VyY2VcblxuIyAwMDAwMDAwMCAgIDAwMCAgIDAwMCAgMDAwICAgMDAwICBcbiMgMDAwICAgMDAwICAwMDAgICAwMDAgIDAwMDAgIDAwMCAgXG4jIDAwMDAwMDAgICAgMDAwICAgMDAwICAwMDAgMCAwMDAgIFxuIyAwMDAgICAwMDAgIDAwMCAgIDAwMCAgMDAwICAwMDAwICBcbiMgMDAwICAgMDAwICAgMDAwMDAwMCAgIDAwMCAgIDAwMCAgXG5cbiMgQ29tcGlsZSBhbmQgZXhlY3V0ZSBhIHN0cmluZyBvZiBrb2ZmZWUsIGNvcnJlY3RseSBzZXR0aW5nIGBfX2ZpbGVuYW1lYCwgYF9fZGlybmFtZWAsIGFuZCByZWxhdGl2ZSBgcmVxdWlyZSgpYC5cblxuZXhwb3J0cy5ydW4gPSAoY29kZSwgb3B0aW9ucyA9IHt9KSAtPlxuICAgIFxuICAgIG1haW5Nb2R1bGUgPSByZXF1aXJlLm1haW5cblxuICAgICMgU2V0IHRoZSBmaWxlbmFtZS5cbiAgICBtYWluTW9kdWxlLmZpbGVuYW1lID0gcHJvY2Vzcy5hcmd2WzFdID1cbiAgICAgICAgaWYgb3B0aW9ucy5maWxlbmFtZSB0aGVuIGZzLnJlYWxwYXRoU3luYyhvcHRpb25zLmZpbGVuYW1lKSBlbHNlICc8YW5vbnltb3VzPidcblxuICAgICMgQ2xlYXIgdGhlIG1vZHVsZSBjYWNoZS5cbiAgICBtYWluTW9kdWxlLm1vZHVsZUNhY2hlIGFuZD0ge31cblxuICAgICMgQXNzaWduIHBhdGhzIGZvciBub2RlX21vZHVsZXMgbG9hZGluZ1xuICAgIGRpciA9IGlmIG9wdGlvbnMuZmlsZW5hbWU/XG4gICAgICAgIHBhdGguZGlybmFtZSBmcy5yZWFscGF0aFN5bmMgb3B0aW9ucy5maWxlbmFtZVxuICAgIGVsc2VcbiAgICAgICAgZnMucmVhbHBhdGhTeW5jICcuJ1xuICAgIG1haW5Nb2R1bGUucGF0aHMgPSByZXF1aXJlKCdtb2R1bGUnKS5fbm9kZU1vZHVsZVBhdGhzIGRpclxuXG4gICAgIyBDb21waWxlLlxuICAgIGlmIG5vdCBoZWxwZXJzLmlzQ29mZmVlKG1haW5Nb2R1bGUuZmlsZW5hbWUpIG9yIHJlcXVpcmUuZXh0ZW5zaW9uc1xuICAgICAgICBhbnN3ZXIgPSBjb21waWxlIGNvZGUsIG9wdGlvbnNcbiAgICAgICAgY29kZSA9IGFuc3dlci5qcyA/IGFuc3dlclxuXG4gICAgbWFpbk1vZHVsZS5fY29tcGlsZSBjb2RlLCBtYWluTW9kdWxlLmZpbGVuYW1lXG5cbiMgMDAwMDAwMDAgIDAwMCAgIDAwMCAgIDAwMDAwMDAgICAwMDAgICAgICBcbiMgMDAwICAgICAgIDAwMCAgIDAwMCAgMDAwICAgMDAwICAwMDAgICAgICBcbiMgMDAwMDAwMCAgICAwMDAgMDAwICAgMDAwMDAwMDAwICAwMDAgICAgICBcbiMgMDAwICAgICAgICAgIDAwMCAgICAgMDAwICAgMDAwICAwMDAgICAgICBcbiMgMDAwMDAwMDAgICAgICAwICAgICAgMDAwICAgMDAwICAwMDAwMDAwICBcblxuIyBDb21waWxlIGFuZCBldmFsdWF0ZSBhIHN0cmluZyBpbiBhIE5vZGUuanMtbGlrZSBlbnZpcm9ubWVudC4gVGhlIFJFUEwgdXNlcyB0aGlzIHRvIHJ1biB0aGUgaW5wdXQuXG5cbmV4cG9ydHMuZXZhbCA9IChjb2RlLCBvcHRpb25zID0ge30pIC0+XG4gICAgXG4gICAgcmV0dXJuIHVubGVzcyBjb2RlID0gY29kZS50cmltKClcbiAgICBjcmVhdGVDb250ZXh0ID0gdm0uU2NyaXB0LmNyZWF0ZUNvbnRleHQgPyB2bS5jcmVhdGVDb250ZXh0XG5cbiAgICBpc0NvbnRleHQgPSB2bS5pc0NvbnRleHQgPyAoY3R4KSAtPlxuICAgICAgICBvcHRpb25zLnNhbmRib3ggaW5zdGFuY2VvZiBjcmVhdGVDb250ZXh0KCkuY29uc3RydWN0b3JcblxuICAgIGlmIGNyZWF0ZUNvbnRleHRcbiAgICAgICAgaWYgb3B0aW9ucy5zYW5kYm94P1xuICAgICAgICAgICAgaWYgaXNDb250ZXh0IG9wdGlvbnMuc2FuZGJveFxuICAgICAgICAgICAgICAgIHNhbmRib3ggPSBvcHRpb25zLnNhbmRib3hcbiAgICAgICAgICAgIGVsc2VcbiAgICAgICAgICAgICAgICBzYW5kYm94ID0gY3JlYXRlQ29udGV4dCgpXG4gICAgICAgICAgICAgICAgc2FuZGJveFtrXSA9IHYgZm9yIG93biBrLCB2IG9mIG9wdGlvbnMuc2FuZGJveFxuICAgICAgICAgICAgc2FuZGJveC5nbG9iYWwgPSBzYW5kYm94LnJvb3QgPSBzYW5kYm94LkdMT0JBTCA9IHNhbmRib3hcbiAgICAgICAgZWxzZVxuICAgICAgICAgICAgc2FuZGJveCA9IGdsb2JhbFxuICAgICAgICBzYW5kYm94Ll9fZmlsZW5hbWUgPSBvcHRpb25zLmZpbGVuYW1lIHx8ICdldmFsJ1xuICAgICAgICBzYW5kYm94Ll9fZGlybmFtZSAgICA9IHBhdGguZGlybmFtZSBzYW5kYm94Ll9fZmlsZW5hbWVcbiAgICAgICAgIyBkZWZpbmUgbW9kdWxlL3JlcXVpcmUgb25seSBpZiB0aGV5IGNob3NlIG5vdCB0byBzcGVjaWZ5IHRoZWlyIG93blxuICAgICAgICB1bmxlc3Mgc2FuZGJveCAhPSBnbG9iYWwgb3Igc2FuZGJveC5tb2R1bGUgb3Igc2FuZGJveC5yZXF1aXJlXG4gICAgICAgICAgICBNb2R1bGUgPSByZXF1aXJlICdtb2R1bGUnXG4gICAgICAgICAgICBzYW5kYm94Lm1vZHVsZSAgPSBfbW9kdWxlICAgID0gbmV3IE1vZHVsZShvcHRpb25zLm1vZHVsZW5hbWUgfHwgJ2V2YWwnKVxuICAgICAgICAgICAgc2FuZGJveC5yZXF1aXJlID0gX3JlcXVpcmUgPSAocGF0aCkgLT4gIE1vZHVsZS5fbG9hZCBwYXRoLCBfbW9kdWxlLCB0cnVlXG4gICAgICAgICAgICBfbW9kdWxlLmZpbGVuYW1lID0gc2FuZGJveC5fX2ZpbGVuYW1lXG4gICAgICAgICAgICBmb3IgciBpbiBPYmplY3QuZ2V0T3duUHJvcGVydHlOYW1lcyByZXF1aXJlIHdoZW4gciBub3QgaW4gWydwYXRocycsICdhcmd1bWVudHMnLCAnY2FsbGVyJ11cbiAgICAgICAgICAgICAgICBfcmVxdWlyZVtyXSA9IHJlcXVpcmVbcl1cbiAgICAgICAgICAgICMgdXNlIHRoZSBzYW1lIGhhY2sgbm9kZSBjdXJyZW50bHkgdXNlcyBmb3IgdGhlaXIgb3duIFJFUExcbiAgICAgICAgICAgIF9yZXF1aXJlLnBhdGhzID0gX21vZHVsZS5wYXRocyA9IE1vZHVsZS5fbm9kZU1vZHVsZVBhdGhzIHByb2Nlc3MuY3dkKClcbiAgICAgICAgICAgIF9yZXF1aXJlLnJlc29sdmUgPSAocmVxdWVzdCkgLT4gTW9kdWxlLl9yZXNvbHZlRmlsZW5hbWUgcmVxdWVzdCwgX21vZHVsZVxuICAgIG8gPSB7fVxuICAgIG9ba10gPSB2IGZvciBvd24gaywgdiBvZiBvcHRpb25zXG4gICAgby5iYXJlID0gb24gIyBlbnN1cmUgcmV0dXJuIHZhbHVlXG4gICAganMgPSBjb21waWxlIGNvZGUsIG9cbiAgICBpZiBzYW5kYm94IGlzIGdsb2JhbFxuICAgICAgICB2bS5ydW5JblRoaXNDb250ZXh0IGpzXG4gICAgZWxzZVxuICAgICAgICB2bS5ydW5JbkNvbnRleHQganMsIHNhbmRib3hcblxuIyAwMDAwMDAwMCAgIDAwMDAwMDAwICAgMDAwMDAwMCAgIDAwMCAgIDAwMDAwMDAgIDAwMDAwMDAwMCAgMDAwMDAwMDAgIDAwMDAwMDAwICAgXG4jIDAwMCAgIDAwMCAgMDAwICAgICAgIDAwMCAgICAgICAgMDAwICAwMDAgICAgICAgICAgMDAwICAgICAwMDAgICAgICAgMDAwICAgMDAwICBcbiMgMDAwMDAwMCAgICAwMDAwMDAwICAgMDAwICAwMDAwICAwMDAgIDAwMDAwMDAgICAgICAwMDAgICAgIDAwMDAwMDAgICAwMDAwMDAwICAgIFxuIyAwMDAgICAwMDAgIDAwMCAgICAgICAwMDAgICAwMDAgIDAwMCAgICAgICAwMDAgICAgIDAwMCAgICAgMDAwICAgICAgIDAwMCAgIDAwMCAgXG4jIDAwMCAgIDAwMCAgMDAwMDAwMDAgICAwMDAwMDAwICAgMDAwICAwMDAwMDAwICAgICAgMDAwICAgICAwMDAwMDAwMCAgMDAwICAgMDAwICBcblxuZXhwb3J0cy5yZWdpc3RlciA9IC0+IHJlcXVpcmUgJy4vcmVnaXN0ZXInXG5cbmV4cG9ydHMuX2NvbXBpbGVGaWxlID0gKGZpbGVuYW1lLCBzb3VyY2VNYXAgPSBubywgaW5saW5lTWFwID0gbm8pIC0+XG4gICAgXG4gICAgcmF3ID0gZnMucmVhZEZpbGVTeW5jIGZpbGVuYW1lLCAndXRmOCdcbiAgICAjIFN0cmlwIHRoZSBVbmljb2RlIGJ5dGUgb3JkZXIgbWFyaywgaWYgdGhpcyBmaWxlIGJlZ2lucyB3aXRoIG9uZS5cbiAgICBzdHJpcHBlZCA9IGlmIHJhdy5jaGFyQ29kZUF0KDApIGlzIDB4RkVGRiB0aGVuIHJhdy5zdWJzdHJpbmcgMSBlbHNlIHJhd1xuXG4gICAgdHJ5XG4gICAgICAgIGFuc3dlciA9IGNvbXBpbGUgc3RyaXBwZWQsIHtcbiAgICAgICAgICAgIGZpbGVuYW1lLCBzb3VyY2VNYXAsIGlubGluZU1hcFxuICAgICAgICAgICAgc291cmNlRmlsZXM6IFtmaWxlbmFtZV1cbiAgICAgICAgfVxuICAgIGNhdGNoIGVyclxuICAgICAgICAjIEFzIHRoZSBmaWxlbmFtZSBhbmQgY29kZSBvZiBhIGR5bmFtaWNhbGx5IGxvYWRlZCBmaWxlIHdpbGwgYmUgZGlmZmVyZW50XG4gICAgICAgICMgZnJvbSB0aGUgb3JpZ2luYWwgZmlsZSBjb21waWxlZCB3aXRoIEtvZmZlZS5ydW4sIGFkZCB0aGF0XG4gICAgICAgICMgaW5mb3JtYXRpb24gdG8gZXJyb3Igc28gaXQgY2FuIGJlIHByZXR0eS1wcmludGVkIGxhdGVyLlxuICAgICAgICB0aHJvdyBoZWxwZXJzLnVwZGF0ZVN5bnRheEVycm9yIGVyciwgc3RyaXBwZWQsIGZpbGVuYW1lXG5cbiAgICBhbnN3ZXJcblxuIyAwMDAgICAgICAwMDAwMDAwMCAgMDAwICAgMDAwICAwMDAwMDAwMCAgMDAwMDAwMDAgICBcbiMgMDAwICAgICAgMDAwICAgICAgICAwMDAgMDAwICAgMDAwICAgICAgIDAwMCAgIDAwMCAgXG4jIDAwMCAgICAgIDAwMDAwMDAgICAgIDAwMDAwICAgIDAwMDAwMDAgICAwMDAwMDAwICAgIFxuIyAwMDAgICAgICAwMDAgICAgICAgIDAwMCAwMDAgICAwMDAgICAgICAgMDAwICAgMDAwICBcbiMgMDAwMDAwMCAgMDAwMDAwMDAgIDAwMCAgIDAwMCAgMDAwMDAwMDAgIDAwMCAgIDAwMCAgXG5cbmxleGVyID0gbmV3IExleGVyICMgSW5zdGFudGlhdGUgYSBMZXhlciBmb3Igb3VyIHVzZSBoZXJlLlxuXG4jIFRoZSByZWFsIExleGVyIHByb2R1Y2VzIGEgZ2VuZXJpYyBzdHJlYW0gb2YgdG9rZW5zLiBUaGlzIG9iamVjdCBwcm92aWRlcyBhXG4jIHRoaW4gd3JhcHBlciBhcm91bmQgaXQsIGNvbXBhdGlibGUgd2l0aCB0aGUgSmlzb24gQVBJLiBXZSBjYW4gdGhlbiBwYXNzIGl0XG4jIGRpcmVjdGx5IGFzIGEgXCJKaXNvbiBsZXhlclwiLlxuXG5wYXJzZXIubGV4ZXIgPVxuICAgIFxuICAgIGxleDogLT5cbiAgICAgICAgdG9rZW4gPSBwYXJzZXIudG9rZW5zW0Bwb3MrK11cbiAgICAgICAgaWYgdG9rZW5cbiAgICAgICAgICAgIFt0YWcsIEB5eXRleHQsIEB5eWxsb2NdID0gdG9rZW5cbiAgICAgICAgICAgIHBhcnNlci5lcnJvclRva2VuID0gdG9rZW4ub3JpZ2luIG9yIHRva2VuXG4gICAgICAgICAgICBjb25zb2xlLmxvZyAnREFGVUsnLCB0b2tlbiBpZiBub3QgQHl5bGxvYz8uZmlyc3RfbGluZT9cbiAgICAgICAgICAgIEB5eWxpbmVubyA9IEB5eWxsb2MuZmlyc3RfbGluZVxuICAgICAgICBlbHNlXG4gICAgICAgICAgICB0YWcgPSAnJ1xuICAgICAgICB0YWdcbiAgICBzZXRJbnB1dDogKHRva2VucykgLT5cbiAgICAgICAgcGFyc2VyLnRva2VucyA9IHRva2Vuc1xuICAgICAgICBAcG9zID0gMFxuICAgIHVwY29taW5nSW5wdXQ6IC0+XG4gICAgICAgIFwiXCJcbiAgICAgICAgXG5wYXJzZXIueXkgPSByZXF1aXJlICcuL25vZGVzJyAjIE1ha2UgYWxsIHRoZSBBU1Qgbm9kZXMgdmlzaWJsZSB0byB0aGUgcGFyc2VyLlxuXG4jIE92ZXJyaWRlIEppc29uJ3MgZGVmYXVsdCBlcnJvciBoYW5kbGluZyBmdW5jdGlvbi5cblxucGFyc2VyLnl5LnBhcnNlRXJyb3IgPSAobWVzc2FnZSwge3Rva2VufSkgLT5cbiAgICBcbiAgICAjIERpc3JlZ2FyZCBKaXNvbidzIG1lc3NhZ2UsIGl0IGNvbnRhaW5zIHJlZHVuZGFudCBsaW5lIG51bWJlciBpbmZvcm1hdGlvbi5cbiAgICAjIERpc3JlZ2FyZCB0aGUgdG9rZW4sIHdlIHRha2UgaXRzIHZhbHVlIGRpcmVjdGx5IGZyb20gdGhlIGxleGVyIGluIGNhc2VcbiAgICAjIHRoZSBlcnJvciBpcyBjYXVzZWQgYnkgYSBnZW5lcmF0ZWQgdG9rZW4gd2hpY2ggbWlnaHQgcmVmZXIgdG8gaXRzIG9yaWdpbi5cbiAgICBcbiAgICB7ZXJyb3JUb2tlbiwgdG9rZW5zfSA9IHBhcnNlclxuICAgIFtlcnJvclRhZywgZXJyb3JUZXh0LCBlcnJvckxvY10gPSBlcnJvclRva2VuXG5cbiAgICBlcnJvclRleHQgPSBzd2l0Y2hcbiAgICAgICAgd2hlbiBlcnJvclRva2VuIGlzIHRva2Vuc1t0b2tlbnMubGVuZ3RoIC0gMV1cbiAgICAgICAgICAgICdlbmQgb2YgaW5wdXQnXG4gICAgICAgIHdoZW4gZXJyb3JUYWcgaW4gWydJTkRFTlQnLCAnT1VUREVOVCddXG4gICAgICAgICAgICAnaW5kZW50YXRpb24nXG4gICAgICAgIHdoZW4gZXJyb3JUYWcgaW4gWydJREVOVElGSUVSJywgJ05VTUJFUicsICdJTkZJTklUWScsICdTVFJJTkcnLCAnU1RSSU5HX1NUQVJUJywgJ1JFR0VYJywgJ1JFR0VYX1NUQVJUJ11cbiAgICAgICAgICAgIGVycm9yVGFnLnJlcGxhY2UoL19TVEFSVCQvLCAnJykudG9Mb3dlckNhc2UoKVxuICAgICAgICBlbHNlXG4gICAgICAgICAgICBoZWxwZXJzLm5hbWVXaGl0ZXNwYWNlQ2hhcmFjdGVyIGVycm9yVGV4dFxuXG4gICAgIyBUaGUgc2Vjb25kIGFyZ3VtZW50IGhhcyBhIGBsb2NgIHByb3BlcnR5LCB3aGljaCBzaG91bGQgaGF2ZSB0aGUgbG9jYXRpb24gZGF0YSBmb3IgdGhpcyB0b2tlbi4gXG4gICAgIyBVbmZvcnR1bmF0ZWx5LCBKaXNvbiBzZWVtcyB0byBzZW5kIGFuIG91dGRhdGVkIGBsb2NgIChmcm9tIHRoZSBwcmV2aW91cyB0b2tlbiksIFxuICAgICMgc28gd2UgdGFrZSB0aGUgbG9jYXRpb24gaW5mb3JtYXRpb24gZGlyZWN0bHkgZnJvbSB0aGUgbGV4ZXIuXG4gICAgXG4gICAgaGVscGVycy50aHJvd1N5bnRheEVycm9yIFwidW5leHBlY3RlZCAje2Vycm9yVGV4dH1cIiwgZXJyb3JMb2NcblxuIyAgMDAwMDAwMCAgIDAwMDAwMDAgICAwMDAgICAwMDAgIDAwMDAwMDAwICAgIDAwMDAwMDAgIDAwMDAwMDAwICAwMCAgICAgMDAgICAwMDAwMDAwICAgMDAwMDAwMDAgICBcbiMgMDAwICAgICAgIDAwMCAgIDAwMCAgMDAwICAgMDAwICAwMDAgICAwMDAgIDAwMCAgICAgICAwMDAgICAgICAgMDAwICAgMDAwICAwMDAgICAwMDAgIDAwMCAgIDAwMCAgXG4jIDAwMDAwMDAgICAwMDAgICAwMDAgIDAwMCAgIDAwMCAgMDAwMDAwMCAgICAwMDAgICAgICAgMDAwMDAwMCAgIDAwMDAwMDAwMCAgMDAwMDAwMDAwICAwMDAwMDAwMCAgIFxuIyAgICAgIDAwMCAgMDAwICAgMDAwICAwMDAgICAwMDAgIDAwMCAgIDAwMCAgMDAwICAgICAgIDAwMCAgICAgICAwMDAgMCAwMDAgIDAwMCAgIDAwMCAgMDAwICAgICAgICBcbiMgMDAwMDAwMCAgICAwMDAwMDAwICAgIDAwMDAwMDAgICAwMDAgICAwMDAgICAwMDAwMDAwICAwMDAwMDAwMCAgMDAwICAgMDAwICAwMDAgICAwMDAgIDAwMCAgICAgICAgXG5cbmdldFNvdXJjZU1hcCA9IChmaWxlbmFtZSkgLT5cbiAgICAgXG4gICAgIyBLb2ZmZWUgY29tcGlsZWQgaW4gYSBicm93c2VyIG1heSBnZXQgY29tcGlsZWQgd2l0aCBgb3B0aW9ucy5maWxlbmFtZWAgb2YgYDxhbm9ueW1vdXM+YCwgXG4gICAgIyBidXQgdGhlIGJyb3dzZXIgbWF5IHJlcXVlc3QgdGhlIHN0YWNrIHRyYWNlIHdpdGggdGhlIGZpbGVuYW1lIG9mIHRoZSBzY3JpcHQgZmlsZS5cbiAgICBcbiAgICBpZiBzb3VyY2VNYXBzW2ZpbGVuYW1lXT9cbiAgICAgICAgc291cmNlTWFwc1tmaWxlbmFtZV1cbiAgICBlbHNlIGlmIHNvdXJjZU1hcHNbJzxhbm9ueW1vdXM+J10/XG4gICAgICAgIHNvdXJjZU1hcHNbJzxhbm9ueW1vdXM+J11cbiAgICBlbHNlIGlmIHNvdXJjZXNbZmlsZW5hbWVdP1xuICAgICAgICBhbnN3ZXIgPSBjb21waWxlIHNvdXJjZXNbZmlsZW5hbWVdLFxuICAgICAgICAgICAgZmlsZW5hbWU6IGZpbGVuYW1lXG4gICAgICAgICAgICBzb3VyY2VNYXA6IHllc1xuICAgICAgICBhbnN3ZXIuc291cmNlTWFwXG4gICAgZWxzZVxuICAgICAgICBudWxsXG5cbiMgIDAwMDAwMDAgIDAwMDAwMDAwMCAgIDAwMDAwMDAgICAgMDAwMDAwMCAgMDAwICAgMDAwICAwMDAwMDAwMDAgIDAwMDAwMDAwICAgIDAwMDAwMDAgICAgMDAwMDAwMCAgMDAwMDAwMDAgIFxuIyAwMDAgICAgICAgICAgMDAwICAgICAwMDAgICAwMDAgIDAwMCAgICAgICAwMDAgIDAwMCAgICAgIDAwMCAgICAgMDAwICAgMDAwICAwMDAgICAwMDAgIDAwMCAgICAgICAwMDAgICAgICAgXG4jIDAwMDAwMDAgICAgICAwMDAgICAgIDAwMDAwMDAwMCAgMDAwICAgICAgIDAwMDAwMDAgICAgICAgMDAwICAgICAwMDAwMDAwICAgIDAwMDAwMDAwMCAgMDAwICAgICAgIDAwMDAwMDAgICBcbiMgICAgICAwMDAgICAgIDAwMCAgICAgMDAwICAgMDAwICAwMDAgICAgICAgMDAwICAwMDAgICAgICAwMDAgICAgIDAwMCAgIDAwMCAgMDAwICAgMDAwICAwMDAgICAgICAgMDAwICAgICAgIFxuIyAwMDAwMDAwICAgICAgMDAwICAgICAwMDAgICAwMDAgICAwMDAwMDAwICAwMDAgICAwMDAgICAgIDAwMCAgICAgMDAwICAgMDAwICAwMDAgICAwMDAgICAwMDAwMDAwICAwMDAwMDAwMCAgXG5cbiMgQmFzZWQgb24gW21pY2hhZWxmaWNhcnJhL0tvZmZlZVJlZHV4XShodHRwOi8vZ29vLmdsL1pUeDFwKVxuIyBOb2RlSlMgLyBWOCBoYXZlIG5vIHN1cHBvcnQgZm9yIHRyYW5zZm9ybWluZyBwb3NpdGlvbnMgaW4gc3RhY2sgdHJhY2VzIHVzaW5nXG4jIHNvdXJjZU1hcCwgc28gd2UgbXVzdCBtb25rZXktcGF0Y2ggRXJyb3IgdG8gZGlzcGxheSBLb2ZmZWUgc291cmNlIHBvc2l0aW9ucy5cblxuRXJyb3IucHJlcGFyZVN0YWNrVHJhY2UgPSAoZXJyLCBzdGFjaykgLT5cbiAgICBcbiAgICBnZXRTb3VyY2VNYXBwaW5nID0gKGZpbGVuYW1lLCBsaW5lLCBjb2x1bW4pIC0+XG4gICAgICAgIHNvdXJjZU1hcCA9IGdldFNvdXJjZU1hcCBmaWxlbmFtZVxuICAgICAgICBhbnN3ZXIgPSBzb3VyY2VNYXAuc291cmNlTG9jYXRpb24gW2xpbmUgLSAxLCBjb2x1bW4gLSAxXSBpZiBzb3VyY2VNYXA/XG4gICAgICAgIGlmIGFuc3dlcj8gdGhlbiBbYW5zd2VyWzBdICsgMSwgYW5zd2VyWzFdICsgMV0gZWxzZSBudWxsXG5cbiAgICBmcmFtZXMgPSBmb3IgZnJhbWUgaW4gc3RhY2tcbiAgICAgICAgYnJlYWsgaWYgZnJhbWUuZ2V0RnVuY3Rpb24oKSBpcyBleHBvcnRzLnJ1blxuICAgICAgICBcIiAgICAgICAgYXQgI3tmb3JtYXRTb3VyY2VQb3NpdGlvbiBmcmFtZSwgZ2V0U291cmNlTWFwcGluZ31cIlxuXG4gICAgXCIje2Vyci50b1N0cmluZygpfVxcbiN7ZnJhbWVzLmpvaW4gJ1xcbid9XFxuXCJcbiAgICBcbiMgQmFzZWQgb24gaHR0cDovL3Y4Lmdvb2dsZWNvZGUuY29tL3N2bi9icmFuY2hlcy9ibGVlZGluZ19lZGdlL3NyYy9tZXNzYWdlcy5qc1xuIyBNb2RpZmllZCB0byBoYW5kbGUgc291cmNlTWFwXG5cbmZvcm1hdFNvdXJjZVBvc2l0aW9uID0gKGZyYW1lLCBnZXRTb3VyY2VNYXBwaW5nKSAtPlxuICAgIFxuICAgIGZpbGVuYW1lID0gdW5kZWZpbmVkXG4gICAgZmlsZUxvY2F0aW9uID0gJydcblxuICAgIGlmIGZyYW1lLmlzTmF0aXZlKClcbiAgICAgICAgZmlsZUxvY2F0aW9uID0gXCJuYXRpdmVcIlxuICAgIGVsc2VcbiAgICAgICAgaWYgZnJhbWUuaXNFdmFsKClcbiAgICAgICAgICAgIGZpbGVuYW1lID0gZnJhbWUuZ2V0U2NyaXB0TmFtZU9yU291cmNlVVJMKClcbiAgICAgICAgICAgIGZpbGVMb2NhdGlvbiA9IFwiI3tmcmFtZS5nZXRFdmFsT3JpZ2luKCl9LCBcIiB1bmxlc3MgZmlsZW5hbWVcbiAgICAgICAgZWxzZVxuICAgICAgICAgICAgZmlsZW5hbWUgPSBmcmFtZS5nZXRGaWxlTmFtZSgpXG5cbiAgICAgICAgZmlsZW5hbWUgb3I9IFwiPGFub255bW91cz5cIlxuXG4gICAgICAgIGxpbmUgPSBmcmFtZS5nZXRMaW5lTnVtYmVyKClcbiAgICAgICAgY29sdW1uID0gZnJhbWUuZ2V0Q29sdW1uTnVtYmVyKClcblxuICAgICAgICAjIENoZWNrIGZvciBhIHNvdXJjZU1hcCBwb3NpdGlvblxuICAgICAgICBzb3VyY2UgPSBnZXRTb3VyY2VNYXBwaW5nIGZpbGVuYW1lLCBsaW5lLCBjb2x1bW5cbiAgICAgICAgZmlsZUxvY2F0aW9uID1cbiAgICAgICAgICAgIGlmIHNvdXJjZVxuICAgICAgICAgICAgICAgIFwiI3tmaWxlbmFtZX06I3tzb3VyY2VbMF19OiN7c291cmNlWzFdfVwiXG4gICAgICAgICAgICBlbHNlXG4gICAgICAgICAgICAgICAgXCIje2ZpbGVuYW1lfToje2xpbmV9OiN7Y29sdW1ufVwiXG5cbiAgICBmdW5jdGlvbk5hbWUgPSBmcmFtZS5nZXRGdW5jdGlvbk5hbWUoKVxuICAgIGlzQ29uc3RydWN0b3IgPSBmcmFtZS5pc0NvbnN0cnVjdG9yKClcbiAgICBpc01ldGhvZENhbGwgPSBub3QgKGZyYW1lLmlzVG9wbGV2ZWwoKSBvciBpc0NvbnN0cnVjdG9yKVxuXG4gICAgaWYgaXNNZXRob2RDYWxsXG4gICAgICAgIG1ldGhvZE5hbWUgPSBmcmFtZS5nZXRNZXRob2ROYW1lKClcbiAgICAgICAgdHlwZU5hbWUgPSBmcmFtZS5nZXRUeXBlTmFtZSgpXG5cbiAgICAgICAgaWYgZnVuY3Rpb25OYW1lXG4gICAgICAgICAgICB0cCA9IGFzID0gJydcbiAgICAgICAgICAgIGlmIHR5cGVOYW1lIGFuZCBmdW5jdGlvbk5hbWUuaW5kZXhPZiB0eXBlTmFtZVxuICAgICAgICAgICAgICAgIHRwID0gXCIje3R5cGVOYW1lfS5cIlxuICAgICAgICAgICAgaWYgbWV0aG9kTmFtZSBhbmQgZnVuY3Rpb25OYW1lLmluZGV4T2YoXCIuI3ttZXRob2ROYW1lfVwiKSAhPSBmdW5jdGlvbk5hbWUubGVuZ3RoIC0gbWV0aG9kTmFtZS5sZW5ndGggLSAxXG4gICAgICAgICAgICAgICAgYXMgPSBcIiBbYXMgI3ttZXRob2ROYW1lfV1cIlxuXG4gICAgICAgICAgICBcIiN7dHB9I3tmdW5jdGlvbk5hbWV9I3thc30gKCN7ZmlsZUxvY2F0aW9ufSlcIlxuICAgICAgICBlbHNlXG4gICAgICAgICAgICBcIiN7dHlwZU5hbWV9LiN7bWV0aG9kTmFtZSBvciAnPGFub255bW91cz4nfSAoI3tmaWxlTG9jYXRpb259KVwiXG4gICAgZWxzZSBpZiBpc0NvbnN0cnVjdG9yXG4gICAgICAgIFwibmV3ICN7ZnVuY3Rpb25OYW1lIG9yICc8YW5vbnltb3VzPid9ICgje2ZpbGVMb2NhdGlvbn0pXCJcbiAgICBlbHNlIGlmIGZ1bmN0aW9uTmFtZVxuICAgICAgICBcIiN7ZnVuY3Rpb25OYW1lfSAoI3tmaWxlTG9jYXRpb259KVwiXG4gICAgZWxzZVxuICAgICAgICBmaWxlTG9jYXRpb25cbiAgICBcbiAgICAiXX0=
//# sourceURL=../src/koffee.coffee